### ISSUE TITLE
too many file descriptors in select()

### ISSUE THREAD

**Issue by Tjoe23** [DIGITALCRIMINALS/OnlyFans#107]
Hi guys anyone know how to fix this error? had no issues until one of the most recent updates. currently running the latest on win 10.

Traceback (most recent call last):
File "C:\Users\Downloads\OnlyFans-master\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

**Comment by Shingotink** [comment]
Getting the same error, did you get it working?

**Comment by wireman21** [comment]
having this same issue, i believe it is because i am subscribed to too many profiles (currently have 803 active subscriptions). is there a way to just download one profile? if yes can someone point me in the direction of how to do this?

**Comment by wireman21** [comment]
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome . | xxxxx
Traceback (most recent call last):
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OnlyFans-7.6\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

**Comment by aboredpervert** [comment]
This may be a nasty side effect of the quick fix done in https://github.com/DIGITALCRIMINALS/OnlyFans/commit/69ffbda10dd8e09840db5d2fc907ff26935dad9c.

Try removing those two lines in `start_ofd.py`:

    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

Then see if it still happens. You will probably get another error during exit, but you can ignore them.

**Comment by aboredpervert** [comment]
I will try to make a PR to try to fix the underlying problem soon.

**Comment by aboredpervert** [comment]
As much as I try and try, I am unable to reproduce the original crash-on-exit from #44 on 3.10 now...

**Comment by Gamma-Velorum** [comment]
> This may be a nasty side effect of the quick fix done in [69ffbda](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/69ffbda10dd8e09840db5d2fc907ff26935dad9c).
> 
> Try removing those two lines in `start_ofd.py`:
> 
> ```
> if sys.platform == "win32":
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```
> 
> Then see if it still happens. You will probably get another error during exit, but you can ignore them.

This resolved it for me. Thanks. Any idea when the fix will be submitted?

**Comment by aboredpervert** [comment]
> This resolved it for me. Thanks. Any idea when the fix will be submitted?

I was trying to reproduce the original issue that caused this change to be added, but I was unable 😞

I wanted to solve the underlying issue before removing that. However it's better to have a harmless exception at exit than having the thing crash, so maybe I should submit it right away and find the real fix later.

**Comment by Daironman78** [comment]
> This may be a nasty side effect of the quick fix done in [69ffbda](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/69ffbda10dd8e09840db5d2fc907ff26935dad9c).
> 
> Try removing those two lines in `start_ofd.py`:
> 
> ```
> if sys.platform == "win32":
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```
> 
> Then see if it still happens. You will probably get another error during exit, but you can ignore them.

Ok maybe Im just not as tech savy but I'm having this same issue where I get the "too many file descriptors in select" error......after downloading the new version as well as 3.10  and am a little confused on where you say try removing those two lines. Can you explain what you mean specifically. Is there a specific command needed to remove a line. I have tried everything after putting in Start_ofd.py (for example remove line 315  or even the asyncio.set line. Just not sure what I need to do specifically. Sorry if I sound dumb.

**Comment by Daironman78** [comment]
> > This resolved it for me. Thanks. Any idea when the fix will be submitted?
> 
> I was trying to reproduce the original issue that caused this change to be added, but I was unable 😞
> 
> I wanted to solve the underlying issue before removing that. However it's better to have a harmless exception at exit than having the thing crash, so maybe I should submit it right away and find the real fix later.

Can you let me know what you remove specifically and/or how you were able to fix your problem with this as I am having the same issue.

**Comment by DIGITALCRIMINALS** [comment]
> > > This resolved it for me. Thanks. Any idea when the fix will be submitted?
> > 
> > 
> > I was trying to reproduce the original issue that caused this change to be added, but I was unable disappointed
> > I wanted to solve the underlying issue before removing that. However it's better to have a harmless exception at exit than having the thing crash, so maybe I should submit it right away and find the real fix later.
> 
> Can you let me know what you remove specifically and/or how you were able to fix your problem with this as I am having the same issue.

https://github.com/DIGITALCRIMINALS/OnlyFans/pull/180
