### ISSUE TITLE
KeyError: 'user_id'

### ISSUE THREAD

**Issue by otisrush** [DIGITALCRIMINALS/OnlyFans#111]
Hello, I got this error with the latest version:

```
Traceback (most recent call last):
  File "E:\XXX\,,,OFN\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\XXX\,,,OFN\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "E:\XXX\,,,OFN\datascraper\main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "E:\XXX\,,,OFN\modules\onlyfans.py", line 415, in paid_content_scraper
    await process_metadata(
  File "E:\XXX\,,,OFN\modules\onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "E:\XXX\,,,OFN\helpers\main_helper.py", line 575, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'
```

**Comment by DIGITALCRIMINALS** [comment]
Which site are you trying to scrape

**Comment by otisrush** [comment]
Sorry, Onlyfans

**Comment by docholllidae** [comment]
i'm getting this too, using the latest commit & python3.10

the other two scrapers work fine

**Comment by docholllidae** [comment]
Ubuntu 20.04.3  and  python3.10

`python3 start_ofd.py`
`0` for OnlyFans
`0` for Default Profile
results in the above error

`python3 start_ofd.py`
`0` for OnlyFans
`1` for myusername
I do not get the error

@otisrush

**Comment by otisrush** [comment]
doesn't make any difference for me, sadly

**Comment by otisrush** [comment]
newest update did not fix the issue for me

**Comment by DIGITALCRIMINALS** [comment]
Which user are you trying to scrape

**Comment by otisrush** [comment]
both all and just my profile

**Comment by otisrush** [comment]
it always happens after the same model (in initial scraping) if that helps

**Comment by DIGITALCRIMINALS** [comment]
I meant which model

**Comment by otisrush** [comment]
oh in that case, Cubbixoxo

**Comment by otisrush** [comment]
all fixed! thanks!
