### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by OFtaa** [DIGITALCRIMINALS/OnlyFans#113]
When trying to download a model's content on OnlyFans using the latest version and Python 3.10, I'm occasionally running into this error:

Traceback (most recent call last):
File "D:\ofs\start_ofd.py", line 104, in
asyncio.run(main())
File "C:\Users\usert\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
return future.result()
File "D:\ofs\start_ofd.py", line 86, in main
api = await main_datascraper.start_datascraper(
File "D:\ofs\datascraper\main_datascraper.py", line 103, in start_datascraper
await main_helper.process_downloads(api, module)
File "D:\ofs\helpers\main_helper.py", line 972, in process_downloads
await module.prepare_downloads(subscription)
File "D:\ofs\modules\onlyfans.py", line 1252, in prepare_downloads
await main_helper.async_downloads(download_list, subscription)
File "D:\ofs\helpers\main_helper.py", line 255, in async_downloads
results = await asyncio.ensure_future(run(download_list))
File "D:\ofs\helpers\main_helper.py", line 250, in run
await asyncio.gather(*tasks)
File "D:\ofs\helpers\main_helper.py", line 227, in process_download
status_code = await write_data(
File "D:\ofs\helpers\main_helper.py", line 1049, in write_data
os.replace(partial_path, download_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\ofs\.sites\OnlyFans\{MODELNAME}\Posts\Free\Images\2208x1170_5010fa0e24ba004aff7220608bdb8772-1e56839d598a.jpg.part' -> 'D:\ofs\.sites\OnlyFans\{MODELNAME}\Posts\Free\Images\2208x1170_5010fa0e24ba004aff7220608bdb8772.jpg'

**Comment by aboredpervert** [comment]
So it would mean that multiple downloads are trying to download to the exact same file name at the same time?
That's not supposed to happen...

**Comment by Comfy-Mittens** [comment]
I'm getting this issue after pulling master. Have you found a solution or workaround?

**Comment by aboredpervert** [comment]
That's very special because (especially when using the original filenames), there should not be two medias with the same filename.
I guess a workaround will be needed to handle this case.
