### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp_socks'

### ISSUE THREAD

**Issue by kccomikeyga** [DIGITALCRIMINALS/OnlyFans#115]
Clean install of Python 3.10 and clean install of OFScraper 4.6.  After running requirements.txt, I am greeted with the following error after running start_ofd.py:

Traceback (most recent call last):
  File "E:\OF_SCRAPER\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "E:\OF_SCRAPER\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "E:\OF_SCRAPER\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "E:\OF_SCRAPER\apis\api_helper.py", line 30, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'

**Comment by kccomikeyga** [comment]
Nevermind.  I saw the page.
