### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#118]
Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "D:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "D:\OnlyFans Scrapper\helpers\main_helper.py", line 939, in process_profiles
    auth = api.add_auth(json_auth)
  File "D:\OnlyFans Scrapper\apis\onlyfans\onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "D:\OnlyFans Scrapper\apis\onlyfans\classes\create_auth.py", line 44, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "D:\OnlyFans Scrapper\apis\api_helper.py", line 96, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DIGITALCRIMINALS** [comment]
You've messed up one of your json files

**Comment by Site3op** [comment]
> You've messed up one of your json files

I would assume so but it was working fine several times. I believe it had something to do with Github being down or my location since switching to a VPN magically made it work.
