### ISSUE TITLE
Getting an "AttributeError: 'int' object has no attribute 'isdigit'" on launch

### ISSUE THREAD

**Issue by taa770567** [DIGITALCRIMINALS/OnlyFans#125]
I keep getting this (python and requirements are up to date) :

Traceback (most recent call last):
  File "C:\Users\tenho\Desktop\OnlyFans-master\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\tenho\Desktop\OnlyFans-master\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\tenho\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 58, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "C:\Users\tenho\Desktop\OnlyFans-master\helpers\main_helper.py", line 898, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by taa770567** [comment]
sorry just saw

**Comment by tonyctalope** [comment]
I just fixe this line in the config.json and then it works.
auto_profile_choice": []
