### ISSUE TITLE
string_match bug

### ISSUE THREAD

**Issue by edmundackah** [DIGITALCRIMINALS/OnlyFans#128]
Can start the latest release, keep getting the following stack trace

```
Traceback (most recent call last):
  File "C:\Users\username\Documents\GitHub\OnlyFans\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "C:\Users\username\Documents\GitHub\OnlyFans\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax
```

**Comment by medlhed420** [comment]
@edmundackah I'm seeing this too. What was the fix?
