### ISSUE TITLE
New issue after adding geckodriver

### ISSUE THREAD

**Issue by HoneyBadger116** [DIGITALCRIMINALS/OnlyFans#129]
Keep telling me to add geckodriver to extras so I did. Now I have a new issue.

Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "D:\OF Rip\OnlyFans-master\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OF Rip\OnlyFans-master\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OF Rip\OnlyFans-master\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\OF Rip\OnlyFans-master\modules\onlyfans.py", line 117, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "D:\OF Rip\OnlyFans-master\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "D:\OF Rip\OnlyFans-master\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\kioro\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\kioro\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\firefox\webdriver.py", line 175, in __init__
    self.service.start()
  File "C:\Users\kioro\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 101, in start
    self.assert_process_still_running()
  File "C:\Users\kioro\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 113, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service D:\OF Rip\OnlyFans-master\extras\OFLogin\geckodriver.exe unexpectedly exited. Status code was: 64

**Comment by Troll180** [comment]
Same issue here, it only does that for OF. Fansly work perfectly, any solution? Thx

**Comment by Troll180** [comment]
I had the same issue, I made a new folder for the OF scraper 7.6.1, reinstalled the requirements and made a new auth.json , my cookies has changed, as well as the user-agent and the new line x-bc .
I added geckodriver 0.27.0 as asked too and it work for me now. I'm a pure noob, if I made it, you can too:)

**Comment by DIGITALCRIMINALS** [comment]
I disabled browser auth for now
