### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/OnlyFans#137]
E:\OnlyFans-master>python start_ofd.py
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 937, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Expected object or value

config.json
```
{
  "info": {
    "version": 7.2
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": true
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "e9e67ef8ba2911eb9dec240a641d41ce"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "0",
        "auto_model_choice": false,
        "auto_media_choice": "1,2",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "Metadata\\{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [
          ""
        ],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": false,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "Metadata\\{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [
          ""
        ],
        "webhook": true
      }
    }
  }
}
```

thanks for support

**Comment by DIGITALCRIMINALS** [comment]
The issue is your auth.json not config.json

**Comment by CannotTouch** [comment]
here the auth.json
where you see CORRECT there are my data, double checked that are correct

`
{
  "auth": {
    "username": "default",
    "cookie": "auth_id=CORRECT; sess=CORRECT; auth_hash=; auth_uniq_CORRECT=; auth_uid_CORRECT=;",
    "x_bc": "CORRECT",
    "user_agent": "CORRECT",
    "email": "CORRECT",
    "password": "CORRECT",
    "hashed": false,
    "support_2fa": true,
    "active": active
  }
}
`

**Comment by DIGITALCRIMINALS** [comment]
> here the auth.json where you see CORRECT there are my data, double checked that are correct
> 
> ```
> {
>   "auth": {
>     "username": "default",
>     "cookie": "auth_id=CORRECT; sess=CORRECT; auth_hash=; auth_uniq_CORRECT=; auth_uid_CORRECT=;",
>     "x_bc": "CORRECT",
>     "user_agent": "CORRECT",
>     "email": "CORRECT",
>     "password": "CORRECT",
>     "hashed": false,
>     "support_2fa": true,
>     "active": active
>   }
> }
> ```

Replace active with true

**Comment by CannotTouch** [comment]
with 
"true": true
now it spam a lot of:
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.

thanks for support

**Comment by DIGITALCRIMINALS** [comment]
Are you subscribed to any models

**Comment by CannotTouch** [comment]
yep several

**Comment by DIGITALCRIMINALS** [comment]
Backup config.json and let the script run with a fresh one to see if it works

**Comment by DIGITALCRIMINALS** [comment]
Change "auto_profile_choice": "0", to "auto_profile_choice": "default",

**Comment by CannotTouch** [comment]
```
"supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "default",
        "auto_model_choice": false,
```

same spam

**Comment by DIGITALCRIMINALS** [comment]
I'd need to your auth.json details to fix this

If you want you can send them here

datahoarders@protonmail.com

**Comment by CannotTouch** [comment]
with a new config (moved the old, and generated a new one without any change)

```
E:\OnlyFans-master>python start_ofd.py
The .settings\config.json file has been updated. Fill in whatever you need to fill in and then press enter when done.

Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
```
should i email the auth.json than?

**Comment by DIGITALCRIMINALS** [comment]
Yes

**Comment by CannotTouch** [comment]
done

**Comment by DIGITALCRIMINALS** [comment]
Going to move this issue here

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/142
