### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by jcisz** [DIGITALCRIMINALS/OnlyFans#14]
Hi i'm getting this error with this model in specific, i have tried with other 2 accounts and works great. Already did a fresh install and clear venv

``` cmd
Scrape Processing
Name: luisatavarests
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████| 356/356 [00:00<00:00, 3960.49it/s]
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "*\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans\datascraper\main_datascraper.py", line 95, in start_datascraper
    await main_helper.process_names(
  File "F:\OnlyFans\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "F:\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "F:\OnlyFans\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "F:\OnlyFans\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "F:\OnlyFans\helpers\main_helper.py", line 565, in export_sqlite
    post_db = result.filter_by(post_id=post_id).first()
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\orm\query.py", line 2760, in first
    return self.limit(1)._iter().first()
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\orm\query.py", line 2844, in _iter
    result = self.session.execute(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "F:\OnlyFans\scraper\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT posts.id AS posts_id, posts.post_id AS posts_post_id, posts.text AS posts_text, posts.price AS posts_price, posts.paid AS posts_paid, posts.archived AS posts_archived, posts.created_at AS posts_created_at
FROM posts
WHERE posts.post_id = ?
 LIMIT ? OFFSET ?]
[parameters: (202493683, 1, 0)]
(Background on this error at: http://sqlalche.me/e/14/4xp6)
```

**Comment by DIGITALCRIMINALS** [comment]
What's your OS?

**Comment by jcisz** [comment]
Win 10 21H1

**Comment by DIGITALCRIMINALS** [comment]
Delete the metadata folder or rename the files in the metadata folder to something else

**Comment by jcisz** [comment]
Fixed. Thanks
