### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Eviepayne** [DIGITALCRIMINALS/OnlyFans#16]
I've tried a number of the workarounds I've found but I still get this on a few models.
```
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "/usr/src/app/modules/onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 778, in prepare_scraper
    unrefined_result = pool.starmap(
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/src/app/modules/onlyfans.py", line 1193, in media_scraper
    for temp_media in medias:
TypeError: 'NoneType' object is not iterable
```

**Comment by DIGITALCRIMINALS** [comment]
which model?

**Comment by lucky1luc** [comment]
D:\Data\OnlyFans-7.5>python start_ofd.py
Auth (V1) Attempt 1/10
Internal error
Auth (V1) Attempt 2/10
Welcome xxxxxxxxxx | xxxxxxxxx
Scraping Paid Content
Traceback (most recent call last):
  File "D:\Data\OnlyFans-7.5\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Data\OnlyFans-7.5\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Data\OnlyFans-7.5\datascraper\main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "D:\Data\OnlyFans-7.5\modules\onlyfans.py", line 322, in paid_content_scraper
    paid_contents = await authed.get_paid_content()
  File "D:\Data\OnlyFans-7.5\apis\onlyfans\classes\create_auth.py", line 447, in get_paid_content
    results2 = await self.get_paid_content(
  File "D:\Data\OnlyFans-7.5\apis\onlyfans\classes\create_auth.py", line 447, in get_paid_content
    results2 = await self.get_paid_content(
  File "D:\Data\OnlyFans-7.5\apis\onlyfans\classes\create_auth.py", line 450, in get_paid_content
    final_results.extend(results2)
TypeError: 'error_details' object is not iterable

**Comment by lucky1luc** [comment]
After running updater.py:

Scrape Processing
Name: carla-piece-of-art
Type: Profile
Type: Stories
Traceback (most recent call last):
  File "D:\Data\OnlyFans-7.5\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Data\OnlyFans-7.5\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Data\OnlyFans-7.5\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "D:\Data\OnlyFans-7.5\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\Data\OnlyFans-7.5\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\Data\OnlyFans-7.5\modules\onlyfans.py", line 787, in prepare_scraper
    highlight = await subscription.get_highlights(hightlight_id=highlight.id)
  File "D:\Data\OnlyFans-7.5\apis\onlyfans\classes\create_user.py", line 276, in get_highlights
    results = [create_story(x) for x in results["stories"]]
TypeError: 'error_details' object is not subscriptable

**Comment by lucky1luc** [comment]
very bizarre, now it works
