### ISSUE TITLE
I can't login with v7.6.1

### ISSUE THREAD

**Issue by van2727** [DIGITALCRIMINALS/OnlyFans#166]
I uses python 3.10 and try in other SO as well, but i can't login

Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\modules\onlyfans.py", line 117, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    self.service.start()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service G:\drive\OnlyFans-7.6.1\OnlyFans-7.6.1\extras\OFLogin\geckodriver.exe unexpectedly exited. Status code was: 64

**Comment by DIGITALCRIMINALS** [comment]
socks5://user:pass@host:port
