### ISSUE TITLE
Issues in line 23, 20, 22, 29

### ISSUE THREAD

**Issue by pnaaas** [DIGITALCRIMINALS/OnlyFans#172]
Hi! I need help. I Windows, i get errors in 

PS C:\Users\musta\Downloads\OnlyFans-master> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\musta\Downloads\OnlyFans-master\start_ofd.py", line 23, in <module>
    main_test.check_config()
  File "C:\Users\musta\Downloads\OnlyFans-master\tests\main_test.py", line 20, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\musta\Downloads\OnlyFans-master\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "C:\Users\musta\Downloads\OnlyFans-master\apis\api_helper.py", line 29, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'

In Linux, don't work too. Not error, but execute and more nothing, just enter screen.

**Comment by lordofcookies** [comment]
Feels like the error you get when you're missing a specific module. Try to see if you can reinstall aiohttp_socks.

For example, from the main page / instructions:

pip install --upgrade --user -r requirements.txt

**Comment by marcintosch** [comment]
And be sure to execute the script with Python 3.10 - it can be helpful to upgrade the requirements with pip3 instead of pip.
