### ISSUE TITLE
TypeError: 'error_details' object is not iterable

### ISSUE THREAD

**Issue by MonkeyKingViper** [DIGITALCRIMINALS/OnlyFans#186]
Something broke within the last couple hours. Was working fine last night and this morning. Come back later and this happens. Nothing has changed in my setup since the last success.

Auth (V1) Attempt 1/10
Welcome "redacted" | "redacted"
Traceback (most recent call last):
  File "P:\OnlyFans-7.6.1\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "P:\OnlyFans-7.6.1\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "P:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "P:\OnlyFans-7.6.1\modules\onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "P:\OnlyFans-7.6.1\modules\onlyfans.py", line 1271, in manage_subscriptions
    for remote_blacklist in remote_blacklists:
TypeError: 'error_details' object is not iterable

**Comment by MonkeyKingViper** [comment]
Nevermind. Must have been an internal issue on their side. Everything is working again.
