### ISSUE TITLE
KeyError: "Created_at"

### ISSUE THREAD

**Issue by Bum211** [DIGITALCRIMINALS/OnlyFans#196]
Has anyone running into this error. I finally got the scrapper to work but it is only scrapping some models and some gave me this error. Please kindly help! Thanks!

![Create_at error](https://user-images.githubusercontent.com/96312987/146594973-aae93bc0-5ddd-4fb2-95cd-b4f180e25d15.PNG)

**Comment by okanshine** [comment]
hey, how do you work scrapping ?

**Comment by tintinhamans** [comment]
I am using the provided Dockerfile and am also running into this issue:

```
Scrape Processing
Name: <redacted>
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
  0%|          | 0/387 [00:00<?, ?it/s]  0%|          | 1/387 [00:00<03:50,  1.68it/s]100%|██████████| 387/387 [00:00<00:00, 645.60it/s]Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/usr/src/app/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 841, in prepare_scraper
    await process_metadata(
  File "/usr/src/app/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/usr/src/app/helpers/main_helper.py", line 589, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 107, in <module>
    input()
EOFError: EOF when reading a line
Processing metadata.
Merging new metadata with legacy metadata.
Finished processing metadata.
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/usr/src/app/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 841, in prepare_scraper
    await process_metadata(
  File "/usr/src/app/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/usr/src/app/helpers/main_helper.py", line 589, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'
```

**Comment by xantror** [comment]
I am running release 7.6.1 using the provided Dockerfile and am also running into this issue:

```
Scrape Processing
Name: <redacted>
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
  0%|          | 0/387 [00:00<?, ?it/s]  0%|          | 1/387 [00:00<03:50,  1.68it/s]100%|██████████| 387/387 [00:00<00:00, 645.60it/s]Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/usr/src/app/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 841, in prepare_scraper
    await process_metadata(
  File "/usr/src/app/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/usr/src/app/helpers/main_helper.py", line 589, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 107, in <module>
    input()
EOFError: EOF when reading a line
Processing metadata.
Merging new metadata with legacy metadata.
Finished processing metadata.
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/usr/src/app/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 841, in prepare_scraper
    await process_metadata(
  File "/usr/src/app/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/usr/src/app/helpers/main_helper.py", line 589, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'
```

**Comment by xantror** [comment]
That being said, it just completed a run successfully after I switched to the latest commit (1fa838b). 

@Bum211 I recommend you have a go using the latest commit to see if that fixes the issue for you like it did for me.

**Comment by Bum211** [comment]
@xantror thank you for the comment and just want to ask how can I grab the latest commit and try running it? sorry I'm a noob and appreciate any instruction

**Comment by xantror** [comment]
Instead of downloading the from releases, use the following [dropdown](https://i.imgur.com/ja245L7.png) to either download the zip or clone the repo using a git util.

**Comment by Bum211** [comment]
@xantror thank you so much for the help here! I followed your instruction above and boost it up and it ran with no further issue! Thank you!

**Comment by xantror** [comment]
@DIGITALCRIMINALS, you can mark this issue as resolved as far as I am concerned.
