### ISSUE TITLE
Traceback in the start file, and some python files?

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINALS/OnlyFans#199]
Using latest python 3.10, also having installed the new requirements still throws up these errors. 
```Traceback (most recent call last):
  File "B:\Github\OnlyFans\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "B:\Github\OnlyFans\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "B:\Github\OnlyFans\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 937, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value```

**Comment by aboredpervert** [comment]
It means the JSON in your config or one of your auth files has an error in it.
