### ISSUE TITLE
path for profile is wrong

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINALS/OnlyFans#202]
```
Traceback (most recent call last):
  File "D:\OnlyFans-master\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans-master\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 63, in start_datascraper
    module.assign_vars(
  File "D:\OnlyFans-master\modules\onlyfans.py", line 61, in assign_vars
    profile_directory = main_helper.get_directory(
  File "D:\OnlyFans-master\helpers\main_helper.py", line 761, in get_directory
    directory = check_space(new_directories, min_size=min_drive_space)
  File "D:\OnlyFans-master\helpers\main_helper.py", line 774, in check_space
    obj_Disk = disk_usage(download_path)
  File "D:\OnlyFans-master\helpers\main_helper.py", line 78, in disk_usage
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OnlyFans-master\\.profiles'
```

**Comment by DIGITALCRIMINALS** [comment]
For now you can create the folder yourself and run the script, I'll fix this.
