### ISSUE TITLE
AtrributeError: 'error_details' object has no attribute "following"

### ISSUE THREAD

**Issue by 3otgjrq** [DIGITALCRIMINALS/OnlyFans#204]
Everything works great on OF. I try to run fansly and i've been getting this for a while now:
I am following people and have paid subscriptions. I've never gotten fansly to work.

Auth (V1) Attempt 1/10
Welcome None | <redacted>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002572F684730>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002572F684820>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002572F6847C0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002572F6848B0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002572F684760>
Traceback (most recent call last):
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\modules\fansly.py", line 1264, in manage_subscriptions
    results2 = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 310, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 300, in multi
    valid_subscriptions.following
AttributeError: 'error_details' object has no attribute 'following'

**Comment by Nick05491** [comment]
For what it's worth, I've seen a similar error when scraping OF...

**Comment by DIGITALCRIMINALS** [comment]
Try the latest commit

**Comment by 3otgjrq** [comment]
> Try the latest commit

Still same (although the popup auth and config additions are a nice touch.)
I haven't been putting my email/password into auth (haven't ever needed it for OF.) Just the authorization and the user agent.

**Comment by DIGITALCRIMINALS** [comment]
It seems you're getting an error, you can run "python start_ofd.py -v" in your terminal and we'll be able to see the error

**Comment by 3otgjrq** [comment]
sorry for taking forever to get back on this:
Auth (V1) Attempt 1/10
Welcome None | <redacted>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8F40>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8FD0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8E80>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8F70>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685C32E90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8E20>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8F10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8EB0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B685CE8FA0>
Traceback (most recent call last):
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\modules\fansly.py", line 1264, in manage_subscriptions
    results2 = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 310, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\<redacted>\Desktop\O\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 300, in multi
    valid_subscriptions.following
AttributeError: 'error_details' object has no attribute 'following'

**Comment by 3otgjrq** [comment]
Not sure if there's any more output in that with the -v command.

**Comment by DIGITALCRIMINALS** [comment]
Use latest commit

**Comment by 3otgjrq** [comment]
I'm using the newest commit (as of last night about 12 hours ago.) I am past the issue I was having before.

I have a similar problem now on both OF and Fansly: if I select all (0) or multiple such as 1,2,3 it returns back "There's no subscriptions to scrape." If I individually select one, it tends to work.

**Comment by 3otgjrq** [comment]
I just tried running the update.py for the first time, after seeing master having further changes. Updated an seems to be working with 0/all on OF.
