### ISSUE TITLE
ValueError: Unexpected character in found when decoding object value

### ISSUE THREAD

**Issue by gulch2k** [DIGITALCRIMINALS/OnlyFans#209]
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Traceback (most recent call last):
  File "C:\Users\finan\Documents\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\finan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\finan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\finan\Documents\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\finan\Documents\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\finan\Documents\OnlyFans-7.6.1\helpers\main_helper.py", line 937, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value

**Comment by gulch2k** [comment]
nvm I found what was wrong with it.
