### ISSUE TITLE
Updated to newer version and now it does not start.

### ISSUE THREAD

**Issue by Shingotink** [DIGITALCRIMINALS/OnlyFans#21]
Traceback (most recent call last):
  File "C:\Users\shing\Desktop\OnlyFans-master\start_ofd.py", line 16, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "C:\Users\shing\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 44
    match site_name_lower:
          ^
SyntaxError: invalid syntax

**Comment by DIGITALCRIMINALS** [comment]
Update to Python 3.10
