### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINALS/OnlyFans#211]
I have been having this error ever since I have downloaded the new 7.6.1 version. I have the 3.10 Python installed as well but cannot seem to pull any thing when I try to run the script. I just get the error message below. I looked at a similar error and tried to follow the instructions but they weren't detailed enough for me to figure out how to fix this issue. I have tried to look all over the net via google to fix this issue to no avail.  Can someone please help me figure out a way to resolve this problem. Thanks in advance. : 

Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome XXXXXXXX | uXXXXXXX
Traceback (most recent call last):
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TXXXX_\Documents\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\TXXXX_\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
**ValueError: too many file descriptors in select()**

**Comment by DIGITALCRIMINALS** [comment]
Use the latest commit

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/107

**Comment by Daironman78** [comment]
I have the latest version and this was still getting this message.
