### ISSUE TITLE
TypeError: create_auth.get_subscription()

### ISSUE THREAD

**Issue by d3ibis** [DIGITALCRIMINALS/OnlyFans#214]
I updated to latest, got this error:

![Screen Shot 2021-12-24 at 6 19 11 AM](https://user-images.githubusercontent.com/17270352/147315772-ce9cd42c-a45c-48c8-b5bc-52d622b58038.png)

Scraping Paid Content
Traceback (most recent call last):
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 79, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 64, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/d3ibis/Downloads/OnlyFans/datascraper/main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Users/d3ibis/Downloads/OnlyFans/modules/onlyfans.py", line 334, in paid_content_scraper
    subscription = await authed.get_subscription(
TypeError: create_auth.get_subscription() got an unexpected keyword argument 'check'

Any fix/solution ? <3

**Comment by avekifes** [comment]
Same issue here. Why is it that pretty much EVERY TIME I update the script, something breaks?

**Comment by DIGITALCRIMINALS** [comment]
Fixed

**Comment by d3ibis** [comment]
It is fixed, I can see my subscription, but when I want to scrap I got this:

100%|█████████████████████████████████████████████| 6/6 [00:00<00:00, 10.30it/s]
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 78, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 63, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/d3ibis/Downloads/OnlyFans/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/Users/d3ibis/Downloads/OnlyFans/helpers/main_helper.py", line 1018, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/Users/d3ibis/Downloads/OnlyFans/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/Users/d3ibis/Downloads/OnlyFans/modules/onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/Users/d3ibis/Downloads/OnlyFans/apis/onlyfans/classes/user_model.py", line 291, in get_posts
    results = await api_helper.scrape_endpoint_links(
  File "/Users/d3ibis/Downloads/OnlyFans/apis/api_helper.py", line 392, in scrape_endpoint_links
    case starsavn_classes.create_auth:
AttributeError: module 'apis.starsavn.classes' has no attribute 'create_auth'

**Comment by DIGITALCRIMINALS** [comment]
Fixed now
