### ISSUE TITLE
Failure to scrape with latest commit.

### ISSUE THREAD

**Issue by PsychoSid** [DIGITALCRIMINALS/OnlyFans#215]
Hello,

Just pulled from the latest and now failures are seen:-

```
Auth (V1) Attempt 1/10
Welcome <user> | <uid>
Scraping Paid Content
Traceback (most recent call last):
  File "/Users/me/Misc/OnlyFans/start_ofd.py", line 79, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/me/Misc/OnlyFans/start_ofd.py", line 64, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/me/Misc/OnlyFans/datascraper/main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Users/me/Misc/OnlyFans/modules/onlyfans.py", line 337, in paid_content_scraper
    subscription = paid_content.user
AttributeError: 'create_post' object has no attribute 'user'
```

Did I miss an update step ?

Cheers

**Comment by Toxotes** [comment]
Chime in that I get this error too

**Comment by qingshanfeihu** [comment]
I get another error like this:
Scrape Processing
Name: u9712828
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
100%|###############################################################################################################################################################| 5.03M/5.03M [00:03<00:00, 1.36MB/s]
Type: Stories
Error: {'code': 0, 'message': 'No access'}
Processing Scraped Stories
100%|#####################################################################################################################################################################| 1/1 [00:00<00:00, 218.21it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|#####################################################################################################################################################################| 1/1 [00:00<00:00, 505.58it/s]
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "/root/onlyfans/start_ofd.py", line 78, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/root/onlyfans/start_ofd.py", line 63, in main
    api = await main_datascraper.start_datascraper(
  File "/root/onlyfans/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/root/onlyfans/helpers/main_helper.py", line 1018, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/root/onlyfans/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/root/onlyfans/modules/onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/root/onlyfans/apis/onlyfans/classes/user_model.py", line 291, in get_posts
    results = await api_helper.scrape_endpoint_links(
  File "/root/onlyfans/apis/api_helper.py", line 392, in scrape_endpoint_links
    case starsavn_classes.create_auth:
AttributeError: module 'apis.starsavn.classes' has no attribute 'create_auth'

**Comment by rknightion** [comment]
I'm also getting the starsavn.classes error from the above, but I'm not using starsavn (only OF)

**Comment by PsychoSid** [comment]
I have reverted to commit `1fa838b` for now which is working just fine for me. Cheers.

**Comment by DIGITALCRIMINALS** [comment]
I'll let you all know when it's fixed

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed

**Comment by wcktklwn** [comment]
The latest update is working for me. Thanks @DIGITALCRIMINALS for your hard work!

**Comment by d3ibis** [comment]
ThanQ @DIGITALCRIMINALS , working great after latest update!
(Waiting for the process to finish for one account)

**Comment by Toxotes** [comment]
Verified fixed. Thanks!
