### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ttrv65ebyng** [DIGITALCRIMINALS/OnlyFans#23]
On filling in the credentials for both OnlyFans and Fansly, I tried scraping from both. Authentication and scraping works with OF, however when trying Fansly, auth seems to work, but I promptly get this after it says "Welcome None | {username}" (and please, excuse the mess that is my folder structure)

```
Traceback (most recent call last):
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/datascraper/main_datascraper.py", line 131, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/modules/fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/modules/fansly.py", line 1283, in manage_subscriptions
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
  File "/Volumes/Seagate 2TB/pn/gallerydl-21/FNSL/OnlyFans-7.4.5/modules/fansly.py", line 1283, in <lambda>
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
TypeError: 'NoneType' object is not subscriptable
```

**System Details:**
macOS 12.0 (21A5522h), Python 3.9.7 (arm64)

**Comment by DIGITALCRIMINALS** [comment]
Use the latest commit

**Comment by DIGITALCRIMINALS** [comment]
Now upgrade your Python to 3.10

**Comment by ttrv65ebyng** [comment]
Ok, for me, updating that seems to have worked. Thank you! For some reason I had to specify python@3.10 to brew as it would say 3.9.7 was up to date otherwise.

**Comment by DIGITALCRIMINALS** [comment]
> petitepixie69

Did you pay for any content?

**Comment by RonnieBlaze** [comment]
> 
> 
> > petitepixie69
> 
> Did you pay for any content?

I may have, I don't remember off hand.

**Comment by RonnieBlaze** [comment]
> 
> 
> Well it works for me

so strange... any ideas on something i can try?  im going to try brand new configs from scratch.
