### ISSUE TITLE
Tracebacks after selecting site

### ISSUE THREAD

**Issue by randomname912** [DIGITALCRIMINALS/OnlyFans#235]
I get the following message after first running "python start_ofd.py" and then selecting "0 = OnlyFans". Fansly and StarsAVN does not give the error, although I have nothing filled in the "auth" file for them. I have tried installing the scraper and python 3.10.1 again with no success at solving the problem. Both "config" and "auth" are filled as I have always filled them. Does anyone have a solution?

C:\Users\XXX\Downloads\OnlyFans Scraper - Chrome\OnlyFans-master>python start_ofd.py
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\OnlyFans Scraper - Chrome\OnlyFans-master\start_ofd.py", line 77, in <module>
    asyncio.run(main())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\XXX\Downloads\OnlyFans Scraper - Chrome\OnlyFans-master\start_ofd.py", line 62, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\XXX\Downloads\OnlyFans Scraper - Chrome\OnlyFans-master\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(
  File "C:\Users\XXX\Downloads\OnlyFans Scraper - Chrome\OnlyFans-master\helpers\main_helper.py", line 994, in process_profiles
    temp_json_auth = ujson.load(fp)
ValueError: Unrecognized escape sequence when decoding 'string'

**Comment by DeepSeaOne** [comment]
Are you on the latest commit? Can you run the script using -v(python -v start_ofd.py) and paste the results here?

**Comment by randomname912** [comment]
> Are you on the latest commit? Can you run the script using -v(python -v start_ofd.py) and paste the results here?

Never mind, I solved it. There must have been a symbol in the password that I have that caused the script to not work. When I leave that empty, everything works as per usual.
