### ISSUE TITLE
Memory Error on scraping expired subscription?

### ISSUE THREAD

**Issue by lucky1luc** [DIGITALCRIMINALS/OnlyFans#251]
I got following error on a model where my subscription expired. After this my PC basically crashed. Maybe there is a memory leak somewhere?

Missing 2362327 Posts... Retrying...
Scrape Attempt: 24/100
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Data\OnlyFans-7.5\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 56, in _cancel_all_tasks
    to_cancel = tasks.all_tasks(loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 53, in all_tasks
    tasks = list(_all_tasks)
MemoryError

**Comment by DIGITALCRIMINALS** [comment]
You ran out of ram. I keep forget that not everyone has 120GB so I'll have to optimise it.
