### ISSUE TITLE
ValueError: Unrecognized escape sequence when decoding 'string'

### ISSUE THREAD

**Issue by TheBurrito461** [DIGITALCRIMINALS/OnlyFans#255]
I receive this error when trying to run `start_ofd.py`: 

`Traceback (most recent call last):
  File "D:\Kali\OnlyFans\start_ofd.py", line 24, in <module>
    main_test.check_config()
  File "D:\Kali\OnlyFans\tests\main_test.py", line 26, in check_config
    json_config, updated = main_helper.get_config(path)
  File "D:\Kali\OnlyFans\helpers\main_helper.py", line 881, in get_config
    json_config = ujson.load(fp)
ValueError: Unrecognized escape sequence when decoding 'string'`

**Comment by DIGITALCRIMINALS** [comment]
You messed up your config. Delete it or fix it.
