### ISSUE TITLE
[commit 966] ValueError: invalid literal for int() with base 10: 'MODEL_NAME'

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/OnlyFans#259]
With the latest commit i received this error.
I have just changed the name of the model with MODEL_NAME.. is a normal name, no strange characters, all plain.

```
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 74, in <module>
    asyncio.run(main())
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 128, in start_datascraper
    await default(datascraper)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 86, in default
    subscription_options = OptionsFormat(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 854, in __init__
    self.formatter(options_type)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 888, in formatter
    final_list = self.choose_option()
  File "E:\OnlyFans-master\helpers\main_helper.py", line 904, in choose_option
    input_value = int(input())
ValueError: invalid literal for int() with base 10: 'MODEL_NAME'
```
update: if instead the name (of any model) I insert the number all works correctly.

thanks for support

**Comment by DIGITALCRIMINALS** [comment]
Fixed in latest commit
