### ISSUE TITLE
ImportError: cannot import name 'download_session'

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINALS/OnlyFans#266]
Hey, getting the following problem starting the scraper with Python 3.10.1 on Ubuntu 18.04.6 LTS.

```bash
$ ./start_ofd.py
Traceback (most recent call last):
  File "/home1/sideloading/local/OnlyFans/./start_ofd.py", line 23, in <module>
    main_test.check_config()
  File "/home1/sideloading/local/OnlyFans/tests/main_test.py", line 28, in check_config
    import helpers.main_helper as main_helper
  File "/home1/sideloading/local/OnlyFans/helpers/main_helper.py", line 36, in <module>
    from apis import api_helper
  File "/home1/sideloading/local/OnlyFans/apis/api_helper.py", line 37, in <module>
    from helpers.main_helper import download_session
ImportError: cannot import name 'download_session' from partially initialized module 'helpers.main_helper' (most likely due to a circular import) (/home1/sideloading/local/OnlyFans/helpers/main_helper.py)
```

I am using the latest commit ab6e735.

**Comment by DIGITALCRIMINALS** [comment]
I pushed another commit

**Comment by sideloading** [comment]
@DIGITALCRIMINALS Thanks for the quick fix, I am getting this attribute error now 😩

```bash
./start_ofd.py
Traceback (most recent call last):
  File "/home1/sideloading/local/OnlyFans/./start_ofd.py", line 24, in <module>
    main_test.check_profiles()
  File "/home1/sideloading/local/OnlyFans/tests/main_test.py", line 77, in check_profiles
    main_helper.export_json(new_item, auth_filepath)
  File "/home1/sideloading/local/OnlyFans/helpers/main_helper.py", line 811, in export_json
    if filepath.is_file():
AttributeError: 'str' object has no attribute 'is_file'
```

**Comment by sideloading** [comment]
@DIGITALCRIMINALS Solved.

Currently the script doesn't create the .settings and .profiles folder/files.

**Comment by DIGITALCRIMINALS** [comment]
Thanks, fixed in latest commit
