### ISSUE TITLE
Existence of `Thumbs.db` in metadata folder breaks script

### ISSUE THREAD

**Issue by E0911CD45B19686** [DIGITALCRIMINALS/OnlyFans#267]
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/.sites/OnlyFans/<redacted>/Posts/Free/Images/Thumbs.db' -> '/usr/src/app/.sites/OnlyFans/<redacted>/Metadata/Thumbs_0.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 74, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/datascraper/main_datascraper.py", line 95, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/usr/src/app/helpers/main_helper.py", line 1015, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "/usr/src/app/modules/onlyfans.py", line 185, in paid_content_scraper
    await main_helper.format_directories(
  File "/usr/src/app/helpers/main_helper.py", line 1348, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "/usr/local/lib/python3.10/shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/.sites/OnlyFans/<redacted>/Posts/Free/Images/Thumbs.db'
```

I did a file search and there was an errant `Thumbs.db` in a metadata folder. I removed it and the script ran fine again. Based on the file extension I'm pretty sure this is only a problem if it exists in the metadata folder, since I also found some in image folders for other models and didn't have any errors.

```bash
find OnlyFans -type f -name Thumbs.db
OnlyFans/<redacted_another_user>/Posts/Free/Images/Thumbs.db
OnlyFans/<redacted>/Metadata/Thumbs.db
```

**Comment by horatiorosa** [comment]
I have a similar issue with the Metafolder

I ran the script unsuccessfully a twice and what I noticed was happening was inception-like: 
original file structure before scrape attempt:  
      sites
       Onlyfans
         only_fans_provider 
           Metadata 
             user_data.db
New file structure after scrape attempt:
     sites
       Onlyfans
         only_fans_provider 
          Metadata
            user_data.db
            OnlyFans
              only_fans_provider
                Metadata
       


As my throwing spaghetti against the wall solution, the third time I ran the script, I deleted the `Metadata` folder but that did not fix anything. Logs are as follows:

           
```
Choose Profiles: 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome only_fans_user | only_fans_user
Scraping Paid Content
Scraping - <redacted> | 1 / 12
Scraping - <redacted> | 2 / 12
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 267.75it/s]
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 665.34it/s]
Scraping - <redacted>-am | 3 / 12
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 555.24it/s]
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 90.93it/s]
Scraping - <redacted> | 4 / 12
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1347.78it/s]
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1687.85it/s]
Scraping - <redacted> | 5 / 12
Scraping - <redacted> | 6 / 12
Scraping - <redacted> | 7 / 12
Scraping - <redacted> | 8 / 12
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 971.80it/s]
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 192.90it/s]
Scraping - <redacted> | 9 / 12
Scraping - <redacted> | 10 / 12
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1036.27it/s]
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 290.07it/s]
Scraping - <redacted> | 11 / 12
Scraping - <redacted> | 12 / 12
Scraping Subscriptions
Scrape Processing
Name: <redacted>
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 260/260 [00:00<00:00, 2008.91it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 260/260 [00:00<00:00, 986.83it/s]
Type: Archived
No Archived Found.
Type: Messages
No Messages Found.
Scrape Completed

# nothing downloaded, (except for possibly Metadata as indicated above) , ran script again.

Scrape Processing
Name: <redacted>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'sites/OnlyFans/<redacted>/Metadata/sites/OnlyFans/<redacted>/Metadata/user_data.db' -> 'sites/OnlyFans/<redacted>/Metadata/user_data_0.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/datascraper/main_datascraper.py", line 95, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/helpers/main_helper.py", line 1021, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)  # type: ignore
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/modules/onlyfans.py", line 113, in start_datascraper
    await main_helper.format_directories(
  File "/Users/<the_user_i_am>/LocalDesktop/OnlyFans/helpers/main_helper.py", line 1348, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'sites/OnlyFans/<redacted>/Metadata/sites/OnlyFans/<redacted>/Metadata/user_data.db'
```

I am running Mc 10.14.6, python 3 version is 3.10.1. I slightly changed my `config,json` as follows(TL;DR:  just updated the download folder from `.sites` to `sites`:

```
"onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": true,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          "sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          "sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
      ```
      



TYSM for any and all help / suggestions / prayers 😬   😬  😬

**Comment by DIGITALCRIMINALS** [comment]
Latest commit should fix the thumbs.db issue

**Comment by fl4shforward** [comment]
It seems like we have a regression on this bug.
I'm seeing the same issue on the latest commit.
