### ISSUE TITLE
Traceback error and "ValueError: could not convert string to float: '1,000.00'"

### ISSUE THREAD

**Issue by swagman382** [DIGITALCRIMINALS/OnlyFans#278]
I have the latest version of python as well
Type: Messages
Traceback (most recent call last):
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\datascraper\main_datascraper.py", line 95, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\helpers\main_helper.py", line 1050, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)  # type: ignore
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\modules\streamliner.py", line 74, in start_datascraper
    await self.prepare_scraper(subscription, key)
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\modules\streamliner.py", line 265, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\apis\starsavn\classes\user_model.py", line 410, in get_messages
    final_results = [
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\apis\starsavn\classes\user_model.py", line 411, in <listcomp>
    message_model.create_message(x, self) for x in final_results if x
  File "C:\Users\17133\Downloads\agane\OnlyFans-master\apis\starsavn\classes\message_model.py", line 18, in __init__
    self.price: Optional[float] = float(option.get("price", "0").replace("$", ""))
ValueError: could not convert string to float: '1,000.00'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216C3F62200>
Traceback (most recent call last):
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216C3F62200>
Traceback (most recent call last):
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216C3F62200>
Traceback (most recent call last):
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216C3F62200>
Traceback (most recent call last):
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by DIGITALCRIMINALS** [comment]
Fixed
