### ISSUE TITLE
missing 1 required positional argument: 'directory_manager'

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#279]
Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 95, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "D:\OnlyFans Scrapper\helpers\main_helper.py", line 1044, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "D:\OnlyFans Scrapper\modules\streamliner.py", line 229, in paid_content_scraper
    old_metadata, delete_metadatas = await process_legacy_metadata(
TypeError: process_legacy_metadata() missing 1 required positional argument: 'directory_manager'

**Comment by estif2127** [comment]
Having the same problem

**Comment by HistoricTheater** [comment]
Commit 26b1acb is presenting this error on linux as well

**Comment by twist3dimages** [comment]
Same here

**Comment by kb1ibt** [comment]
specifically missing the 4th argument "subscription_directory_manager" in https://github.com/DIGITALCRIMINALS/OnlyFans/blob/26b1acbb7772de19019912a43782feef0af26cf4/modules/streamliner.py#L229
it should be 
```                    
old_metadata, delete_metadatas = await process_legacy_metadata(
                        subscription,
                        api_type,
                        metadata_path,
                        subscription_directory_manager
                    )
