### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINALS/OnlyFans#28]
I get this with one user.

```
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "I:\OnlyFans-7.5\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "I:\OnlyFans-7.5\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "I:\OnlyFans-7.5\datascraper\main_datascraper.py", line 96, in start_datascraper
    await main_helper.process_names(
  File "I:\OnlyFans-7.5\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "I:\OnlyFans-7.5\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "I:\OnlyFans-7.5\modules\onlyfans.py", line 793, in prepare_scraper
    master_set += await subscription.get_archived_posts()
  File "I:\OnlyFans-7.5\apis\onlyfans\classes\create_user.py", line 430, in get_archived_posts
    final_results = [create_post(x, self) for x in results if x]
  File "I:\OnlyFans-7.5\apis\onlyfans\classes\create_user.py", line 430, in <listcomp>
    final_results = [create_post(x, self) for x in results if x]
  File "I:\OnlyFans-7.5\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
```

**Comment by DIGITALCRIMINALS** [comment]
Thanks, it's because you guys report content. I'll fix it.

**Comment by bobsage123** [comment]
> Thanks, it's because you guys report content. I'll fix it.

I did hit report once by accident on this channel. Weird it would cause an issue. Thanks for fixing

**Comment by DIGITALCRIMINALS** [comment]
I pushed the commit
