### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#283]
Traceback (most recent call last):
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.sites\\OnlyFans\\REDACTED\\Metadata\\.sites\\OnlyFans\\REDACTED\\Metadata\\user_data.db' -> '.sites\\OnlyFans\\REDACTED\\Metadata\\user_data_4.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 100, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "D:\OnlyFans Scrapper\helpers\main_helper.py", line 1020, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "D:\OnlyFans Scrapper\modules\streamliner.py", line 199, in paid_content_scraper
    await main_helper.format_directories(
  File "D:\OnlyFans Scrapper\helpers\main_helper.py", line 1354, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\Users\A\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.sites\\OnlyFans\\REDACTED\\Metadata\\.sites\\OnlyFans\\REDACTED\\Metadata\\user_data.db'

This is happening on latest commit.

**Comment by digitaljdr** [comment]
Getting the same sort of error on the latest commit. 

`Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Traceback (most recent call last):
  File "/Volumes/OF/start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Volumes/OF/start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "/Volumes/OF/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Volumes/OF/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Volumes/OF/helpers/main_helper.py", line 960, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'`

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/268

**Comment by DIGITALCRIMINALS** [comment]
> Getting the same sort of error on the latest commit.
> 
> `Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn 0 Traceback (most recent call last): File "/Volumes/OF/start_ofd.py", line 75, in <module> asyncio.run(main()) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete return future.result() File "/Volumes/OF/start_ofd.py", line 61, in main api = await main_datascraper.start_datascraper(config, site_name_lower) File "/Volumes/OF/datascraper/main_datascraper.py", line 131, in start_datascraper await default(datascraper) File "/Volumes/OF/datascraper/main_datascraper.py", line 55, in default await main_helper.process_profiles(api, global_settings) File "/Volumes/OF/helpers/main_helper.py", line 960, in process_profiles json_auth = temp_json_auth["auth"] KeyError: 'auth'`

Redo your auth
