### ISSUE TITLE
TypeError: create_user.create_directory_manager() got an unexpected keyword argument 'path_formats'

### ISSUE THREAD

**Issue by HistoricTheater** [DIGITALCRIMINALS/OnlyFans#288]
Commit 9910f3d
```
Traceback (most recent call last):
  File "/OnlyFans/start_ofd.py", line 64, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/OnlyFans/start_ofd.py", line 50, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/OnlyFans/datascraper/main_datascraper.py", line 128, in start_datascraper
    await default(datascraper)
  File "/OnlyFans/datascraper/main_datascraper.py", line 100, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/OnlyFans/helpers/main_helper.py", line 1034, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "/OnlyFans/modules/streamliner.py", line 186, in paid_content_scraper
    author.create_directory_manager(path_formats=path_formats)
TypeError: create_user.create_directory_manager() got an unexpected keyword argument 'path_formats'
```

**Comment by icemouton** [comment]
Getting the same issue on the latest commit 9910f3d

**Comment by DIGITALCRIMINALS** [comment]
Turn off paid content for now in config
