### ISSUE TITLE
TypeError: OnlyFansDataScraper.process_mass_messages() takes 2 positional arguments but 5 were given

### ISSUE THREAD

**Issue by prockerxoxo** [DIGITALCRIMINALS/OnlyFans#289]
I get this error and I think it's specifically my profile. I can scrap individually, but I can't do all.

Traceback (most recent call last):
  File "F:\OnlyFans Scraper\start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "C:\Users\brand\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\brand\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\OnlyFans Scraper\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "F:\OnlyFans Scraper\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "F:\OnlyFans Scraper\datascraper\main_datascraper.py", line 100, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "F:\OnlyFans Scraper\helpers\main_helper.py", line 1028, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)  # type: ignore
  File "F:\OnlyFans Scraper\modules\streamliner.py", line 76, in start_datascraper
    await self.prepare_scraper(subscription, key)
  File "F:\OnlyFans Scraper\modules\streamliner.py", line 238, in prepare_scraper
    unrefined_set2 = await self.datascraper.process_mass_messages(
TypeError: OnlyFansDataScraper.process_mass_messages() takes 2 positional arguments but 5 were given###

**Comment by DIGITALCRIMINALS** [comment]
Latest commit
