### ISSUE TITLE
Error using text

### ISSUE THREAD

**Issue by freakish804** [DIGITALCRIMINALS/OnlyFans#300]
Download Processing
Name: queensmita | Type: Posts | Count: 59 | Directory: F:\OnlyFans-7.6.1\.sites

  0%|                                                                              | 457k/1.88G [00:00<25:02, 1.25MB/s]Traceback (most recent call last):
  File "F:\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Obayd\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Obayd\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 103, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 975, in process_downloads
    await module.prepare_downloads(subscription)
  File "F:\OnlyFans-7.6.1\modules\onlyfans.py", line 1252, in prepare_downloads
    await main_helper.async_downloads(download_list, subscription)
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 255, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 250, in run
    await asyncio.gather(*tasks)
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 227, in process_download
    status_code = await write_data(
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 1030, in write_data
    with open_partial(download_path) as f:
  File "F:\OnlyFans-7.6.1\helpers\main_helper.py", line 1017, in open_partial
    return open(partial_path, "xb")
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\OnlyFans-7.6.1\\.sites\\OnlyFans\\queensmita\\Posts\\Free\\Videos\\2022-01-04-Sample JOI Content Mamanar marumagal leelaigala when the husband is sent away for work. Hungry mamanar wants a taste of her pussy, cum in her pussy a-0gy1q69cp61llv38lmriz_source-bd95940ef5ff.mp4.part'

  0%|                                                                              | 493k/1.88G [00:13<25:02, 1.25MB/s]

Shows this error to every model when i try to download if  there is text in "filename_format": "{date}-{text}-{filename}.{ext}" .
If i remove the text then it works fine. I used to download this way previously and its a very useful feature atleast for me. Is there any way to fix this issue and download posts with text ?

**Comment by Gamma-Velorum** [comment]
```python
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.sites\\OnlyFans\\alexelena\\Metadata\\.sites\\OnlyFans\\alexelena\\Metadata\\user_data.db' -> '.sites\\OnlyFans\\alexelena\\Metadata\\user_data_1.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 64, in <module>
    asyncio.run(main())
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "O:\OnlyFans-master\start_ofd.py", line 50, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "O:\OnlyFans-master\helpers\main_helper.py", line 1035, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "O:\OnlyFans-master\modules\streamliner.py", line 202, in paid_content_scraper
    await main_helper.format_directories(
  File "O:\OnlyFans-master\helpers\main_helper.py", line 1376, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.sites\\OnlyFans\\alexelena\\Metadata\\.sites\\OnlyFans\\alexelena\\Metadata\\user_data.db'
```

Using Python 3.10.2 & requirements updated.

**Comment by DIGITALCRIMINALS** [comment]
> ```python
> Traceback (most recent call last):
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
>     os.rename(src, real_dst)
> FileNotFoundError: [WinError 2] The system cannot find the file specified: '.sites\\OnlyFans\\alexelena\\Metadata\\.sites\\OnlyFans\\alexelena\\Metadata\\user_data.db' -> '.sites\\OnlyFans\\alexelena\\Metadata\\user_data_1.db'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "O:\OnlyFans-master\start_ofd.py", line 64, in <module>
>     asyncio.run(main())
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
>     return future.result()
>   File "O:\OnlyFans-master\start_ofd.py", line 50, in main
>     api = await main_datascraper.start_datascraper(config, site_name)
>   File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
>     await default(datascraper)
>   File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
>     await main_helper.process_jobs(datascraper, subscription_list, site_settings)
>   File "O:\OnlyFans-master\helpers\main_helper.py", line 1035, in process_jobs
>     await datascraper.paid_content_scraper(authed)  # type: ignore
>   File "O:\OnlyFans-master\modules\streamliner.py", line 202, in paid_content_scraper
>     await main_helper.format_directories(
>   File "O:\OnlyFans-master\helpers\main_helper.py", line 1376, in format_directories
>     shutil.move(metadata_filepath, new_m_f)
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
>     copy_function(src, real_dst)
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
>     with open(src, 'rb') as fsrc:
> FileNotFoundError: [Errno 2] No such file or directory: '.sites\\OnlyFans\\alexelena\\Metadata\\.sites\\OnlyFans\\alexelena\\Metadata\\user_data.db'
> ```
> 
> Using Python 3.10.2 & requirements updated.

Not the same issue.

It's this

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/268

**Comment by sxdent21** [comment]
I think I'm having a similar issue.
Windows 10 
Python 3.10
using the commit 5d7050b
``` python
Traceback (most recent call last):
  File "C:\Users\xhald\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\Creators\\Models\\PeachJars\\OnlyFans\\Metadata\\Posts.db' -> 'E:\\Creators\\Models\\PeachJars\\Fansly\\Metadata\\Posts.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Utilities\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\xhald\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\Utilities\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "E:\Utilities\OnlyFans\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "E:\Utilities\OnlyFans\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "E:\Utilities\OnlyFans\helpers\main_helper.py", line 1038, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "E:\Utilities\OnlyFans\modules\streamliner.py", line 202, in paid_content_scraper
    await main_helper.format_directories(
  File "E:\Utilities\OnlyFans\helpers\main_helper.py", line 1379, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "C:\Users\xhald\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "C:\Users\xhald\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\xhald\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Creators\\Models\\PeachJars\\Fansly\\Metadata\\Posts.db'
```

**Comment by neuri4848** [comment]
it happened to me when a model started using "\" or "\\" in the message

**Comment by DIGITALCRIMINALS** [comment]
Does this still happen?

**Comment by freakish804** [comment]
@DIGITALCRIMINALS , checked with latest commit. yes, its still happening.


Download Processing
Name: urfavunicorn69 | Type: Posts | Count: 41 | Directory: E:\OnlyFans-7.6.1\.sites

  0%|                                                                             | 11.9k/34.1M [00:01<55:41, 10.2kB/s]Traceback (most recent call last):
  File "E:\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Obayd\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Obayd\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 103, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 975, in process_downloads
    await module.prepare_downloads(subscription)
  File "E:\OnlyFans-7.6.1\modules\onlyfans.py", line 1252, in prepare_downloads
    await main_helper.async_downloads(download_list, subscription)
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 255, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 250, in run
    await asyncio.gather(*tasks)
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 227, in process_download
    status_code = await write_data(
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 1030, in write_data
    with open_partial(download_path) as f:
  File "E:\OnlyFans-7.6.1\helpers\main_helper.py", line 1017, in open_partial
    return open(partial_path, "xb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\OnlyFans-7.6.1\\.sites\\OnlyFans\\urfavunicorn69\\Posts\\Free\\Images\\2022-01-11-Nasty girls do dirty things… tell me your favorite position. Here’s my reverse cowgirl 🤠 🥵 with
 the right cock, this can -3024x4032_7fd736c44c29e99a5335f41f0a87fc35-6a265283c798.jpg.part'

  0%|                                                                             | 24.2k/34.1M [00:15<55:40, 10.2kB/s]






config,

{
  "info": {
    "version": 7.2
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "4486d4f177af11ec975ef07bcb5e1714"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}-{text}-{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 210,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true

**Comment by spiderzero3** [comment]
still happening on latest commit. post has a caption containing ":\" and the script tries creating a directory because of it. hacked around it by adding 
```
if final_text is not None:
    final_text = final_text.replace("/", "").replace("\\", "")
```
to onlyfans.py and fansly.py after the line `final_text = rawText if rawText else text`

**Comment by PJD94** [comment]
> still happening on latest commit. post has a caption containing ":\" and the script tries creating a directory because of it. hacked around it by adding
> 
> ```
> if final_text is not None:
>     final_text = final_text.replace("/", "").replace("\\", "")
> ```
> 
> to onlyfans.py and fansly.py after the line `final_text = rawText if rawText else text`

Unfortunately that hasn't worked in my case, using the latest commit.

The post in question doesn't seem to have any symbols in the text other than a daft emoji, which has successfully downloaded in the past.

There's a few modules/code snippets around that claim to replace emoji with their text code equivalent but im nowhere near skilled enough with python to integrate it.

**Comment by freakish804** [comment]
Problem Solved with latest commit. Thank you bro @DIGITALCRIMINALS ❤
