### ISSUE TITLE
sqlite3.OperationalError: no such table: medias

### ISSUE THREAD

**Issue by herefromrdt** [DIGITALCRIMINALS/OnlyFans#304]
I get the following error on every run

```

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: medias

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\OnlyFans\start_ofd.py", line 75, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "G:\OnlyFans\start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(config, site_name_lower)
  File "G:\OnlyFans\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "G:\OnlyFans\datascraper\main_datascraper.py", line 96, in default
    await main_helper.process_downloads(api, datascraper, global_settings)
  File "G:\OnlyFans\helpers\main_helper.py", line 1039, in process_downloads
    await datascraper.prepare_downloads(subscription)
  File "G:\OnlyFans\modules\onlyfans.py", line 266, in prepare_downloads
    media_set_count = db_helper.get_count(download_list)
  File "G:\OnlyFans\helpers\db_helper.py", line 117, in get_count
    count = q.session.execute(count_q).scalar()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: medias
[SQL: SELECT count(*) AS count_1
FROM medias
WHERE medias.downloaded = 0 AND medias.api_type = ?]
[parameters: ('Stories',)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)```

**Comment by herefromrdt** [comment]
Closing this, because I updated Python and pulled the latest commit, and the problem went away.
