### ISSUE TITLE
Fansly scraper error

### ISSUE THREAD

**Issue by dave2197** [DIGITALCRIMINALS/OnlyFans#31]
Onlyfans scraper working great, but I get this error when trying Fansly:

```
Traceback (most recent call last):
  File "C:\OnlyFans-7.5\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\OnlyFans-7.5\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\OnlyFans-7.5\datascraper\main_datascraper.py", line 159, in start_datascraper
    await main_helper.process_names(
  File "C:\OnlyFans-7.5\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\OnlyFans-7.5\modules\fansly.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\OnlyFans-7.5\modules\fansly.py", line 842, in prepare_scraper
    await process_metadata(
  File "C:\OnlyFans-7.5\modules\fansly.py", line 678, in process_metadata
    new_metadata_object = await ofrenamer.start(
  File "C:\OnlyFans-7.5\extras\OFRenamer\start_ofr.py", line 198, in start
    await fix_directories(
  File "C:\OnlyFans-7.5\extras\OFRenamer\start_ofr.py", line 141, in fix_directories
    delete_rows = await tqdm.gather(*tasks, **settings)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\OnlyFans-7.5\extras\OFRenamer\start_ofr.py", line 95, in fix_directories2
    os.remove(new_filepath)
PermissionError: [WinError 5] Access denied: 'C:\\OnlyFans-7.5\\.sites\\Fansly\\*****\\Posts\\Free\\Images'
```

**Comment by OFfriend** [comment]
Check your permissions on that drive. You can try to run the Script as Administrator.
