### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by swagman382** [DIGITALCRIMINALS/OnlyFans#310]
I have python 3.10.2 currently and am getting this error when using the avnstars scraper

Scraping Paid Content
Traceback (most recent call last):
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\helpers\main_helper.py", line 1038, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\modules\streamliner.py", line 187, in paid_content_scraper
    author.create_directory_manager()
  File "C:\Users\17133\Downloads\ffs\OnlyFans-master\apis\starsavn\classes\user_model.py", line 599, in create_directory_manager
    profile_directory = base_directory_manager.profile.root_directory.joinpath(
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 849, in joinpath
    return self._make_child(args)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 614, in _make_child
    drv, root, parts = self._parse_args(args)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E891A520E0>
Traceback (most recent call last):
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by DIGITALCRIMINALS** [comment]
Ignore this.

**Comment by swagman382** [comment]
Hey, I know you closed this issue, but I am still getting this error and
was wondering if you know anything about this? Is there some mistake I'm
making?

Scraping Paid Content
Traceback (most recent call last):
  File "C:\Users\17133\Downloads\main\OnlyFans-master\start_ofd.py", line
66, in <module>
    asyncio.run(main())
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py",
line 44, in run
    return loop.run_until_complete(main)
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py",
line 641, in run_until_complete
    return future.result()
  File "C:\Users\17133\Downloads\main\OnlyFans-master\start_ofd.py", line
52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File
"C:\Users\17133\Downloads\main\OnlyFans-master\datascraper\main_datascraper.py",
line 129, in start_datascraper
    await default(datascraper)
  File
"C:\Users\17133\Downloads\main\OnlyFans-master\datascraper\main_datascraper.py",
line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list,
site_settings)
  File
"C:\Users\17133\Downloads\main\OnlyFans-master\helpers\main_helper.py",
line 1038, in process_jobs
    await datascraper.paid_content_scraper(authed)  # type: ignore
  File
"C:\Users\17133\Downloads\main\OnlyFans-master\modules\module_streamliner.py",
line 187, in paid_content_scraper
    author.create_directory_manager()
  File
"C:\Users\17133\Downloads\main\OnlyFans-master\apis\starsavn\classes\user_model.py",
line 599, in create_directory_manager
    profile_directory =
base_directory_manager.profile.root_directory.joinpath(
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py",
line 849, in joinpath
    return self._make_child(args)
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py",
line 614, in _make_child
    drv, root, parts = self._parse_args(args)
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\pathlib.py",
line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PyThreadState_Clear: warning: thread still has a frame
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at
0x00000154B2EA6200>
Traceback (most recent call last):
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py",
line 116, in __del__
    self.close()
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py",
line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py",
line 745, in call_soon
    self._check_closed()
  File
"C:\Users\17133\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py",
line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
