### ISSUE TITLE
Permission denied in fix_directories2

### ISSUE THREAD

**Issue by icemouton** [DIGITALCRIMINALS/OnlyFans#313]
**Source :** Linux Ubuntu Latest Commit.

I've noticed in the past couple of days I'm getting a lot of permission denied errors while scraping from fix_directories2
```
Traceback (most recent call last):
  File "/src/OnlyFans/extras/OFRenamer/start_ofr.py", line 111, in fix_directories2
    if old_filepath.exists():
  File "/usr/lib/python3.10/pathlib.py", line 1278, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1085, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/OnlyFans/model/Posts/Free/Images/3024x4032_6b55ddc7be005b36cf0782c9ef44803c.jpg'
```
If I check on the drive the folder has regular permissions and the file is there with the right permissions as well.

It's not always the same model but I've only seen it happen with models that have thousands of media files +

I tried different commits from the "nuked directory fix" and up but they all give me the same results.

Any clue ?

**Comment by icemouton** [comment]
Hum I did some manipulations on the folders and it seems to work now I'll blame some filesystem stale pointers or something.
