### ISSUE TITLE
i dont even know what this error means...

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINALS/OnlyFans#319]
```B:\Github\OnlyFans>python start_ofd.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "B:\Github\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "B:\Github\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "B:\Github\OnlyFans\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "B:\Github\OnlyFans\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 975, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 774, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: control character (\u0000-\u001F) found while parsing a string at line 5 column 0: line 5 column 1 (char 201)
```

**Comment by scarteo** [comment]
i get almost the same trying to rip fansly
Traceback (most recent call last):
  File "/home/****/onlyfans/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/****/onlyfans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/home/***/onlyfans/datascraper/main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "/home/****/onlyfans/datascraper/main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "/home/***/onlyfans/helpers/main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "/home/***/onlyfans/modules/module_streamliner.py", line 367, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "/home/***/onlyfans/modules/fansly.py", line 393, in get_all_subscriptions
    results = await authed.get_followings(identifiers=identifiers)
  File "/home/***/onlyfans/apis/fansly/classes/auth_model.py", line 271, in get_followings
    final_followings = [
  File "/home/***/onlyfans/apis/fansly/classes/auth_model.py", line 272, in <listcomp>
    create_user(x, self) for x in temp_followings["response"]
  File "/home/***/onlyfans/apis/fansly/classes/user_model.py", line 244, in __init__
    self.header = media_options[0]["location"]
IndexError: list index out of range

**Comment by DIGITALCRIMINALS** [comment]
@Luke-L you messed up one of your json files
