### ISSUE TITLE
temp_json_auth["auth"] - OF

### ISSUE THREAD

**Issue by d3ibis** [DIGITALCRIMINALS/OnlyFans#324]
Downloaded latest code, entered all details in auth, started it & got this:

Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/d3ibis/Downloads/OnlyFans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/d3ibis/Downloads/OnlyFans/datascraper/main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "/Users/d3ibis/Downloads/OnlyFans/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Users/d3ibis/Downloads/OnlyFans/helpers/main_helper.py", line 976, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'

any ideas ? ThanQ <3

**Comment by dunkethee** [comment]
Are you on Mac OS? It looks like the issue involves including .DS_Store in a list of folders when it shouldn't be. 

Fix: 

In helpers/main_helper.py, find the function remove_mandatory_files (starts at line 1181 in current version). In that function, change the line (1183) from:

`folders = [x for x in files if x not in matches]`

to:

`folders = [x for x in files if x.name not in matches]`

**Comment by d3ibis** [comment]
Worked, ThanQ!

**Comment by Nick05491** [comment]
@DIGITALCRIMINALS can we implement this fix for all users?

**Comment by misterscraper** [comment]
> Are you on Mac OS? It looks like the issue involves including .DS_Store in a list of folders when it shouldn't be.
> 
> Fix:
> 
> In helpers/main_helper.py, find the function remove_mandatory_files (starts at line 1181 in current version). In that function, change the line (1183) from:
> 
> `folders = [x for x in files if x not in matches]`
> 
> to:
> 
> `folders = [x for x in files if x.name not in matches]`

this fixed my issue!
