### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by prockerxoxo** [DIGITALCRIMINALS/OnlyFans#332]
I keep getting this error after I updated commits

```
Traceback (most recent call last):
  File "F:\OnlyFans Scraper\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\brand\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\brand\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\OnlyFans Scraper\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "F:\OnlyFans Scraper\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "F:\OnlyFans Scraper\datascraper\main_datascraper.py", line 67, in default
    if not subscription_options.scrape_all():
  File "F:\OnlyFans Scraper\helpers\main_helper.py", line 951, in scrape_all
    and isinstance(self.auto_choice[0], str)
IndexError: list index out of range
```

**Comment by prockerxoxo** [comment]
Fixed issue

**Comment by lamepennies** [comment]
How did you fix this issue?
