### ISSUE TITLE
This weird thing

### ISSUE THREAD

**Issue by AyaanMAG** [DIGITALCRIMINALS/OnlyFans#341]
`Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "D:\Folder\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Folder\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\Folder\OnlyFans\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "D:\Folder\OnlyFans\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "D:\Folder\OnlyFans\helpers\main_helper.py", line 975, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "D:\Folder\OnlyFans\helpers\main_helper.py", line 774, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: EOF while parsing an object at line 13 column 2: line 13 column 3 (char 440)`

**Comment by E0911CD45B19686** [comment]
> orjson.JSONDecodeError: EOF while parsing an object at line 13 column 2: line 13 column 3 (char 440)

You messed up the formatting of your `.profiles/default/auth.json`. Look at line 12 or 13, you probably have an extra `,` that shouldn't be there.
