### ISSUE TITLE
No module named 'classes.make_settings'

### ISSUE THREAD

**Issue by browntown-13** [DIGITALCRIMINALS/OnlyFans#355]
No idea what to do here.

Traceback (most recent call last):
  File "/Users/xxx/Downloads/OnlyFans-master/start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "/Users/xxx/Downloads/OnlyFans-master/helpers/main_helper.py", line 21, in <module>
    import classes.make_settings as make_settings
ModuleNotFoundError: No module named 'classes.make_settings'

**Comment by DIGITALCRIMINALS** [comment]
How are you running the script? Double clicking or running via cmd?

**Comment by browntown-13** [comment]
Hey, sorry, meant to get back here sooner but life got in the way. I've tried both methods with the same result either way.
