### ISSUE TITLE
Problem after updating the script

### ISSUE THREAD

**Issue by Muruxror** [DIGITALCRIMINALS/OnlyFans#361]
Hey Guys,

I tried updating the script...
After I installed Poetry and run poetry install, it gave me the error: module orjson is missing. After that, I installed it with Poetry manually. Now I'm getting this error, I don't know what to do now. 
Any ideas?
That's the cmd log:

X:\Onlyfans\OnlyFans-master NEW test>start_ofd.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "X:\Onlyfans\OnlyFans-master NEW test\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Murux\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Murux\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "X:\Onlyfans\OnlyFans-master NEW test\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "X:\Onlyfans\OnlyFans-master NEW test\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "X:\Onlyfans\OnlyFans-master NEW test\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "X:\Onlyfans\OnlyFans-master NEW test\helpers\main_helper.py", line 975, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "X:\Onlyfans\OnlyFans-master NEW test\helpers\main_helper.py", line 774, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: control character (\u0000-\u001F) found while parsing a string at line 7 column 0: line 7 column 1 (char 351)

thx in advance :)

**Comment by DIGITALCRIMINALS** [comment]
Your auth.json is messed up. It has invalid characters in them.

**Comment by Muruxror** [comment]
Thanks, I messed up while copy and paste my information,
but now the next: Access denied.
I deleted .sides, .settings, .profiles and let the script create new ones. Then I filled in my data from of, but no change.
Also checked poetry updates.
Another idea?
I am willing to send you my data, if you would try it.

**Comment by DIGITALCRIMINALS** [comment]
You can send me the auth.json you're trying to fill in. My email is on my main account @DIGITALCRIMINAL

**Comment by Muruxror** [comment]
Everything works again thx.
