### ISSUE TITLE
Error when downloading from Fansly

### ISSUE THREAD

**Issue by ShadyRelapse-PP** [DIGITALCRIMINALS/OnlyFans#368]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022A39640610>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022A3939B4C0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022A3939BD00>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022A39533400>
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "E:\OnlyFans-master\modules\module_streamliner.py", line 367, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "E:\OnlyFans-master\modules\fansly.py", line 394, in get_all_subscriptions
    results2 = await authed.get_subscriptions(
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 335, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 318, in multi
    subscription = await self.get_user(item["accountId"])
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 219, in get_user
    response = create_user(response["response"][0], self)
  File "E:\OnlyFans-master\apis\fansly\classes\user_model.py", line 244, in __init__
    self.header = media_options[0]["location"]
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022A36E0E9E0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022A36E0E9E0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by ShadyRelapse-PP** [comment]
this is using the latest commit and also i have a creator account

**Comment by DIGITALCRIMINALS** [comment]
Which model does it fail on?

**Comment by ShadyRelapse-PP** [comment]
> Which model does it fail on?

doesn't fail on any it fails after I choose my profile.

**Comment by ShadyRelapse-PP** [comment]
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
2
Choose Profiles: 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome USERNAME REMOVED
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B19BD2A10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B19AD5B40>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B19AD4970>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B19A8C760>
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "E:\OnlyFans-master\modules\module_streamliner.py", line 367, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "E:\OnlyFans-master\modules\fansly.py", line 394, in get_all_subscriptions
    results2 = await authed.get_subscriptions(
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 335, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 318, in multi
    subscription = await self.get_user(item["accountId"])
  File "E:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 219, in get_user
    response = create_user(response["response"][0], self)
  File "E:\OnlyFans-master\apis\fansly\classes\user_model.py", line 244, in __init__
    self.header = media_options[0]["location"]
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B1747EA70>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B1747EA70>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B1747EA70>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by DIGITALCRIMINALS** [comment]
Ahh, so you've got no cover photo on your account right?

**Comment by ShadyRelapse-PP** [comment]
I have both a header and pfp on my account

**Comment by DIGITALCRIMINALS** [comment]
Fixed

https://github.com/DIGITALCRIMINALS/UltimaScraperAPI/commit/7d8b330f8454aa96b6707c3d8605b59967873456
