### ISSUE TITLE
Error - Traceback (most recent call last)

### ISSUE THREAD

**Issue by Nido21100** [DIGITALCRIMINALS/OnlyFans#38]
I got this error today, any idea how to fix it?

Traceback (most recent call last):
  File "T:\OF\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "T:\OF\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "T:\OF\datascraper\main_datascraper.py", line 96, in start_datascraper
    await main_helper.process_names(
  File "T:\OF\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "T:\OF\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "T:\OF\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "T:\OF\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "T:\OF\helpers\main_helper.py", line 583, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

**Comment by Nido21100** [comment]
> Which model?

It was model keighlanight1 but I deleted the metadata folder in her directory and it worked fine after that.

**Comment by Nido21100** [comment]
what i did must have been a flucke coz i got it with model danijensen

Traceback (most recent call last):
  File "T:\OF\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "T:\OF\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "T:\OF\datascraper\main_datascraper.py", line 96, in start_datascraper
    await main_helper.process_names(
  File "T:\OF\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "T:\OF\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "T:\OF\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "T:\OF\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "T:\OF\helpers\main_helper.py", line 583, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

**Comment by DIGITALCRIMINALS** [comment]
Been fixed in latest commit
