### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by spike63995** [DIGITALCRIMINALS/OnlyFans#398]
Hi, I used to have no issues with this, but using 7.6.1 now for some reason is giving me this error when I try to run the script.

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\helpers\main_helper.py", line 836
    match options_type:
          ^
SyntaxError: invalid syntax

**Comment by shawn8888** [comment]
Same here. 
`python --version
Python 3.9.4`

**Comment by shawn8888** [comment]
upgrade to python 3.10.4 solved the problem.
