### ISSUE TITLE
Error while trying to scrap on Fansly

### ISSUE THREAD

**Issue by NyctophobiaZ** [DIGITALCRIMINALS/OnlyFans#401]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FE89FAF0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C2E0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C280>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C370>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FE89FBB0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C220>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C310>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C2B0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C3A0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000284FEB3C250>
Traceback (most recent call last):
  File "D:\Garbage\ \OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Alvaro\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Alvaro\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Garbage\ \OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Garbage\ \OnlyFans-7.6.1\datascraper\main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\Garbage\ \OnlyFans-7.6.1\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "D:\Garbage\ \OnlyFans-7.6.1\modules\fansly.py", line 1264, in manage_subscriptions
    results2 = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "D:\Garbage\ \OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 310, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "D:\Garbage\ \OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 300, in multi
    valid_subscriptions.following
AttributeError: 'error_details' object has no attribute 'following'

**Comment by ppsoong** [comment]
I also cannot run the Fansly scraper. When I select Fansly and my log in this is the error I get:

```
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
2
Choose Profiles: 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome <USER_NAME>
Traceback (most recent call last):
  File "Z:\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "Z:\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "Z:\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "Z:\OnlyFans-master\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "Z:\OnlyFans-master\helpers\main_helper.py", line 1012, in account_setup
    await datascraper.manage_subscriptions(
  File "Z:\OnlyFans-master\modules\module_streamliner.py", line 369, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "Z:\OnlyFans-master\modules\fansly.py", line 393, in get_all_subscriptions
    results = await authed.get_followings(identifiers=identifiers)
  File "Z:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 271, in get_followings
    final_followings = [
  File "Z:\OnlyFans-master\apis\fansly\classes\auth_model.py", line 272, in <listcomp>
    create_user(x, self) for x in temp_followings["response"]
  File "Z:\OnlyFans-master\apis\fansly\classes\user_model.py", line 244, in __init__
    self.header = media_options[0]["location"]
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000147DE2F2D40>
Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
