### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by PatrickMelanson** [DIGITALCRIMINALS/OnlyFans#409]
When I go to actually run `start_ofd.py` I get that the 10 attempts all fail, then it says `Accessed denied` with the following error:
 
`Traceback (most recent call last):
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\pat68\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\pat68\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 117, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "C:\Users\pat68\Downloads\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\pat68\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\pat68\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\firefox\webdriver.py", line 176, in __init__
    self.service.start()
  File "C:\Users\pat68\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\pat68\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\pat68\Downloads\OnlyFans-7.6.1\extras\OFLogin\geckodriver.exe unexpectedly exited. Status code was: 64`

I have pasted geckodriver into the `OFLogin` folder, but at this point, I'm at a loss. Thanks!

**Comment by PatrickMelanson** [comment]
Update: I still haven't found a solution, but after some snooping around I have a new error: 

`PS C:\Users\pat68\Downloads\OnlyFans-master> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\pat68\Downloads\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "C:\Users\pat68\Downloads\OnlyFans-master\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'`

I'm not sure if this will help, but before I was just in a loop of "access denied"

**Comment by ctrlcmdshft** [comment]
You are missing "orjson" module run the command to install the requirements again.

**Comment by PatrickMelanson** [comment]
Okay y'all, so I seem to have fixed the problem (at least in my specific case). I downloaded `orjson`, but more importantly (I think) I was able to get the auth file to work. I did two things that seemed to work (though YMMV): 
- First I opened OF in my browser, inspected the elements, reset it, all that, AND THEN copied the `sess` information. I then KEPT THE PAGE OPEN (not sure if that was important, I don't know but it worked). 
- Secondly (and what I suspect actually made it work) is that I filled out the email and password fields (with the relevant information). Hopefully this helps, I'm going to set this to "solved" now. 

Oh, and another thing for anyone reading in the future: did you have to download it in two batches? I got about halfway through one creator, it stopped, prompted me again, and then continued. As far as I can tell it got all of it, so I don't know if it was a glitch or what.
