### ISSUE TITLE
Running on linux - ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by xxtensazenxx** [DIGITALCRIMINALS/OnlyFans#42]
For the life of me I cannot get this script to function anymore. 

(scraper) matt@oldshack:~/onlyfans$ python3.10 start_ofd.py
Traceback (most recent call last):
  File "/home/matt/onlyfans/start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "/home/matt/onlyfans/tests/main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "/home/matt/onlyfans/helpers/main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "/home/matt/onlyfans/database/databases/user_data/models/api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

I follow all instructions but get stuck here now.

**Comment by OFfriend** [comment]
are you using `ppa:deadsnakes/ppa` for python 3.10? Don't use it. I had the same Problem. Build Python 3.10 from Source and use pip3.10 for installing the dependencies.

**Comment by xxtensazenxx** [comment]
matt@oldshack:~/onlyfans$ pip3.10 install --upgrade --user -r requirements.txt
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting urllib3
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting win32-setctime
  Using cached win32_setctime-1.0.3-py3-none-any.whl (3.5 kB)
Collecting python-socks[asyncio]
  Using cached python_socks-1.2.4-py3-none-any.whl (35 kB)
Collecting psutil
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_1d134024312441ad9ee20ce58e8663d1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_1d134024312441ad9ee20ce58e8663d1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w9qoqqq2
       cwd: /tmp/pip-install-ncko51il/psutil_1d134024312441ad9ee20ce58e8663d1/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz#sha256=0c9ccb99ab76025f2f0bbecf341d4656e9c1351db8cc8a03ccd62e318ab4b5c6 (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.7.3.tar.gz (465 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_b84263700cc54f1d8861ee776cab7cc1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_b84263700cc54f1d8861ee776cab7cc1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ztlvrrv8
       cwd: /tmp/pip-install-ncko51il/psutil_b84263700cc54f1d8861ee776cab7cc1/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz#sha256=af73f7bcebdc538eda9cc81d19db1db7bf26f103f91081d780bbacfcb620dee2 (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.7.2.tar.gz (460 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_2067dc7c9c114009983a5ae5f1931642/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_2067dc7c9c114009983a5ae5f1931642/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z31td6eb
       cwd: /tmp/pip-install-ncko51il/psutil_2067dc7c9c114009983a5ae5f1931642/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz#sha256=90990af1c3c67195c44c9a889184f84f5b2320dce3ee3acbd054e3ba0b4a7beb (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.7.1.tar.gz (460 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_4d16dc5362b84b96a186dd7012581664/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_4d16dc5362b84b96a186dd7012581664/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zjcnr8iq
       cwd: /tmp/pip-install-ncko51il/psutil_4d16dc5362b84b96a186dd7012581664/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2c/5c/cb95a715fb635e1ca858ffb8c50a523a16e2dc06aa3e207ab73cb93516af/psutil-5.7.1.tar.gz#sha256=4ef6845b35e152e6937d4f28388c2440ca89a0089ced0a30a116fa3ceefdfa3a (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.7.0.tar.gz (449 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_543b073be67d40ce8e00d03d97d8bba4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_543b073be67d40ce8e00d03d97d8bba4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3jtk93md
       cwd: /tmp/pip-install-ncko51il/psutil_543b073be67d40ce8e00d03d97d8bba4/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz#sha256=685ec16ca14d079455892f25bd124df26ff9137664af445563c1bd36629b5e0e (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.6.7.tar.gz (448 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_f5ff15e106364cd4879d262bd0187291/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_f5ff15e106364cd4879d262bd0187291/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4vcrsdnj
       cwd: /tmp/pip-install-ncko51il/psutil_f5ff15e106364cd4879d262bd0187291/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/73/93/4f8213fbe66fc20cb904f35e6e04e20b47b85bee39845cc66a0bcf5ccdcb/psutil-5.6.7.tar.gz#sha256=ffad8eb2ac614518bbe3c0b8eb9dffdb3a8d2e3a7d5da51c5b974fb723a5c5aa (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.6.6.tar.gz (447 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_5df6b1e0d5764013848712ce3938a4be/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_5df6b1e0d5764013848712ce3938a4be/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c3pc7wax
       cwd: /tmp/pip-install-ncko51il/psutil_5df6b1e0d5764013848712ce3938a4be/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5f/dc/edf6758183afc7591a16bd4b8a44d8eea80aca1327ea60161dd3bad9ad22/psutil-5.6.6.tar.gz#sha256=ad21281f7bd6c57578dd53913d2d44218e9e29fd25128d10ff7819ef16fa46e7 (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.6.5.tar.gz (447 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncko51il/psutil_c713283c0c1d4b5596370289ec9b6007/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncko51il/psutil_c713283c0c1d4b5596370289ec9b6007/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-26284ys_
       cwd: /tmp/pip-install-ncko51il/psutil_c713283c0c1d4b5596370289ec9b6007/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
      from setuptools import windows_support
    File "/usr/local/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/03/9a/95c4b3d0424426e5fd94b5302ff74cea44d5d4f53466e1228ac8e73e14b4/psutil-5.6.5.tar.gz#sha256=d051532ac944f1be0179e0506f6889833cf96e466262523e57a871de65a15147 (from https://pypi.org/simple/psutil/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psutil-5.6.4.tar.gz (447 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 481, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 545, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 35, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 47, in _setup_isolation
    build_reqs = self._get_build_requires_wheel()
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 82, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 168, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 328, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/pip-build-env-5k1o2xhx/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/tmp/pip-build-env-5k1o2xhx/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
    from setuptools import windows_support
  File "/tmp/pip-build-env-5k1o2xhx/overlay/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
