### ISSUE TITLE
Issues with 20, 22, and 826

### ISSUE THREAD

**Issue by JinHoshi** [DIGITALCRIMINALS/OnlyFans#429]
Windows 10, I already did the upgrade with both PIP and PIP3 according to other issues, that had any of the same line issues.

Traceback (most recent call last):
  File "C:\Users\super\Documents\OnlyFans-7.6.1\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "C:\Users\super\Documents\OnlyFans-7.6.1\tests\main_test.py", line 22, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\super\Documents\OnlyFans-7.6.1\helpers\main_helper.py", line 826, in get_config
    json_config = ujson.load(open(config_path))
ujson.JSONDecodeError: Expected object or value

**Comment by DIGITALCRIMINALS** [comment]
Fix your config.
