### ISSUE TITLE
Scraper trying to process accounts I'm no longer subscribed to, leading to FileNotFoundErrors

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#430]
I'm at wit's end trying to understand why the scraper keeps trying to scrape accounts that I'm not even subscribed to anymore.

> Traceback (most recent call last):
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 66, in
> asyncio.run(main())
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
> return loop.run_until_complete(main)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
> return future.result()
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
> api = await main_datascraper.start_datascraper(config, site_name)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
> await default(datascraper)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
> await main_helper.process_jobs(datascraper, subscription_list, site_settings)
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 1056, in process_jobs
> await datascraper.start_datascraper(authed, username,whitelist=["Messages"])
> File "C:\Users\username\Desktop\OnlyFans-master\modules\module_streamliner.py", line 82, in start_datascraper
> await self.prepare_scraper(subscription, content_type)
> File "C:\Users\username\Desktop\OnlyFans-master\modules\module_streamliner.py", line 251, in prepare_scraper
> await self.process_scraped_content(master_set, content_type, subscription)
> File "C:\Users\username\Desktop\OnlyFans-master\modules\module_streamliner.py", line 298, in process_scraped_content
> await process_metadata(
> File "C:\Users\username\Desktop\OnlyFans-master\classes\prepare_metadata.py", line 654, in process_metadata
> os.remove(legacy_metadata)
> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'X:\\OnlyFans\\OnlyFans\\banginpromos\\Metadata\\Messages.db'

**Comment by avekifes** [comment]
I was able to get around the problem by switching the scraping of paid content to off, but I still have no idea how I would fix the FileNotFoundError.
