### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by lamepennies** [DIGITALCRIMINALS/OnlyFans#431]
Getting this error on linux:

RuntimeError: can't start new thread
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea440>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea7d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb4c0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb220>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb0a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb3a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeba90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb490>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeab00>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeab60>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea770>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebe9ba0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea470>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea500>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebe9840>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb040>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea350>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebeb250>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebe9db0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3b0ebea5f0>

I'm using the latest commit. I did have a previous session work fine but I cancelled the operation...or so I thought. Any idea?

**Comment by lamepennies** [comment]
I guess a bit more details using v8 from the git pull:





Welcome USER | USER
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-5' coro=<create_auth.get_subscriptions.<locals>.multi() done, defined at /DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py:285> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/DIR/USER/scripts/OnlyFans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/DIR/USER/scripts/OnlyFans/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/DIR/USER/scripts/OnlyFans/datascraper/main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "/DIR/USER/scripts/OnlyFans/helpers/main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/modules/module_streamliner.py", line 371, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/modules/onlyfans.py", line 402, in get_all_subscriptions
    results = await authed.get_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 335, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 306, in multi
    results2 = await asyncio.gather(*tasks)
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 221, in get_user
    response = await self.session_manager.json_request(link)
  File "/DIR/USER/scripts/OnlyFans/apis/api_helper.py", line 193, in json_request
    response = await request_method(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 813, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 306, in multi
    results2 = await asyncio.gather(*tasks)
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 221, in get_user
    response = await self.session_manager.json_request(link)
  File "/DIR/USER/scripts/OnlyFans/apis/api_helper.py", line 193, in json_request
    response = await request_method(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 813, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324af0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03249a0>
Traceback (most recent call last):
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/DIR/USER/scripts/OnlyFans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/DIR/USER/scripts/OnlyFans/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/DIR/USER/scripts/OnlyFans/datascraper/main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "/DIR/USER/scripts/OnlyFans/helpers/main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/modules/module_streamliner.py", line 371, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/modules/onlyfans.py", line 402, in get_all_subscriptions
    results = await authed.get_subscriptions(
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 335, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 306, in multi
    results2 = await asyncio.gather(*tasks)
  File "/DIR/USER/scripts/OnlyFans/apis/onlyfans/classes/auth_model.py", line 221, in get_user
    response = await self.session_manager.json_request(link)
  File "/DIR/USER/scripts/OnlyFans/apis/api_helper.py", line 193, in json_request
    response = await request_method(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/DIR/USER/venv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 813, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DIR/USER/scripts/OnlyFans/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 562, in shutdown_default_executor
    thread.start()
  File "/home/USER/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03259f0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325a80>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03257b0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0327580>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324910>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03258d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325a20>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03259c0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325990>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325900>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03257e0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325870>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03258a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325810>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325840>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325960>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0327670>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325bd0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325ba0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325b70>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0327460>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325630>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325570>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03269b0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324b20>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325720>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03270d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0325660>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324790>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324610>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324640>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324700>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324550>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324160>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324250>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324d30>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03244c0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03244f0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc03245e0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5bc0324670>

**Comment by DIGITALCRIMINALS** [comment]
I'd set max_threads to 1, maybe that would resolve it.
