### ISSUE TITLE
Fansly: Initial subscription list scrape stalls

### ISSUE THREAD

**Issue by lordoffools** [DIGITALCRIMINALS/OnlyFans#437]
Running the latest commit from 3 days ago (d417277).

I'm not getting any error messages, so I'm not sure what useful information I can provide this time.

After authenticating successfully, it just stalls (normally I would expect it to finish scraping the list of subscriptions and then display those for selection).

@DIGITALCRIMINALS What can I provide here that'll be useful since I have no errors / stacktrace?

Thank you.

**Comment by lordoffools** [comment]
It finally timed out with this error:

Auth (V1) Attempt 1/10
Welcome XXXX
Traceback (most recent call last):
  File "/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/datascraper/main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "/helpers/main_helper.py", line 1013, in account_setup
    await datascraper.manage_subscriptions(
  File "/modules/module_streamliner.py", line 371, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "/modules/fansly.py", line 393, in get_all_subscriptions
    results = await authed.get_followings(identifiers=identifiers)
  File "/apis/fansly/classes/auth_model.py", line 272, in get_followings
    create_user(x, self) for x in temp_followings["response"]
TypeError: 'NoneType' object is not subscriptable

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed
