### ISSUE TITLE
Cannot Scrapt a certain Model

### ISSUE THREAD

**Issue by 666diabolus** [DIGITALCRIMINALS/OnlyFans#441]
I kept getting error when I try to scrapt the model name miariderx, it keep showing this type of message
Been using the latest release (Dec)

```
Scrape Attempt: 1/100
Missing 200 Posts... Retrying...
Scrape Attempt: 2/100
Missing 200 Posts... Retrying...
Scrape Attempt: 3/100
Missing 400 Posts... Retrying...
Scrape Attempt: 4/100
Missing 533 Posts... Retrying...
Scrape Attempt: 5/100
Missing 800 Posts... Retrying...
Scrape Attempt: 6/100
Missing 1280 Posts... Retrying...
Scrape Attempt: 7/100
Missing 2133 Posts... Retrying...
Scrape Attempt: 8/100
Missing 3657 Posts... Retrying...
Scrape Attempt: 9/100
```

**Comment by 666diabolus** [comment]
and now the December release starting to announce this error : 

`Traceback (most recent call last):
  File "F:\Temp - Copy (2)\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\filco\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\filco\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\Temp - Copy (2)\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "F:\Temp - Copy (2)\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "F:\Temp - Copy (2)\helpers\main_helper.py", line 942, in process_profiles
    auth = api.add_auth(json_auth)
  File "F:\Temp - Copy (2)\apis\onlyfans\onlyfans.py", line 45, in add_auth
    temp_auth_details = auth_details(options).upgrade_legacy(options)
  File "F:\Temp - Copy (2)\apis\onlyfans\classes\extras.py", line 9, in __init__
    self.cookie = cookie_parser(options.get("cookie", ""))
  File "F:\Temp - Copy (2)\apis\onlyfans\classes\extras.py", line 63, in __init__
    key, value = crumble.strip().split("=")
ValueError: too many values to unpack (expected 2)`

**Comment by lucky1luc** [comment]
Was any solution found for this? I have the same problem now. (After a couple of months of no-OF, I wanted to restart scraping again. Changed the Auth.json and got the above error (to many values to unpack)

I have the windows 11 python app installed, which is at version Python 3.10.9

Poetry does not give an error while installing via pip, but does not start either (a bunch of 'requirement already satisfied' messages appear when re-trying to pip install poetry, so I assume that installation went correctly

What else is there to try?

**Comment by lucky1luc** [comment]
Check the auth.json and remove anything that is behind ref_src= 
Your cookie line in the auth.json should look like this at the end: cookie : "............; ref_src=;",
That fixed it for me.
