### ISSUE TITLE
Onlyfans not working

### ISSUE THREAD

**Issue by Shingotink** [DIGITALCRIMINALS/OnlyFans#444]
Onlyfans stopped working a few days ago

PS C:\Users\shing\Desktop\OnlyFans-7.6> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\shing\Desktop\OnlyFans-7.6\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\shing\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\shing\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\shing\Desktop\OnlyFans-7.6\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\shing\Desktop\OnlyFans-7.6\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\shing\Desktop\OnlyFans-7.6\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\Users\shing\Desktop\OnlyFans-7.6\helpers\main_helper.py", line 976, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "C:\Users\shing\Desktop\OnlyFans-7.6\helpers\main_helper.py", line 775, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: control character (\u0000-\u001F) found while parsing a string at line 5 column 0: line 5 column 1 (char 337)

**Comment by eddycoolgo** [comment]
I have the same problem, please help!

**Comment by Shingotink** [comment]
I was able to
