### ISSUE TITLE
Error Traceback (most recent call last):

### ISSUE THREAD

**Issue by Playerhater01** [DIGITALCRIMINALS/OnlyFans#457]
Please help!!!

TTraceback (most recent call last):
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\helpers\main_helper.py", line 962, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "C:\Users\mc2be\Downloads\OnlyFans-7.6.1(2)\OnlyFans-7.6.1\helpers\main_helper.py", line 761, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: expected value at line 4 column 14: line 4 column 14 (char 58)

**Comment by DIGITALCRIMINALS** [comment]
fix ur config
