### ISSUE TITLE
auth problem

### ISSUE THREAD

**Issue by Lanneer487** [DIGITALCRIMINALS/OnlyFans#459]
Hi,

I've a problem with my authentification.
When I use the info for another onlyfans-scraper on github, it works perfectly.
But with this one It won't connect.

`Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/usr/src/app/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/usr/src/app/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'`

Someone knows the solution for this?

**Comment by Kurosaki22** [comment]
After I had to update my session key and so on the scraper also stopped working for me.

`G:\Photo\_OF_Scraper\OnlyFans>start_ofd.py
Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "G:\Photo\_OF_Scraper\OnlyFans\helpers\main_helper.py", line 962, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "G:\Photo\_OF_Scraper\OnlyFans\helpers\main_helper.py", line 761, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: expected `,` or `}` at line 7 column 5: line 7 column 5 (char 373)`

**Comment by Kurosaki22** [comment]
Ok I was able to fix it.
I downloaded the master and started from scratch.
I let the tool create a new config and settings file and so on.
I just imported my .sites folder and now it is working again
