### ISSUE TITLE
No module named yarl when start_ofd.py

### ISSUE THREAD

**Issue by pashata777** [DIGITALCRIMINALS/OnlyFans#468]
I can't even start the script, I get the following :

Traceback (most recent call last):
  File "D:\downloads\OnlyFans-master\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "D:\downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 21, in <module>
    import classes.make_settings as make_settings
  File "D:\downloads\OnlyFans-master\OnlyFans-master\classes\make_settings.py", line 6, in <module>
    from yarl import URL
ModuleNotFoundError: No module named 'yarl'

python 3.10.4

**Comment by MonkeyKingViper** [comment]
I don't know much about Python...but you you run the following:

pip install yarl

It should install the missing package "yarl" which will make it work. Don't know why it's missing for you but since it is, you should be good after.

**Comment by RB1875** [comment]
See this thread for details on how to solve

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/364
