### ISSUE TITLE
Line 20, 22, 826 JSONDecodeError

### ISSUE THREAD

**Issue by Felix-stowe** [DIGITALCRIMINALS/OnlyFans#469]
Running Python 3.10 on Windows 10
When running Start.ofd I get the below issue. I do get a warning about my pip version 22.0.4 with 22.1 being available but might not be relevant to this. 

Traceback (most recent call last):
  File "C:\Users\X\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "C:\Users\X\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\tests\main_test.py", line 22, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\X\Downloads\OnlyFans-7.6.1\OnlyFans-7.6.1\helpers\main_helper.py", line 826, in get_config
    json_config = ujson.load(open(config_path))
ujson.JSONDecodeError: Expected object or value

**Comment by DIGITALCRIMINALS** [comment]
fix config
