### ISSUE TITLE
KeyError: 'author' error back again?

### ISSUE THREAD

**Issue by Shingotink** [DIGITALCRIMINALS/OnlyFans#47]
I have 2 profiles. One with under 200 models works fine and one with over 1000 won't load.

Traceback (most recent call last):
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\datascraper\main_datascraper.py", line 69, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\modules\onlyfans.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\modules\onlyfans.py", line 1266, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\apis\onlyfans\classes\create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\apis\onlyfans\classes\create_auth.py", line 282, in multi
    subscriptions = [
TypeError: 'NoneType' object is not iterable

**Comment by Shingotink** [comment]
Yeah seems to be a rate limit of some sort.

I tried it again a few hours ago and it was still not working with my main with 1000+ models but worked fine with my secondary with less than 200 models

**Comment by Shingotink** [comment]
> 
> 
> > Yeah seems to be a rate limit of some sort.
> > I tried it again a few hours ago and it was still not working with my main with 1000+ models but worked fine with my secondary with less than 200 models
> 
> Lower the threads in the config

I tried 20, 10 and 5, but still not working

**Comment by Shingotink** [comment]
Last night it just started working again, still working right now.
