### ISSUE TITLE
Text file length exceeded.

### ISSUE THREAD

**Issue by valiumx** [DIGITALCRIMINALS/OnlyFans#482]
I have the following error:

0it [00:00, ?it/s]Traceback (most recent call last):
  File "C:\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 103, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 975, in process_downloads
    await module.prepare_downloads(subscription)
  File "C:\OnlyFans-7.6.1\modules\onlyfans.py", line 1252, in prepare_downloads
    await main_helper.async_downloads(download_list, subscription)
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 255, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 250, in run
    await asyncio.gather(*tasks)
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 227, in process_download
    status_code = await write_data(
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 1030, in write_data
    with open_partial(download_path) as f:
  File "C:\OnlyFans-7.6.1\helpers\main_helper.py", line 1017, in open_partial
    return open(partial_path, "xb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\OnlyFans-7.6.1\\.sites\\OnlyFans\\scarlettmrose\\Posts\\Free\\Images\\19-05-2021 - Like all my pictures on my profile feed , so I’ll can post more FREE HOT STUFF 🔥🔥🔥 (Don’t worry no one can see your likes   comments, Only me 😋😘) https   -068ed3e7beab.jpg.part'

I know what the issue is -  its to do with how I set the file format. I wanted to have the date and text showing to make it easier to sort files out. The issue comes about if the content's text is greater than the text length and the script freezes because it can't write the file. I have tried the max- 255 chars and I have also tried 0. 0 works and the script runs to completion but only that date is scrapped as the filename. Wondering if anyone had a similar issue?

**Comment by Beareschal** [comment]
Probably errors because of the {text} variable being used. It's not just the length limit that would be a factor; that setting should just cut off the file name when it reaches 255 characters.
My best guess is that It picks up the emojis and other invalid characters people use in posts and causes it to error out.
