### ISSUE TITLE
KeyError: 'user_id'

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#486]
`Traceback (most recent call last):
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 415, in paid_content_scraper
    await process_metadata(
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/helpers/main_helper.py", line 575, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'`

**Comment by misterscraper** [comment]
anyone got a fix?

**Comment by marcintosch** [comment]
Did you change the auth.json?
