### ISSUE TITLE
Two errors in two different scenarios.

### ISSUE THREAD

**Issue by Captshadow** [DIGITALCRIMINALS/OnlyFans#49]
When I attempt to run the code start_ofd.py py double clicking, it throws the error "No module named 'sqlalchemy'" as seen below.

Traceback (most recent call last):
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

Second, when I attempt to run using "python start_ofd.py" it throws the error: "No module named 'aiohttp_socks'" as seen below.

Traceback (most recent call last):
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "C:\Users\jeff2\Desktop\OnlyFans-7.5.1\apis\api_helper.py", line 30, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'

**Comment by OFfriend** [comment]
looks like you have python problems.. check #43

**Comment by Captshadow** [comment]
Nevermind, read a little further into the article, appreciate the help with python!
