### ISSUE TITLE
Doesn't Run Anymore "post_id" issue

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#491]
I'm now starting to get some random errors when running the onlyfans scraper?

here is my code:

> Scraping Paid Content
Scraping - XXXXXXX| 1 / 7
100%|████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 267.28it/s]
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 627.32it/s]
Scraping - XXXXXXX | 2 / 7
Scraping - XXXXXXX | 3 / 7
100%|███████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1481.30it/s]
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 557.06it/s]
Scraping - XXXXXXX | 4 / 7
100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 915.59it/s]
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 91, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 415, in paid_content_scraper
    await process_metadata(
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/helpers/main_helper.py", line 575, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'

**Comment by mstiggles** [comment]
I think I have something similar going on...

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 1267, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment
