### ISSUE TITLE
ImportError: cannot import name 'Chrome' from 'selenium.webdriver' (unknown location)

### ISSUE THREAD

**Issue by ghost** [DIGITALCRIMINALS/OnlyFans#498]
Traceback (most recent call last):
  File "C:\Users\rapgo\Desktop\Riper\OnlyFans-7.6.1\start_ofd.py", line 24, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "C:\Users\rapgo\Desktop\Riper\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "C:\Users\rapgo\Desktop\Riper\OnlyFans-7.6.1\modules\onlyfans.py", line 14, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "C:\Users\rapgo\Desktop\Riper\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\rapgo\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\webdriver\__init__.py", line 3, in <module>
    from .browser import Chrome, Edge, Firefox, Safari  # noqa
  File "C:\Users\rapgo\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\webdriver\browser.py", line 1, in <module>
    from selenium.webdriver import Chrome as _Chrome, ChromeOptions
ImportError: cannot import name 'Chrome' from 'selenium.webdriver' (unknown location)

**Comment by djmarioka** [comment]
Similar error here, could you fix it?. Thanks.
![2022-07-05 06_57_38-ImportError_ cannot import name 'Chrome' from 'selenium webdriver' (unknown loca](https://user-images.githubusercontent.com/81478245/177252603-6cbcd8db-a076-4c30-8c2d-4b746d48c8e0.png)

**Comment by fightcancer2** [comment]
> Similar error here, could you fix it?. Thanks. ![2022-07-05 06_57_38-ImportError_ cannot import name 'Chrome' from 'selenium webdriver' (unknown loca](https://user-images.githubusercontent.com/81478245/177252603-6cbcd8db-a076-4c30-8c2d-4b746d48c8e0.png)

Same error here.
