### ISSUE TITLE
Script doesn't run anymore, KeyError: 'auth'

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#500]
I'm getting a constant KeyError: 'auth' message now when running the script, I've tried downloading the script fresh but nada happens..here is my error:

`python3 start_ofd.py
Traceback (most recent call last):
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Users/XXX/Downloads/OnlyFans-7.6.1/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'`

**Comment by DDERSaft** [comment]
I have the same problem, doesn't work anymore since 2 weeks or so...

any suggestion to solve this issue?

**Comment by koalahntr** [comment]
Check your .profiles folder for any .DS_STORE files and delete them. This fixed it for me.

**Comment by misterscraper** [comment]
I'm now getting the following:

`Traceback (most recent call last):
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1 2/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1 2/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1 2/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1 2/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1 2/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'`

this problem randomly happens and this is starting to get really annoying!

**Comment by aukeba** [comment]
I'm getting the same thing on macOS using the latest script. I'm gonna try the older versions and see if that does anything

**Comment by jackbeischel** [comment]
I had the same problem and the solution in https://github.com/DIGITALCRIMINALS/OnlyFans/issues/324 worked for me
