### ISSUE TITLE
Fansly Scrape Runtime Error?

### ISSUE THREAD

**Issue by Rakshae** [DIGITALCRIMINALS/OnlyFans#507]
It was working fine last week, I haven't made any changes.

> Traceback (most recent call last):
  File "K:\OnlyFans-6.4.3\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "K:\OnlyFans-6.4.3\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "K:\OnlyFans-6.4.3\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "K:\OnlyFans-6.4.3\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "K:\OnlyFans-6.4.3\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "K:\OnlyFans-6.4.3\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "K:\OnlyFans-6.4.3\modules\module_streamliner.py", line 238, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "K:\OnlyFans-6.4.3\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "K:\OnlyFans-6.4.3\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "K:\OnlyFans-6.4.3\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  [Previous line repeated 959 more times]
  File "K:\OnlyFans-6.4.3\apis\fansly\classes\user_model.py", line 399, in get_messages
    results = api_helper.merge_dictionaries(results)
  File "K:\OnlyFans-6.4.3\apis\api_helper.py", line 599, in merge_dictionaries
    final_dictionary: dict[str, Any] = merge({}, *items, strategy=Strategy.ADDITIVE)  # type: ignore
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python310\site-packages\mergedeep\mergedeep.py", line 100, in merge
    return reduce(partial(_deepmerge, strategy=strategy), sources, destination)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python310\site-packages\mergedeep\mergedeep.py", line 87, in _deepmerge
    dst[key] = deepcopy(src[key])
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240BFD12200>
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by zeldatp151** [comment]
I am also having this same issue, but with the latest commit.

**Comment by mediaburnwayne** [comment]
Same issue, fansly scraper is totally hosed. I tried wacking everything and downloading latest nd same issue. This project has not been updated in months and I fear it is dead

**Comment by mediaburnwayne** [comment]
Happens on the message portion of scrape.



Name: fansly creator
Type: Stories
Type: Posts
Type: Archived Posts
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████| 461/461 [00:01<00:00, 325.19it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████| 461/461 [00:23<00:00, 19.47it/s]
Type: Archived
Type: Chats
Type: Messages
Traceback (most recent call last):
  File "M:\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "M:\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "M:\OnlyFans\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "M:\OnlyFans\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "M:\OnlyFans\helpers\main_helper.py", line 1040, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "M:\OnlyFans\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "M:\OnlyFans\modules\module_streamliner.py", line 238, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "M:\OnlyFans\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "M:\OnlyFans\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "M:\OnlyFans\apis\fansly\classes\user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  [Previous line repeated 959 more times]
  File "M:\OnlyFans\apis\fansly\classes\user_model.py", line 399, in get_messages
    results = api_helper.merge_dictionaries(results)
  File "M:\OnlyFans\apis\api_helper.py", line 599, in merge_dictionaries
    final_dictionary: dict[str, Any] = merge({}, *items, strategy=Strategy.ADDITIVE)  # type: ignore
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\mergedeep\mergedeep.py", line 100, in merge
    return reduce(partial(_deepmerge, strategy=strategy), sources, destination)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\mergedeep\mergedeep.py", line 87, in _deepmerge
    dst[key] = deepcopy(src[key])
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016A0D65DEA0>
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by nightwolf151** [comment]
I wonder if we can set it to exclude the messages section of the scrape as a temporary fix, so we can at least get the feed stuff.

**Comment by 666diabolus** [comment]
he's been aware of the problems but he's on another project before the fix. The project is getting better and better, not dead 
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/506#issuecomment-1182555394

**Comment by blanuk** [comment]
well, i cannot downloading from fansly anymore too. BUT: Fansly shows me a message that im browsing to fast thru the site.
i think it blocks because of the speed :/
maybee there should be some pause in it or so.

**Comment by AlexDucks** [comment]
The "fix" is just to not scrape messages. If you have `"auto_api_choice": "0"` for Fansly in `.settings/config.json`, which would normally scrape all APIs, then set it to: `"auto_api_choice": "1,2,3,4,6,7"`

`0` would normally be "All" - while `1,2,3,4,6,7` is every other API except "Messages":
> `Choose Contents: 0 = All | 1 = Stories | 2 = Posts | 3 = Archived | 4 = Chats | 5 = Messages | 6 = Highlights | 7 = MassMessages`
(I'm not sure if all of these are even used, but might as well include most of them)

This seems to work for me at least, though of course it won't scrape messages, but it should at least scrape the posts.

**Comment by blanuk** [comment]
works for me too, thanks :)

**Comment by Rakshae** [comment]
> The "fix" is just to not scrape messages. If you have `"auto_api_choice": "0"` for Fansly in `.settings/config.json`, which would normally scrape all APIs, then set it to: `"auto_api_choice": "1,2,3,4,6,7"`
> 
> `0` would normally be "All" - while `1,2,3,4,6,7` is every other API except "Messages":
> 
> > `Choose Contents: 0 = All | 1 = Stories | 2 = Posts | 3 = Archived | 4 = Chats | 5 = Messages | 6 = Highlights | 7 = MassMessages`
> > (I'm not sure if all of these are even used, but might as well include most of them)
> 
> This seems to work for me at least, though of course it won't scrape messages, but it should at least scrape the posts.

Worked like a charm

**Comment by AlexDucks** [comment]
@Rakshae Just my opinion, but I think it might be better to keep the issue open for now since it's still a bug in the application.

It'll also increase the odds of anyone else with the same problem to find this issue (so there aren't duplicate issues created).

**Comment by nightwolf151** [comment]
Agree, this issue is not completed, there is just a work around that restores partial functionality.
