### ISSUE TITLE
Traceback error?

### ISSUE THREAD

**Issue by RK625** [DIGITALCRIMINALS/OnlyFans#508]
So I'm on a mac, using docker. I have not had any issues with this till lately.

Getting this error:
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/usr/src/app/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/usr/src/app/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'

Any help in fixing this would be very appreciated.

**Comment by koalahntr** [comment]
Check your .profiles folder for any .DS_STORE files and delete them. This fixed it for me.
