### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by sk1dd0** [DIGITALCRIMINALS/OnlyFans#510]
Hi, when I attempt to run the script I recieve this error and the window instantly closes. I am not sure what to do and have tried installing different versions, and reinstalling requirements.txt

```
Traceback (most recent call last):
  File "E:\other iykyk\OFFICAIL\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\other iykyk\OFFICAIL\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "E:\other iykyk\OFFICAIL\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "E:\other iykyk\OFFICAIL\OnlyFans-7.6.1\helpers\main_helper.py", line 937, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ujson.JSONDecodeError: Expected object or value
```

**Comment by sk1dd0** [comment]
Opened the auth file for onlyfans and there was an error in the text i fixed with quotation marks being on wrong place. Not sure if I caused this but all is fixed now and running
