### ISSUE TITLE
Attribute Error or another Traceback Error

### ISSUE THREAD

**Issue by JamiDEV** [DIGITALCRIMINALS/OnlyFans#517]
Traceback (most recent call last):
  File "/Users/mymac/Desktop/OnlyFans-master/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/mymac/Desktop/OnlyFans-master/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/mymac/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/mymac/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "/Users/mymac/Desktop/OnlyFans-master/modules/module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "/Users/mymac/Desktop/OnlyFans-master/modules/module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "/Users/mymac/Desktop/OnlyFans-master/modules/onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "/Users/mymac/Desktop/OnlyFans-master/apis/onlyfans/classes/user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results]
  File "/Users/mymac/Desktop/OnlyFans-master/apis/onlyfans/classes/user_model.py", line 283, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "/Users/mymac/Desktop/OnlyFans-master/apis/onlyfans/classes/hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by JamiDEV** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/516#issuecomment-1192808225

the fix.
