### ISSUE TITLE
GETTING THIS ERROR WHEN I TRY TO CREATE .JOHN AND CONFIG FILE 

### ISSUE THREAD

**Issue by cuenta111** [DIGITALCRIMINALS/OnlyFans#519]
c:\of>python start_ofd.py
Traceback (most recent call last):
  File "c:\of\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "c:\of\helpers\main_helper.py", line 21, in <module>
    import classes.make_settings as make_settings
  File "c:\of\classes\make_settings.py", line 6, in <module>
    from yarl import URL
ModuleNotFoundError: No module named 'yarl'

PLEASE HELP ME SOLVE THIS ISSUE

**Comment by Rhysdabeast** [comment]
`pip3 install yarl` in your command prompt should do the trick
