### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by mbielikG** [DIGITALCRIMINALS/OnlyFans#528]
Choose Subscriptions: 0 = All | 1 = helenstar18
1
Scraping Subscriptions
Scrape Processing
Name: helenstar18
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Stories
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/usr/src/app/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/usr/src/app/helpers/main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "/usr/src/app/modules/module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "/usr/src/app/modules/module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "/usr/src/app/modules/onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "/usr/src/app/apis/onlyfans/classes/user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results]
  File "/usr/src/app/apis/onlyfans/classes/user_model.py", line 283, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "/usr/src/app/apis/onlyfans/classes/hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by mbielikG** [comment]
Closing, duplicate
