### ISSUE TITLE
Error on first "login"

### ISSUE THREAD

**Issue by PretzelGravy** [DIGITALCRIMINALS/OnlyFans#535]
I get this error once i have selected the profile.

Welcome uxxxxxxx | uxxxxxxx
Traceback (most recent call last):
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 996, in account_setup
    export_json(mass_messages, metadata_filepath)
  File "C:\Users\44758\Downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 767, in export_json
    filepath.parent.mkdir(exist_ok=True)
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '.profiles\\u2341451\\Metadata'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F6E2772290>
Traceback (most recent call last):
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\44758\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Any help would be greatly appreciated

**Comment by kieeeee24Self** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/533
