### ISSUE TITLE
I'm getting a different Fansly error than everyone else...??

### ISSUE THREAD

**Issue by hsg120** [DIGITALCRIMINALS/OnlyFans#537]
The scraper stopped working for me about the same time people began having trouble with this in particular https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518

But that's not the same error that I'm getting, and I'm not seeing anyone post the error that I'm seeing--

Traceback (most recent call last):
  File "/media/jordan/DATAPART1/OnlyFans-master/./start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/jordan/DATAPART1/OnlyFans-master/./start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/media/jordan/DATAPART1/OnlyFans-master/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/media/jordan/DATAPART1/OnlyFans-master/datascraper/main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "/media/jordan/DATAPART1/OnlyFans-master/helpers/main_helper.py", line 999, in account_setup
    await datascraper.manage_subscriptions(
  File "/media/jordan/DATAPART1/OnlyFans-master/modules/module_streamliner.py", line 371, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "/media/jordan/DATAPART1/OnlyFans-master/modules/fansly.py", line 393, in get_all_subscriptions
    results = await authed.get_followings(identifiers=identifiers)
  File "/media/jordan/DATAPART1/OnlyFans-master/apis/fansly/classes/auth_model.py", line 271, in get_followings
    final_followings = [
  File "/media/jordan/DATAPART1/OnlyFans-master/apis/fansly/classes/auth_model.py", line 272, in <listcomp>
    create_user(x, self) for x in temp_followings["response"]
  File "/media/jordan/DATAPART1/OnlyFans-master/apis/fansly/classes/user_model.py", line 242, in __init__
    self.avatar = media_options[0]["location"]
IndexError: list index out of range

Everything was working great until about a week ago. 

I've tried Onlyfans-master and Onlyfans-7.6.1. Both work with Onlyfans, but both give me this same error when trying to scrape Fansly.

Any thoughts or suggestions would be most appreciated.

**Comment by kieeeee24Self** [comment]
Try Fansly-scraper

**Comment by hsg120** [comment]
kieeeee24Self I really appreciate the suggestion! I'll give it a whirl and report back.

**Comment by hsg120** [comment]
For anyone else having problems using the Onlyfans scraper for Fansly, kieeeee24Self is correct, Fansly-scraper works.

kieeeee24Self, thanks again for the suggestion--it's most apreciated!

**Comment by purpleemoji** [comment]
I will second that fansly-scraper works very well, but I really hope to get OF DataScraper working  again for fansly. 
OF Data Scraper has a much better folder structure. Also the fact that the media file properties match the date/time posted on the creator's account was a big plus for me.

**Comment by DIGITALCRIMINALS** [comment]
Fixed this
