### ISSUE TITLE
Still Getting Traceback Error

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINALS/OnlyFans#54]
I have followed [#43](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/43) and updated everything but I am still getting a traceback error as soon as I start the script. I have everything loaded, installed, updated, and rebooted.

> Traceback (most recent call last):
>   File "X:\Programs\OnlyFans\start_ofd.py", line 12, in <module>
>     main_test.check_config()
>   File "X:\Programs\OnlyFans\tests\main_test.py", line 21, in check_config
>     import helpers.main_helper as main_helper
>   File "X:\Programs\OnlyFans\helpers\main_helper.py", line 2, in <module>
>     from apis import api_helper
>   File "X:\Programs\OnlyFans\apis\api_helper.py", line 30, in <module>
>     from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
> ModuleNotFoundError: No module named 'aiohttp_socks'

![Screenshot 2021-10-21 080326](https://user-images.githubusercontent.com/43517545/138462321-0771316d-1d52-410f-b28a-37ee91ea103a.jpg)
![Screenshot 2021-10-21 080347](https://user-images.githubusercontent.com/43517545/138462129-7bade457-5c81-4973-b32a-4dfa6e489eb2.jpg)
![Screenshot 2021-10-21 080439](https://user-images.githubusercontent.com/43517545/138462130-2c331250-a8cd-4f80-8c32-98b10b26155b.jpg)
![Screenshot 2021-10-22 093802](https://user-images.githubusercontent.com/43517545/138463321-7505b2ba-14a3-4817-b1bc-3817ef7cad4a.jpg)
![Screenshot 2021-10-22 094712](https://user-images.githubusercontent.com/43517545/138464888-c8b5b890-5fb6-4df9-a1d7-204d147023d9.jpg)

**Comment by goodboi69** [comment]
> 
> 
> you installed both 32 & 64 bit and the module in my instructions is for 64 bit. From the picture I can see that the 32 bit Version is in use. I'll adjust my instructions. For 32 bit you need `lxml‑4.6.3‑cp310‑cp310‑win32.whl` from https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

You are vague with your response. I have installed the 32bit version of lxml because the 64bit is not compatible with my system.
