### ISSUE TITLE
Fresh download still keep getting Auth Errors

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#540]
Anyone got a work around for this, one moment it works and then next boom i'm getting this:

Traceback (most recent call last):
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Users/thegoat/Downloads/OnlyFans-7.6.1/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'

**Comment by misterscraper** [comment]
anyone got a fix for this???? seems like this project is dead

**Comment by kieeeee24Self** [comment]
> anyone got a fix for this???? seems like this project is dead

not really, but of keeps changing

**Comment by misterscraper** [comment]
> > anyone got a fix for this???? seems like this project is dead
> 
> not really, but of keeps changing

nobody got a fix for this error?

**Comment by marcintosch** [comment]
you have to fill in the `x_bc` value, too.

**Comment by aukeba** [comment]
I have mine filled in and double check the auth file using textedit and I still get the error?

**Comment by Tramp-ish** [comment]
> anyone got a fix for this???? seems like this project is dead

I believe I found a fix here: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/622#issuecomment-1235560296
