### ISSUE TITLE
auth.json not showing up

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINALS/OnlyFans#555]
When I run start_ofd.py it creates the settings and profile directories. It opens the settings json when its done with that it just close out back to the prompt and auth.json never appears in the profile directory. Any help would be appreciated.

**Comment by AshSha1** [comment]
Had same issue before:
Use this:  poetry run python ./start_ofd.py

it will work

**Comment by elwoodflame** [comment]
that fixed it thank you.

**Comment by elwoodflame** [comment]
Spoke to soon. When I run this and select all i get the following.

Scrape Processing
Name: allyson_grey
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.sites\\OnlyFans\\allyson_grey\\Messages\\Metadata\\Images.json' -> '.sites\\OnlyFans\\allyson_grey\\Metadata\\Images_1.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ofrip\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "F:\ofrip\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "F:\ofrip\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "F:\ofrip\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "F:\ofrip\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "F:\ofrip\OnlyFans-master\modules\module_streamliner.py", line 72, in start_datascraper
    await main_helper.format_directories(
  File "F:\ofrip\OnlyFans-master\helpers\main_helper.py", line 1388, in format_directories
    shutil.move(metadata_filepath, new_m_f)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.sites\\OnlyFans\\allyson_grey\\Messages\\Metadata\\Images.json'

any Idea whats wrong?
