### ISSUE TITLE
Auto Media Choice failing

### ISSUE THREAD

**Issue by thepetcow** [DIGITALCRIMINALS/OnlyFans#574]
Setting `"auto_media_choice": [0]` results in an error after initial scraping.

`Traceback (most recent call last):
  File "M:\Ripper\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Squeaky\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Squeaky\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "M:\Ripper\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "M:\Ripper\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "M:\Ripper\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "M:\Ripper\OnlyFans-7.6.1\modules\onlyfans.py", line 144, in start_datascraper
    api_array = scrape_choice(authed, subscription)
  File "M:\Ripper\OnlyFans-7.6.1\modules\onlyfans.py", line 176, in scrape_choice
    choice_list = main_helper.choose_option(media_types, auto_media_choice)
  File "M:\Ripper\OnlyFans-7.6.1\helpers\main_helper.py", line 901, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'`

Here is a snippet from the config

`{
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": true,
        "auto_media_choice": [0],
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },`

**Comment by Rhysdabeast** [comment]
Change it to `"auto_media_choice": "All"`
