### ISSUE TITLE
Unable to get past initial site selection step

### ISSUE THREAD

**Issue by lordoffools** [DIGITALCRIMINALS/OnlyFans#581]
This just started happening this afternoon in v7.6.1, so I'm assuming either it's a strange issue on my end (no libs or anything have changed on my end), or it's got something to do with the dynamically loaded code?

```
python start_ofd.py 
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Traceback (most recent call last):
  File "/OnlyFans-7.6.1/start_ofd.py", line 108, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/OnlyFans-7.6.1/start_ofd.py", line 93, in main
    api = await main_datascraper.start_datascraper(
  File "/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "/OnlyFans-7.6.1/helpers/main_helper.py", line 992, in process_profiles
    auth = api.add_auth(json_auth)
  File "/OnlyFans-7.6.1/apis/onlyfans/onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "/OnlyFans-7.6.1/apis/onlyfans/classes/create_auth.py", line 52, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "/OnlyFans-7.6.1/apis/api_helper.py", line 97, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "/Library/Python/3.10/lib/python/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I can reproduce regardless of which site I select at the intro (either 0 for OF or 1 for F or 2 for S), so it can't be any changes on the site's part itself.

**Comment by god43** [comment]
same thing

  File "D:\OnlyFans-master\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\OnlyFans-master\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "D:\OnlyFans-master\helpers\main_helper.py", line 942, in process_profiles
    auth = api.add_auth(json_auth)
  File "D:\OnlyFans-master\apis\onlyfans\onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "D:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 44, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "D:\OnlyFans-master\apis\api_helper.py", line 95, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

**Comment by meanjoep92** [comment]
It's nice to know that I'm not the only one suddenly experiencing these errors. 

Having the EXACT same problem when the program was running fine earlier today.

**Comment by nunga** [comment]
Same here. My window was open from last night, so I was able to scrape an account successfully this morning, then it came up with the error when it tried to get the subscription list.


_PS C:\OF_scraper> poetry run python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultimascraper-9En8Lxug-py3.10\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OF_scraper\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\OF_scraper\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\OF_scraper\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\OF_scraper\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\OF_scraper\helpers\main_helper.py", line 967, in process_profiles
    auth = api.add_auth(json_auth)
  File "C:\OF_scraper\apis\onlyfans\onlyfans.py", line 31, in add_auth
    auth = create_auth(self, pool=self.pool, max_threads=self.max_threads)
  File "C:\OF_scraper\apis\onlyfans\classes\auth_model.py", line 52, in __init__
    self.session_manager = self._session_manager(self, max_threads=max_threads)
  File "C:\OF_scraper\apis\onlyfans\classes\auth_model.py", line 68, in __init__
    api_helper.session_manager.__init__(
  File "C:\OF_scraper\apis\api_helper.py", line 129, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultimascraper-9En8Lxug-py3.10\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
PS C:\OF_scraper>_

**Comment by meanjoep92** [comment]
> I'm getting this too. It appears that api_helper.py looks for the following file: https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json
> 
> This file doesn't appear to exist any more?

I also suspected that this was possibly the issue, but not sure if any of the devs could possibly confirm this.

**Comment by tyrion-the-imp** [comment]
Look like someone was working on it as recently as 2 hours ago.  Maybe just need to wait until they're done with it and get a new version put up there.

**Comment by jerry199507** [comment]
https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json
Originally need to request from this url to sign, now this url cannot be accessed

**Comment by coltonshipley** [comment]
It looks like something probably broke with the automation that generates that dynamic value json value. Hopefully it gets fixed. Kinda appears something changed and the process automatically nuked the file.

**Comment by firemanchampion** [comment]
If you look at the history for today: 
https://github.com/DATAHOARDERS/dynamic-rules/commits/main
They pushed out two bad updates. Both don't work (one doesn't allow login/busted, other is just blank)
Use the one from Aug 8th:
https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json

Use that URL for dynamic_rules_link in .settings/config.json

**Comment by lordoffools** [comment]
Hmm, strangely, that doesn't work for me. Is there a need to toggle something else for that older one to work?

**Comment by naodrej** [comment]
yeah that's not working for me either.

**Comment by firemanchampion** [comment]
Can't help you there, worked for me just now.  You can try the Aug 9th one I guess.

**Comment by lordoffools** [comment]
I've tried multiple past ones. Still doesn't work. So either there's a setting that I'm not toggling correctly, or that's not sufficient to fix it (for v7.6.1 and/or just for me).

**Comment by RonnieBlaze** [comment]
> If you look at the history for today: https://github.com/DATAHOARDERS/dynamic-rules/commits/main They pushed out two bad updates. Both don't work (one doesn't allow login/busted, other is just blank) Use the one from Aug 8th: https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json
> 
> Use that URL for dynamic_rules_link in .settings/config.json

this worked for me, Thanks!

**Comment by naodrej** [comment]
For those that it worked for, what version are you on? Are you on 7.6.1?

**Comment by firemanchampion** [comment]
I'm using the master branch if that helps. What isn't working for you exactly? Provide some feedback and people can help direct you what the issue may be.

**Comment by naodrej** [comment]
I'm on 7.6.1, I just tried replacing the links. The result is the same as the error above

**Comment by lordoffools** [comment]
That's the difference, indeed. Master / latest vs. v7.6.1 (the last "official" release).

**Comment by GooseWhoIsLoose** [comment]
> I'm using the master branch if that helps. What isn't working for you exactly? Provide some feedback and people can help direct you what the issue may be.

How do you use the master branch? I'm on the latest official release (7.6.1)

Having the same issue as the original poster, btw.

**Comment by MonkeyKingViper** [comment]
> If you look at the history for today: https://github.com/DATAHOARDERS/dynamic-rules/commits/main They pushed out two bad updates. Both don't work (one doesn't allow login/busted, other is just blank) Use the one from Aug 8th: https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json
> 
> Use that URL for dynamic_rules_link in .settings/config.json

Confirming this worked for me. Many thanks!
Also, I'm on 85aec02 if anyone needs a version this is fixed with

**Comment by nunga** [comment]
I'm not sure which version I'm using but updating  **.settings/config.json** as suggested by @firemanchampion worked for me.   Thanks!

_"dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json",_

**Comment by GooseWhoIsLoose** [comment]
> I'm not sure which version I'm using but updating .settings/config.json as suggested by @firemanchampion worked for me. Thanks!

I'm not having any luck... so to clarify, you changed 

`"dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",`

on line 45 to 

`"dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json",`

Is that right? Just save the file and run?

**Comment by hollowsmart** [comment]
Just confirming myself on latest release 7.6.1 - changing the dynamic_rules_link works.

**Comment by GooseWhoIsLoose** [comment]
> Just confirming myself on latest release 7.6.1 - changing the dynamic_rules_link works.

Hollowsmart, can you elaborate on what exactly you did? Just swapping the URL out isn't working for me

**Comment by lucky1luc** [comment]
I downloaded and replaced the config.json (first I saved my version - 7.6.1 - not modiffied since 2-may-2022 to config.json.saved)
That did not work (gave me some versioning error),
so I removed the new config.json and restored the old one... and now it works????

**Comment by maxcom99** [comment]
Looks like the original URL works now

**Comment by GooseWhoIsLoose** [comment]
Yeah... seems to be working for me now too, with the original URL. Weird.

**Comment by lordoffools** [comment]
Interestingly, I didn't even switch back to the original URL, and it just works now.

So it leads me to wonder if even changing dynamic_rules_link mattered in v7.6.1, or if there was something else also affecting this (in addition to dynamic_rules_link) which has now been resolved?

Leaving this bug open for one of the devs to review and reply accordingly (especially if there's no further action needed), and then close it.

Thank you all.

**Comment by OFfriend** [comment]
There was bug in dynamic_rules which was fixed. You can close ths issue.

**Comment by hempires47** [comment]
not sure if this is same error, but i'm also unable to get past the initial selection.
tried changing the link as suggested, which didn't help.

`Auth (V1) Attempt 1/10
Traceback (most recent call last):
  File "D:\Downloads\OnlyFans-7.6.1\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Downloads\OnlyFans-7.6.1\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "D:\Downloads\OnlyFans-7.6.1\helpers\main_helper.py", line 983, in account_setup
    authed = await auth.login()
  File "D:\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\auth_model.py", line 109, in login
    await self.process_auth()
  File "D:\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\auth_model.py", line 169, in process_auth
    response = await self.session_manager.json_request(link)
  File "D:\Downloads\OnlyFans-7.6.1\apis\api_helper.py", line 193, in json_request
    response = await request_method(
  File "C:\Users\golds\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 557, in _request
    resp = await req.send(conn)
  File "C:\Users\golds\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "C:\Users\golds\AppData\Roaming\Python\Python310\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp\_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp\_http_writer.pyx", line 116, in aiohttp._http_writer._safe_header
ValueError: Newline or carriage return character detected in HTTP status message or header. This is a potential security issue.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F0A671BDF0>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F0A3EB6290>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed`
