### ISSUE TITLE
Error at stories

### ISSUE THREAD

**Issue by waytoospicy** [DIGITALCRIMINALS/OnlyFans#585]
Getting this: 

Name: niykeecruz
Type: Profile
Type: Stories
Traceback (most recent call last):
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\wayto\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\wayto\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\Users\wayto\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by thecrazypozavnist** [comment]
Workaround found in issue #518 seems to fix it.
> In the file apis\onlyfans\classes\create_user.py change the line 270 from: `results = [create_highlight(x) for x in results]` to `results = [create_highlight(x) for x in results.get("data")]`

Unfortunately after that I can't download anything apart from headers but I'm hopeful it's going to be fixed

**Comment by bobeuology** [comment]
If you changed any settings in the config.json file prior to the above fix it may be producing the error you're experiencing. Try a clean copy of the script or reverse any changes you made to the config.json file and the `results = [create_highlight(x) for x in results.get("data")]` fix should work. The `AttributeError: module 'selenium.webdriver' has no attribute 'Opera'` error will still need to be fixed however. [https://github.com/DIGITALCRIMINALS/OnlyFans/issues/496](url)

**Comment by DIGITALCRIMINALS** [comment]
I need the model username or any "free" model that has a story/highlight on their profile to replicate the issue.

**Comment by left1000** [comment]
7.6.1

no fix applied

error:
```
AttributeError: 'str' object has no attribute 'get'
```

free model with this story highlight:

https://onlyfans.com/missgeee
