### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINALS/OnlyFans#594]
```

> Traceback (most recent call last):
>   File "B:\Downloads\OnlyFans\start_ofd.py", line 104, in <module>
>     asyncio.run(main())
>   File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "B:\Downloads\OnlyFans\start_ofd.py", line 86, in main
>     api = await main_datascraper.start_datascraper(
>   File "B:\Downloads\OnlyFans\datascraper\main_datascraper.py", line 58, in start_datascraper
>     auths = choose_option(subscription_list, auto_profile_choice, True)
>   File "B:\Downloads\OnlyFans\helpers\main_helper.py", line 901, in choose_option
>     if value.isdigit():
> AttributeError: 'int' object has no attribute 'isdigit'

```

any idea on a fix? i think my auth and configs are all right...

**Comment by vscum** [comment]
seems to have been fixed by this: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/125#issuecomment-983141190

**Comment by DIGITALCRIMINALS** [comment]
fixed
