### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by porncritic** [DIGITALCRIMINALS/OnlyFans#606]
no problem logging in or getting model list, only when trying do download model

why am I getting this?:
Type: Profile
100%|█████████████████████████████████████████████████████████████████████████████| 6.79M/6.79M [00:00<00:00, 8.20MB/s]
Type: Stories
Traceback (most recent call last):
  File "L:\OnlyFans-master\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\Omen PC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Omen PC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "L:\OnlyFans-master\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "L:\OnlyFans-master\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "L:\OnlyFans-master\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "L:\OnlyFans-master\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "L:\OnlyFans-master\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "L:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results.get("data")]
TypeError: 'NoneType' object is not iterable

anyhelp would be appriciated thanks

**Comment by ESMP** [comment]
Same here, I didn't have this problem a couple of days ago.

**Comment by purpleemoji** [comment]
Problem definitely cropped up in the last 24 hour or so. Scraped successfully yesterday night with no issues.

**Comment by aboredpervert** [comment]
In `create_user.py` at line 270, change `"data"` to `"list"`.
Looks like they changed the response format again, let's hope it was the only change.

**Comment by ESMP** [comment]
Thanks @aboredpervert,  that did it.

**Comment by Proutbedaine** [comment]
> In `create_user.py` at line 270, change `"data"` to `"list"`. Looks like they changed the response format again, let's hope it was the only change.

That did it but I also had to do it on line 283 in user_model.py

**Comment by olivechicago** [comment]
> That did it but I also had to do it on line 283 in user_model.py

Changing the entry in user_model.py seems to have worked for me as well.  My create_user.py did not have this code at all.

**Comment by porncritic** [comment]
Thanks! @aboredpervert worked for me
