### ISSUE TITLE
Tried to scape some content today and these erros showed up

### ISSUE THREAD

**Issue by Yetdel** [DIGITALCRIMINALS/OnlyFans#611]
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "E:\download\o\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\download\o\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "E:\download\o\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "E:\download\o\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "E:\download\o\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "E:\download\o\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "E:\download\o\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results.get("data")]
TypeError: 'NoneType' object is not iterable

**Comment by Yetdel** [comment]
Ok i found the fix in the Issue #604 Im sorry

**Comment by Fall0n** [comment]
how did you get that to help? i have try and try still not working for me

**Comment by Yetdel** [comment]
apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]

**Comment by Fall0n** [comment]
> apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]

there is no line like that. i type it in the user_model.py and get 2 lines that have 283 or?

**Comment by barthramsay** [comment]
If you have the latest version v7.6.1 there is no user_model.py. See [this comment](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/604#issuecomment-1227700082)

You have to replace line 270 in file `apis/onlyfans/classes/create_user.py`

to

```
            results = [create_highlight(x) for x in results.get("list")]
```

**Comment by eclipseo** [comment]
Dup of #604
