### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by RK625** [DIGITALCRIMINALS/OnlyFans#613]
I've gone through many errors on here and cannot find out what is causing this error, was working fine last night. Now its not working. 

Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Traceback (most recent call last):
  File "/Volumes/MacMini/OnlyFans-7.6.1/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Volumes/MacMini/OnlyFans-7.6.1/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Volumes/MacMini/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Volumes/MacMini/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Volumes/MacMini/OnlyFans-7.6.1/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'

**Comment by Neph81** [comment]
I just encountered the same issue.  Running the update did not help nor did downloading the latest source.  Fansly will still work though, just not OnlyFans.

**Comment by RK625** [comment]
I've done that still having the same issue.

**Comment by eclipseo** [comment]
What do you have in .profiles/OnlyFans/default/auth.json (Mangle the value so it's not linked to you). It seems the "auth" object in the json config file is missing.

Have you created the config file as described in the README.md? Use this extension to make the process easier: https://github.com/M-rcus/OnlyFans-Cookie-Helper
