### ISSUE TITLE
Fansly issue KeyError: 'filename'

### ISSUE THREAD

**Issue by Allmaziful** [DIGITALCRIMINALS/OnlyFans#615]
Encountering the following issue after fansly model selection.

Traceback (most recent call last):
  File "C:\Program Files (x86)\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Program Files (x86)\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 156, in start_datascraper
    await main_helper.process_names(
  File "C:\Program Files (x86)\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Program Files (x86)\OnlyFans-7.6.1\modules\fansly.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Program Files (x86)\OnlyFans-7.6.1\modules\fansly.py", line 778, in prepare_scraper
    await profile_scraper(
  File "C:\Program Files (x86)\OnlyFans-7.6.1\modules\fansly.py", line 290, in profile_scraper
    filename: str = media_options["filename"].replace("..", ".")
KeyError: 'filename'

**Comment by Beareschal** [comment]
Can you currently scrape other models on fansly?

**Comment by Allmaziful** [comment]
> Can you currently scrape other models on fansly?

No this happens with every model (whether subscribed to or followed).

**Comment by Allmaziful** [comment]
> Can you currently scrape other models on fansly?

No it's the same with every model I've tried (both subscribed to and followed).

**Comment by eclipseo** [comment]
Try using the latest dev version: https://github.com/DIGITALCRIMINALS/OnlyFans/archive/refs/heads/master.zip

**Comment by Allmaziful** [comment]
> Try using the latest dev version: https://github.com/DIGITALCRIMINALS/OnlyFans/archive/refs/heads/master.zip

Am I missing something obvious or does the master version not even have code for fansly? I can't find it supported in config file.

**Comment by eclipseo** [comment]
> > Try using the latest dev version: https://github.com/DIGITALCRIMINALS/OnlyFans/archive/refs/heads/master.zip
> 
> Am I missing something obvious or does the master version not even have code for fansly? I can't find it supported in config file.

I see the code for Fansly with no issue? The defaults config for Fansly is:

```
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{date}_{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y%m%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
```
