### ISSUE TITLE
Traceback: AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

### ISSUE THREAD

**Issue by anonymousx61** [DIGITALCRIMINALS/OnlyFans#623]
> Traceback (most recent call last):
>   File "C:\Users\Test\Desktop\OnlyFans-7.6.1\start_ofd.py", line 24, in <module>
>     import datascraper.main_datascraper as main_datascraper
>   File "C:\Users\Test\Desktop\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 6, in <module>
>     import modules.onlyfans as m_onlyfans
>   File "C:\Users\Test\Desktop\OnlyFans-7.6.1\modules\onlyfans.py", line 14, in <module>
>     import extras.OFLogin.start_ofl as oflogin
>   File "C:\Users\Test\Desktop\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 2, in <module>
>     from seleniumwire import webdriver
>   File "C:\Users\Test\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
>     from selenium.webdriver import *  # noqa
> AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

Read around and not able to find a fix on this issue. Running the latest version of Python as well.

**Comment by anonymousx61** [comment]
Resolved with help from https://github.com/DIGITALCRIMINALS/OnlyFans/issues/496
