### ISSUE TITLE
Traceback error, began several days ago

### ISSUE THREAD

**Issue by GooseWhoIsLoose** [DIGITALCRIMINALS/OnlyFans#624]
Morning all,

A few days ago this program stopped working for me. I launch the program through console using the command `python start_ofd.py`.

I then get the error `Traceback (most recent call last):
  File "H:\onlyfans.master\start_ofd.py", line 24, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "H:\onlyfans.master\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "H:\onlyfans.master\modules\onlyfans.py", line 14, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "H:\onlyfans.master\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\Goose\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'`

If I run the same command again, from the same command prompt, I get `  File "H:\onlyfans.master\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'`

I'm on the latest official build, 7.6.1 (for Windows 10). I don't know how to get onto the latest unofficial version, but if someone would explain it, I'd be happy to try. I _have_ tried [this](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/604#issuecomment-1228400912) change to create_user.py, with no success. I tried this [https://github.com/DIGITALCRIMINALS/OnlyFans/issues/606#issuecomment-1228024483](url) change to user_model.py as well, still no luck.

I'd appreciate any advice you have, and am happy to provide any info you need.

Thank you! :)

**Comment by GooseWhoIsLoose** [comment]
Well, I feel foolish.

Resolved by following steps in #623, then #604.
