### ISSUE TITLE
Traceback: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by IncogPanda** [DIGITALCRIMINALS/OnlyFans#625]
Traceback (most recent call last):
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\cheen\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\cheen\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\Users\cheen\Downloads\HW\OnlyFans-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by SchmittyWerber** [comment]
[(https://github.com/DIGITALCRIMINALS/OnlyFans/issues/601)]

**Comment by SchmittyWerber** [comment]
(https://github.com/DIGITALCRIMINALS/OnlyFans/issues/601)

**Comment by djmarioka** [comment]
Same error here, could somebody help?:

![image](https://user-images.githubusercontent.com/81478245/190942728-2d6d6e53-d25f-40f7-94f0-bf45f4aec484.png)

Thanks!!
