### ISSUE TITLE
Traceback (most recent call last): / AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by tim1f1** [DIGITALCRIMINALS/OnlyFans#628]
Every time I try and scrap a profile I get the following error
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "C:\Users\tim_f\Documents\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\tim_f\Documents\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\tim_f\Documents\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\tim_f\Documents\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\Users\tim_f\Documents\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "C:\Users\tim_f\Documents\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "C:\Users\tim_f\Documents\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "C:\Users\tim_f\Documents\OnlyFans-master\modules\onlyfans.py", line 386, in get_all_stories
    master_set.extend(await subscription.get_stories())
  File "C:\Users\tim_f\Documents\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 260, in get_stories
    results = [create_highlight(x) for x in results.get("list")]
AttributeError: 'list' object has no attribute 'get'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F51DF92200>
Traceback (most recent call last):
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\tim_f\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by amajio** [comment]
```
Type: Stories
Traceback (most recent call last):
  File "F:\Desktop\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "F:\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "F:\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "F:\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "F:\Desktop\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "F:\Desktop\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "F:\Desktop\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "F:\Desktop\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "F:\Desktop\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'
```

**Comment by ChristophvdF** [comment]
Same one here. Looks like either the API of OF has changed or some breaking change in a dependency

```
Type: Stories
Traceback (most recent call last):
  File "P:\Development\Tools\OnlyFansScraper\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "P:\Development\Tools\OnlyFansScraper\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "P:\Development\Tools\OnlyFansScraper\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "P:\Development\Tools\OnlyFansScraper\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "P:\Development\Tools\OnlyFansScraper\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "P:\Development\Tools\OnlyFansScraper\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "P:\Development\Tools\OnlyFansScraper\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "P:\Development\Tools\OnlyFansScraper\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "P:\Development\Tools\OnlyFansScraper\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002668B1B2200>
Traceback (most recent call last):
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\djlee\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by eclipseo** [comment]
Dup of #604
