### ISSUE TITLE
App only downloaded avatar and header, error below

### ISSUE THREAD

**Issue by dembolito** [DIGITALCRIMINALS/OnlyFans#648]
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Stories
Traceback (most recent call last):
  File "C:\Users\Bartek\Desktop\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Bartek\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "C:\Users\Bartek\Desktop\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'
PS C:\Users\Bartek\Desktop\OnlyFans-master> poetry run python ./start_ofd.py

**I really dont know what is doing there, what is wrong with this?**

**Comment by dembolito** [comment]
It only download avatar and header

**Comment by dembolito** [comment]
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Stories
Traceback (most recent call last):
  File "C:\Users\Bartek\Desktop\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Bartek\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "C:\Users\Bartek\Desktop\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "C:\Users\Bartek\Desktop\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'
PS C:\Users\Bartek\Desktop\OnlyFans-master> poetry run python ./start_ofd.py

**Comment by starboi4eva** [comment]
Same error I'm getting.

**Comment by starboi4eva** [comment]
Hey I just fixed it by copying the fix from #604

**Comment by alexdevos7** [comment]
> Hey I just fixed it by copying the fix from #604

this unfortunately did not work for me

**Comment by starboi4eva** [comment]
Make sure you are using the master branch and copy the file to the root of that folder.
