### ISSUE TITLE
Can someone help me fix this? 

### ISSUE THREAD

**Issue by shanoclever** [DIGITALCRIMINALS/OnlyFans#652]
Updated my xbc and session and all that, and now this pops up. Can someone help?

PS C:\Users\bette\Downloads\7.6.1> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\bette\Downloads\7.6.1\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\bette\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\bette\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\bette\Downloads\7.6.1\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\Users\bette\Downloads\7.6.1\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\Users\bette\Downloads\7.6.1\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\Users\bette\Downloads\7.6.1\helpers\main_helper.py", line 971, in process_profiles
    export_json(datas, user_auth_filepath)
  File "C:\Users\bette\Downloads\7.6.1\helpers\main_helper.py", line 768, in export_json
    filepath.write_bytes(orjson.dumps(metadata, option=orjson.OPT_INDENT_2))
  File "C:\Users\bette\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1143, in write_bytes
    with self.open(mode='wb') as f:
  File "C:\Users\bette\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '.profiles\\OnlyFans\\default\\auth.json'
PS C:\Users\bette\Downloads\7.6.1>

**Comment by eclipseo** [comment]
Apparently Onlyfans is not allowed to read the file? Check the file permissions?
