### ISSUE TITLE
I get this error: ModuleNotFoundError: No module named 'orjson'

### ISSUE THREAD

**Issue by SasukeTenshi** [DIGITALCRIMINALS/OnlyFans#668]
Poetry installed successfully, but when I run python start_ofd.py I get this:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\OnlyFans-master (1)\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "C:\Users\user\Downloads\OnlyFans-master (1)\OnlyFans-master\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'
PS C:\Users\user\Downloads\OnlyFans-master (1)\OnlyFans-master>

I thought "pip install --upgrade --user -r requirements.txt" might fix my problem but there is no requirements.txt in the latest version.

**Comment by burhanilinux** [comment]
command
pip install orjson

Worked for me
