### ISSUE TITLE
Syntax error after choosing site

### ISSUE THREAD

**Issue by kevinholtkamp** [DIGITALCRIMINALS/OnlyFans#671]
When I run the script, after selecting the website, I get the following error:
```Traceback (most recent call last):
  File "C:\abc\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\abc\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\abc\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\abc\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\abc\helpers\main_helper.py", line 962, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "C:\abc\helpers\main_helper.py", line 761, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: expected `,` or `}` at line 5 column 3: line 5 column 3 (char 270)
```

**Comment by steveradabaugh** [comment]
Same issue here. I haven't been able to use the script since mid July. Tried reinstalling and various troubleshooting since then. The errors have changed, but never fully resolved. 

Issue started on MacOS 12.4 but persists on 13.0. Python is 3.10.
