### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by Macmasteri** [DIGITALCRIMINALS/OnlyFans#68]
So I have a new slot on my seed box and trying to get the ripper working again. I dont have the latest version since the one I had worked just fine on the old slot.

I do got an error now. Someone friendly user that can help me understand it?

```
Auth (V1) Attempt 1/10
Welcome xxx| xxx
Scraping Paid Content
Scraping - keishagrey | 1 / 11
  0%|                                                     | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/sdj/xxx/ofmaster2/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/media/sdj/xxx/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/media/sdj/xxx/ofmaster2/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/media/sdj/xxx/ofmaster2/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/media/sdj/xxx/ofmaster2/modules/onlyfans.py", line 398, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "/media/sdj/xxx/.local/lib/python3.9/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/media/sdj/xxx/.local/lib/python3.9/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/media/sdj/xxx/python/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/media/sdj/xxx/.local/lib/python3.9/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression
```

**Comment by americanseeder1865** [comment]
what does your requirements.txt file look like?

**Comment by mkmb1** [comment]
Exactly the same issue here. I tried couple of tqdm versions with no luck. Does anyone have a clue what is the problem?

**Comment by DIGITALCRIMINALS** [comment]
Use the latest version
