### ISSUE TITLE
Getting Bored Of KeyError: 'auth'

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#684]
Using this script is becoming an hit and miss, I keep getting these errors every othery day

"Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
0
Traceback (most recent call last):
  File "/Users/thegoat/Downloads/OnlyFans-master/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/thegoat/Downloads/OnlyFans-master/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/thegoat/Downloads/OnlyFans-master/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/thegoat/Downloads/OnlyFans-master/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/Users/thegoat/Downloads/OnlyFans-master/helpers/main_helper.py", line 963, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'"

It's becoming a bore, has anyone got a work around? This script seems to have a mind of it's own some days. I've checked all the auth details and they're correct with OF.

**Comment by origsgkid** [comment]
have you tried this? https://github.com/DIGITALCRIMINALS/OnlyFans/issues/399

worked for me today after getting latest

**Comment by DIGITALCRIMINALS** [comment]
Fixed, was due to people having files in the profile directory
