### ISSUE TITLE
Crash with commit 1058

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/OnlyFans#699]
It login correctly to OF and receive correctly the model list but when a model name is insert to be scraped it crash so fast that i cannot see the error neither

EDIT: i receive this error

```
Type: Stories
Scrape Attempt: 1/100
Processing Scraped Stories
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "E:\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "E:\OnlyFans-master\modules\module_streamliner.py", line 260, in prepare_scraper
    await self.process_scraped_content(master_set, content_type, subscription)
  File "E:\OnlyFans-master\modules\module_streamliner.py", line 288, in process_scraped_content
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\Bla\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Bla\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Bla\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "E:\OnlyFans-master\modules\onlyfans.py", line 138, in media_scraper
    if "preview" in media["files"] and "url" in media["files"]["preview"]:
TypeError: argument of type 'NoneType' is not iterable
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000215B565DE10>
Traceback (most recent call last):
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\Bla\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

E:\OnlyFans-master>
```

**Comment by CannotTouch** [comment]
Solved! Just check on wich model it crash and delete metadata directori of that model.
