### ISSUE TITLE
i have error with new release 

### ISSUE THREAD

**Issue by ZdrC991** [DIGITALCRIMINALS/OnlyFans#7]
Traceback (most recent call last):
  File "C:\Users\KORISNIK\Desktop\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\KORISNIK\Desktop\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\KORISNIK\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 92, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\KORISNIK\Desktop\OnlyFans-master\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\KORISNIK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 74, in gather
    ifs = [wrap_awaitable(i, f) for i, f in enumerate(fs)]
TypeError: 'coroutine' object is not iterable

**Comment by ZdrC991** [comment]
i use latest and this is error from that version...

**Comment by americanseeder1865** [comment]
alright, I will look into the code later

**Comment by DIGITALCRIMINALS** [comment]
Have you tried the latest release?

**Comment by ZdrC991** [comment]
i downloaded latest version 7.4.5 and i think its same error

Scraping Paid Content
Scraping - ******* | 1 / 20
Traceback (most recent call last):
  File "C:\Users\KORISNIK\Desktop\OnlyFans-7.4.5\OnlyFans-7.4.5\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\KORISNIK\Desktop\OnlyFans-7.4.5\OnlyFans-7.4.5\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\KORISNIK\Desktop\OnlyFans-7.4.5\OnlyFans-7.4.5\datascraper\main_datascraper.py", line 92, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\KORISNIK\Desktop\OnlyFans-7.4.5\OnlyFans-7.4.5\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\KORISNIK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 74, in gather
    ifs = [wrap_awaitable(i, f) for i, f in enumerate(fs)]
TypeError: 'coroutine' object is not iterable

**Comment by OFfriend** [comment]
pip3.10

> 
> 
> The issue was actually in tqdm: [tqdm/tqdm@223561a](https://github.com/tqdm/tqdm/commit/223561a83bcc0cca961b6b42403424b995c6e916)
> 
> The first parameter was manually unpacked and it shouldn't have been. OP needs to update their tqdm by re-running `pip3.9 install -r requirements.txt`.

`pip3.10`
