### ISSUE TITLE
Comparison between datetime.datetime and int

### ISSUE THREAD

**Issue by YJu3SkYQ24** [DIGITALCRIMINALS/OnlyFans#70]
It looks like something is returning mixed results for fansly content:

```
Traceback (most recent call last):
  File "~/OnlyFans/start_ofd.py", line 59, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "~/OnlyFans/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "~/OnlyFans/datascraper/main_datascraper.py", line 131, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "~/OnlyFans/modules/fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "~/OnlyFans/modules/fansly.py", line 1290, in manage_subscriptions
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

```
> ~/OnlyFans/modules/fansly.py(1291)manage_subscriptions()
-> results.sort(key=lambda x: x.subscribedByData["endsAt"])
(Pdb) p [x.subscribedByData['endsAt'] for x in results]
[datetime.datetime(2022, 10, 31, 22, 27, 38, 584672), datetime.datetime(2022, 10, 31, 22, 27, 38, 584733), datetime.datetime(2022, 10, 31, 22, 27, 38, 584760), datetime.datetime(2022, 10, 31, 22, 27, 38, 584781), datetime.datetime(2022, 10, 31, 22, 27, 38, 584802), datetime.datetime(2022, 10, 31, 22, 27, 38, 584821), datetime.datetime(2022, 10, 31, 22, 27, 38, 584840), 1636555965000, 1635828377000, 1638062689000, 1636610201000]
```

This patch is a quick and dirty fix, but its probably best to normalize the data as posts are fetched:
```
diff --git a/modules/fansly.py b/modules/fansly.py
index 6052fce..c703b64 100644
--- a/modules/fansly.py
+++ b/modules/fansly.py
@@ -1287,7 +1287,7 @@ async def manage_subscriptions(
                                     print(f"Blacklisted: {identifier}")
                                     results.remove(result)
     results = [x for x in results if x.subscribedByData or x.following]
-    results.sort(key=lambda x: x.subscribedByData["endsAt"])
+    results.sort(key=lambda x: datetime.fromtimestamp(x.subscribedByData["endsAt"]/1e3) if type(x.subscribedByData["endsAt"]) == int else x.subscribedByData["endsAt"])
     results.sort(key=lambda x: x.is_me(), reverse=True)
     results2 = []
     hard_blacklist = ["onlyfanscreators"]
```

**Comment by DIGITALCRIMINALS** [comment]
Thanks, latest commit should work

**Comment by YJu3SkYQ24** [comment]
Pulled 1593017 and it seems to be working :+1:
