### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINALS/OnlyFans#700]
I got everything up and running. Was able to authenticate and scrap paid content. We I tried to download everything after that, I get this weird error about "'str' object has no attribute 'get'" and I'm not sure what I'm doing wrong. Any help/insight would be greatly appreciated.

`Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
Traceback (most recent call last):
  File "/home/zachary/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/zachary/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/home/zachary/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "/home/zachary/OnlyFans-7.6.1/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/home/zachary/OnlyFans-7.6.1/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/home/zachary/OnlyFans-7.6.1/modules/onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "/home/zachary/OnlyFans-7.6.1/apis/onlyfans/classes/create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "/home/zachary/OnlyFans-7.6.1/apis/onlyfans/classes/create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "/home/zachary/OnlyFans-7.6.1/apis/onlyfans/classes/create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'`

**Comment by lucky1luc** [comment]
see https://github.com/DIGITALCRIMINALS/OnlyFans/issues/601
