### ISSUE TITLE
Error when trying to scrape

### ISSUE THREAD

**Issue by vega69-ux** [DIGITALCRIMINALS/OnlyFans#706]
I'm not sure what I'm doing wrong. When I try to scrape I get the following error.

Type: Profile
Type: Stories
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\Users\*****\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by melstoll** [comment]
I got the same. Still no luck.

Was stuck on auth loop (404) until I run: sudo /Applications/Python\ 3.9/Install\ Certificates.command
and now I'm stuck on this Stories thing.

**Comment by rot2301** [comment]
got the same issue

**Comment by LuisKingArturo** [comment]
> I got the same. Still no luck.
> 
> Was stuck on auth loop (404) until I run: sudo /Applications/Python\ 3.9/Install\ Certificates.command and now I'm stuck on this Stories thing.

any solution

**Comment by melstoll** [comment]
I haven't and gave up. Tried the [https://github.com/k0rnh0li0/onlyfans-dl](url) and works like a charm, but have no way to 'personalize' the filenames, which is the best feature on DigitalCriminals script.

**Comment by vega69-ux** [comment]
I'm still having the same issue.

@melstoll https://github.com/k0rnh0li0/onlyfans-dl works? Do you have a video tutorial on installation and using onlyfans-dl? I clicked on the link and it says "No results matched your search."

**Comment by GreedyGhost1** [comment]
Any solution to this?

**Comment by DIGITALCRIMINALS** [comment]
I'd need to know the username of the model to recreate the issue.
