### ISSUE TITLE
Limit Issue back again. 

### ISSUE THREAD

**Issue by Shingotink** [DIGITALCRIMINALS/OnlyFans#71]
My profile with nearly 1500 models profile is not processing again. My secondary profile with less than 300 runs just fine.

Is there any way to end the process early and still get models listed? That way I can still process the models who are scheduled to expire.

Traceback (most recent call last):
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\start_ofd.py", line 59, in <module>
    asyncio.run(main())
  File "C:\Users\shing\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\shing\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\datascraper\main_datascraper.py", line 69, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\modules\onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\modules\onlyfans.py", line 1267, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\apis\onlyfans\classes\create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\apis\onlyfans\classes\create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "C:\Users\shing\Desktop\OnlyFans-7.5.1\apis\onlyfans\classes\create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

**Comment by DIGITALCRIMINALS** [comment]
Did it resolve itself? It usually works when you lower threads in the config

**Comment by Shingotink** [comment]
I recently found out that the fan in my laptop was failing. I now believe this is the reason my larger profile was failing, not anything to do with script.

I have been using a laptop cooling pad as a temporary fix and am having far less issues than I was before.

**Comment by lordofcookies** [comment]
I'm having this issue after upgrading to 7.6.1 just now.

Exactly the same error as above. Prior to 7.6.1, I ran just fine with threads = -1.

I have over 1,000 profiles.

I just tried threads = 100, and still hit this issue.
