### ISSUE TITLE
TRACEBACK ERROR

### ISSUE THREAD

**Issue by cuenta111** [DIGITALCRIMINALS/OnlyFans#718]
PLEASE HELP WITH SOLUTION :

getting this error after start  i select 1 here : Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN

Traceback (most recent call last):
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000202A911CEE0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000202A911CEE0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\of\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\pranj\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\pranj\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "e:\of\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "e:\of\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "e:\of\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "e:\of\helpers\main_helper.py", line 967, in process_profiles
    auth = api.add_auth(json_auth)
  File "e:\of\apis\onlyfans\onlyfans.py", line 31, in add_auth
    auth = create_auth(self, pool=self.pool, max_threads=self.max_threads)
  File "e:\of\apis\onlyfans\classes\auth_model.py", line 52, in __init__
    self.session_manager = self._session_manager(self, max_threads=max_threads)
  File "e:\of\apis\onlyfans\classes\auth_model.py", line 68, in __init__
    api_helper.session_manager.__init__(
  File "e:\of\apis\api_helper.py", line 129, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\pranj\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000202A911CEE0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

**Comment by DIGITALCRIMINALS** [comment]
With the latest commit, does it still do this?
