### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Jack-caldwar** [DIGITALCRIMINALS/OnlyFans#719]
Hello , 

i got it to auth fine and get into my account and list my subscriptions.

i chose one of them and started to download images, however, it crashed just after downloading a couple of things.
this happens every time.  

any ideas what am doing wrong ?

`Traceback (most recent call last):
  File "J:\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\the_s\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\the_s\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "J:\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "J:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "J:\OnlyFans-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "J:\OnlyFans-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "J:\OnlyFans-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "J:\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "J:\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "J:\OnlyFans-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'`

**Comment by GreedyGhost1** [comment]
I also got the same thing, any ideas?

**Comment by IntoTheBlackHole** [comment]
+1

**Comment by lucky1luc** [comment]
See https://github.com/DIGITALCRIMINALS/OnlyFans/issues/601
