### ISSUE TITLE
"Unexpected character in found when decoding object value" (latest python 3.10)

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINALS/OnlyFans#72]
Please help, i have multiple versions of python installed but using 3.10 for this. I have installed requirements multiple times, in multiple different ways. After uninstalling all python packages, restarting, and installing (and updating) python 3.10, i still get this error.

```
Traceback (most recent call last):
  File "B:\Github\OnlyFans\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "B:\Github\OnlyFans\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "B:\Github\OnlyFans\apis\api_helper.py", line 30, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'
```

I would assume the error is due to incomplete requirement installation, as running `pip install -r requirements.txt` gets me this nasty red string...

```Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.
Installing collected packages: psutil, mergedeep, lxml, jsonpickle, beautifulsoup4, alembic, aiohttp-socks
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\games\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'B:\\TEMP\\pip-install-jos92ejd\\psutil_305efd53b8f14694992a7e332f1cad81\\setup.py'"'"'; __file__='"'"'B:\\TEMP\\pip-install-jos92ejd\\psutil_305efd53b8f14694992a7e332f1cad81\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'B:\TEMP\pip-record-hyarw6eo\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\games\AppData\Local\Programs\Python\Python310\Include\psutil'
         cwd: B:\TEMP\pip-install-jos92ejd\psutil_305efd53b8f14694992a7e332f1cad81\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
    creating build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\games\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'B:\\TEMP\\pip-install-jos92ejd\\psutil_305efd53b8f14694992a7e332f1cad81\\setup.py'"'"'; __file__='"'"'B:\\TEMP\\pip-install-jos92ejd\\psutil_305efd53b8f14694992a7e332f1cad81\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'B:\TEMP\pip-record-hyarw6eo\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\games\AppData\Local\Programs\Python\Python310\Include\psutil' Check the logs for full command output.
```

**Comment by Luke-L** [comment]
solved. https://github.com/DIGITALCRIMINALS/OnlyFans/issues/20 #20

**Comment by Luke-L** [comment]
nope its almost working now but even after filling in my auth stuff for OF, i get these errors: 

```
Select Site: 0 = onlyfans | 1 = fansly |
0
Traceback (most recent call last):
  File "B:\Github\OnlyFans\start_ofd.py", line 59, in <module>
    asyncio.run(main())
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "B:\Github\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "B:\Github\OnlyFans\datascraper\main_datascraper.py", line 51, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 912, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value
```

**Comment by OFfriend** [comment]
you entered 0 or 1?

**Comment by Luke-L** [comment]
i entered 0 for OF mode

**Comment by OFfriend** [comment]
you entered 0 and something else

**Comment by Luke-L** [comment]
> 
> 
> you entered 0 and something else

just tried it again. hit 0, then enter, and came up with the same error.

**Comment by Luke-L** [comment]
Updating issue: Fansly seems to work fine even with no auth or account. Entering 0 for Onlyfans still gives that same error i listed above.
