### ISSUE TITLE
No module named 'orjson'

### ISSUE THREAD

**Issue by Xknight79** [DIGITALCRIMINALS/OnlyFans#721]
C:\OnlyFans-master>python start_ofd.py
Traceback (most recent call last):
  File "C:\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "C:\OnlyFans-master\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

**Comment by kccomikeyga** [comment]
pip install orjson

If you get any further errors like this, do "pip install [name]"
