### ISSUE TITLE
Fansly error

### ISSUE THREAD

**Issue by wireman21** [DIGITALCRIMINALS/OnlyFans#729]
When i try to run fansly, I get this error, does anyone know a fix or can link me to a solution please?

Traceback (most recent call last):
  File "C:\Users\Downloads\OnlyFans-7.6.1\start_ofd.py", line 103, in <module>
    asyncio.run(main())
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\Downloads\OnlyFans-7.6.1\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\Downloads\OnlyFans-7.6.1\modules\fansly.py", line 1290, in manage_subscriptions
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

**Comment by DIGITALCRIMINALS** [comment]
Fixed in latest commit
