### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by VeryCoolGamerMan** [DIGITALCRIMINALS/OnlyFans#73]
As soon as I start it I have this Issue. I updated Python, pip and sqlalchemy. I have no clue of programming and I really dont know what I'm looking at here, so any help would be appreciated.

Traceback (most recent call last):
  File "H:\OnlyFans-master\start_ofd.py", line 12, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "H:\OnlyFans-master\datascraper\main_datascraper.py", line 5, in <module>
    import helpers.main_helper as main_helper
  File "H:\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "H:\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by OFfriend** [comment]
check #43
