### ISSUE TITLE
Adding Directory Not Working ( Yes its formatted correctly) 

### ISSUE THREAD

**Issue by JamiDEV** [DIGITALCRIMINALS/OnlyFans#740]
The scraper is working wonderfully, until I run out of space. I have not been able to figure out why it doesnt let me add additional download directories. I followed the instructions correctly, and used "/" .  I haven't found any topics with this issue. 

I am on MacOS Big Sur. 

`Traceback (most recent call last):
  File "/Users/mymac/Desktop/OnlyFans-master/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/mymac/Desktop/OnlyFans-master/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/Users/mymac/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/Users/mymac/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 102, in default
    await main_helper.process_downloads(api, datascraper, global_settings)
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 1067, in process_downloads
    await datascraper.prepare_downloads(subscription)
  File "/Users/mymac/Desktop/OnlyFans-master/modules/module_streamliner.py", line 353, in prepare_downloads
    await main_helper.async_downloads(
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 310, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 305, in run
    await asyncio.gather(*tasks)
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 278, in process_download
    status_code = await write_data(
  File "/Users/mymac/Desktop/OnlyFans-master/helpers/main_helper.py", line 1147, in write_data
    f.write(data)
`

Update : looks like the rolling over when a directory is full doesnt work

**Comment by DIGITALCRIMINALS** [comment]
Set `min_drive_space` to 1 (this means 1GB minimum of space required, before rolling over to next directory)
