### ISSUE TITLE
ModuleNotFoundError: No module named 'ultima_scraper_renamer'

### ISSUE THREAD

**Issue by basketballhead6** [DIGITALCRIMINALS/OnlyFans#747]
Created a fresh installation and this error occurs when trying to scrape:

Finished processing metadata.
Traceback (most recent call last):
  File "D:\Personal\OF-master\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Personal\OF-master\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 106, in default
    await datascraper.process_jobs(datascraper, subscription_list, site_settings)
  File "D:\Personal\OF-master\ultima_scraper\modules\module_streamliner.py", line 531, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "D:\Personal\OF-master\ultima_scraper\modules\module_streamliner.py", line 106, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "D:\Personal\OF-master\ultima_scraper\modules\module_streamliner.py", line 301, in prepare_scraper
    await self.process_scraped_content(master_set, content_type, subscription)
  File "D:\Personal\OF-master\ultima_scraper\modules\module_streamliner.py", line 351, in process_scraped_content
    await metadata_manager.process_metadata(
  File "D:\Personal\OF-master\ultima_scraper\metadata_manager\metadata_manager.py", line 31, in process_metadata
    from ultima_scraper_renamer import renamer
ModuleNotFoundError: No module named 'ultima_scraper_renamer'

**Comment by lilfmdude** [comment]
i did pip install ultima_scraper_renamer and it installed a ton of things try that

**Comment by basketballhead6** [comment]
Yup that fixed it. Thank you! 

> i did pip install ultima_scraper_renamer and it installed a ton of things try that
