### ISSUE TITLE
scraper issues - multiple scrapers and other issues

### ISSUE THREAD

**Issue by mstiggles** [DIGITALCRIMINALS/OnlyFans#749]
Hey,
I used to be able to run multiple scrapers (8) at a time but as of last night as soon as I open a second scraper it fails. I have tried following some of the suggestions in the discussions and issues logs, but to no avail. I have this traceback. let me know if you can help

 File "C:\Users\matt\Downloads\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\matt\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\helpers\main_helper.py", line 942, in process_profiles
    auth = api.add_auth(json_auth)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\onlyfans\onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 44, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\api_helper.py", line 95, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\matt\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\matt\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\matt\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\matt\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\matt\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /DATAHOARDERS/dynamic-rules/main/onlyfans.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019922293D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by mstiggles** [comment]
I am also getting this error 
Traceback (most recent call last):
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\matt\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\modules\onlyfans.py", line 1267, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "C:\Users\matt\Downloads\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

**Comment by DIGITALCRIMINALS** [comment]
Use the latest commit
