### ISSUE TITLE
Unable to scrape 1 profile, new install.

### ISSUE THREAD

**Issue by Aer3x** [DIGITALCRIMINALS/OnlyFans#758]
Tried a new install, also same error.

```
Scraping Subscriptions
Scrape Processing
Name: ***
Type: Stories
Processing Scraped Stories
  0%|                                                                                          | 0/112 [00:00<?, ?it/s]Traceback (most recent call last):
  File "H:\OnlyFans-master\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Users\dicker-PC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\dicker-PC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "H:\OnlyFans-master\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "H:\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "H:\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 106, in default
    await datascraper.process_jobs(datascraper, subscription_list, site_settings)
  File "H:\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 531, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "H:\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 106, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "H:\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 301, in prepare_scraper
    await self.process_scraped_content(master_set, content_type, subscription)
  File "H:\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 332, in process_scraped_content
    unrefined_set: list[dict[str, Any]] = await tqdm.gather(*tasks, **settings)
  File "C:\Users\dicker-PC\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-ydjPcDtY-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\dicker-PC\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-ydjPcDtY-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\dicker-PC\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\dicker-PC\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-ydjPcDtY-py3.10\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "H:\OnlyFans-master\ultima_scraper\modules\onlyfans.py", line 138, in media_scraper
    and "url" in media["files"]["preview"]
TypeError: argument of type 'NoneType' is not iterable
 47%|█████████████████████████████████████▊                                          | 53/112 [00:00<00:00, 272.45it/s]

```

**Comment by randomhappysack** [comment]
getting the same error on 1 profile, or all profiles...

**Comment by DIGITALCRIMINALS** [comment]
what's the model's username
