### ISSUE TITLE
Auth 404'ed: response["session_manager"] = self.session_manager TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by javierfs** [DIGITALCRIMINALS/OnlyFans#761]
My nano .profiles/OnlyFans/default/auth.json file looks like: 

```
{
  "auth": {
    "username": "default",
    "cookie": "auth_id=49170468; sess=les1ttpt8up38fr483qgnu3lha; auth_hash=; auth_uniq_49170468=; auth_uid_49170468=; aws-waf-token=;",
    "x_bc": "90c55799b48443b8e87e7c496fbe0206f7d1c71c",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": false,
    "active": true
  }
}

```

And I got the following output

```
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Traceback (most recent call last):
  File "/Users/javierfernandez/OF_datascrapper/OnlyFans/start_us.py", line 83, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/javierfernandez/OF_datascrapper/OnlyFans/start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/javierfernandez/OF_datascrapper/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 128, in start_datascraper
    await default(datascraper)
  File "/Users/javierfernandez/OF_datascrapper/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 73, in default
    setup, subscriptions = await datascraper.account_setup(
  File "/Users/javierfernandez/OF_datascrapper/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 486, in account_setup
    authed = await auth.login()
  File "/Users/javierfernandez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-IvZizp0r-py3.10/lib/python3.10/site-packages/ultima_scraper_api/apis/onlyfans/classes/auth_model.py", line 159, in login
    user = await self.get_user(auth_id)
  File "/Users/javierfernandez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-IvZizp0r-py3.10/lib/python3.10/site-packages/ultima_scraper_api/apis/onlyfans/classes/auth_model.py", line 223, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

```

**Comment by basketballhead6** [comment]
@javierfs Did you try running the script again? I got that error once but ran it again and everything was fine.
