### ISSUE TITLE
No such file or directory error while scraping

### ISSUE THREAD

**Issue by horatiorosa** [DIGITALCRIMINALS/OnlyFans#766]
I keep tripping over this error, not sure how to get past it.

```
Scraping - ofmodel | 22 / 24
Processing Scraped Messages
100% 1/1 [00:00<00:00, 10782.27it/s]
Processing metadata.
Finished processing metadata.
Traceback (most recent call last):
  File "OnlyFans/start_us.py", line 83, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/OnlyFans/start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 106, in default
    await datascraper.process_jobs(datascraper, subscription_list, site_settings)
  File "/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 539, in process_jobs
    await datascraper.paid_content_scraper(authed)
  File "/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 254, in paid_content_scraper
    await self.process_scraped_content(
  File "/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 351, in process_scraped_content
    await metadata_manager.process_metadata(
  File "/OnlyFans/ultima_scraper/metadata_manager/metadata_manager.py", line 44, in process_metadata
    result = await self.db_manager.export_sqlite(self.db_manager.database_path, api_type, new_metadata_object)
  File "/Library/Caches/pypoetry/virtualenvs/ultima-scraper-L6hGDV5E-py3.10/lib/python3.10/site-packages/ultima_scraper_api/database/db_manager.py", line 54, in export_sqlite
    metadata_directory.mkdir(exist_ok=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'ofmodel/Metadata
```
I don't sub to this OF account anymore so I'd be happy to skip it but my blacklist isn't set up right. Maybe.
```
"blacklists": ["ofmodel"],
```

**Comment by DIGITALCRIMINALS** [comment]
[blacklists](https://github.com/DIGITALCRIMINALS/OnlyFans#blacklist_name)

**Comment by DIGITALCRIMINALS** [comment]
Blacklist has been fixed on the latest commit, but maybe the issue has been fixed, so you might not need to blacklist them anymore
