### ISSUE TITLE
Script always crashes on the same model

### ISSUE THREAD

**Issue by icemouton** [DIGITALCRIMINALS/OnlyFans#773]
So I get this crash on every run of the script. 
Latest Commit, Ubuntu.

I added the model to my blacklist and she still gets processed in the later stages, the weirdest thing is that the file it's trying to get to and crash the script exists and is on my drive with the right permissions and everyting. 

I'm no longer subbed to that model I don't even want the content.. any ideas ?

```
Scraping - {modelName} | 181 / 228
Processing Scraped Messages
100% 1/1 [00:00<00:00, 4382.76it/s]
Processing metadata.
Finished processing metadata.
Traceback (most recent call last):
  File "/secure/src/OnlyFans/start_us.py", line 83, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/secure/src/OnlyFans/start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "/media/secure/src/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/media/secure/src/OnlyFans/ultima_scraper/datascraper/main_datascraper.py", line 106, in default
    await datascraper.process_jobs(datascraper, subscription_list, site_settings)
  File "/media/secure/src/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 539, in process_jobs
    await datascraper.paid_content_scraper(authed)
  File "/media/secure/src/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 254, in paid_content_scraper
    await self.process_scraped_content(
  File "/media/secure/src/OnlyFans/ultima_scraper/modules/module_streamliner.py", line 351, in process_scraped_content
    await metadata_manager.process_metadata(
  File "/media/secure/src/OnlyFans/ultima_scraper/metadata_manager/metadata_manager.py", line 44, in process_metadata
    result = await self.db_manager.export_sqlite(self.db_manager.database_path, api_type, new_metadata_object)
  File "/home/user/.cache/pypoetry/virtualenvs/ultima-scraper-8jpyxqlB-py3.10/lib/python3.10/site-packages/ultima_scraper_api/database/db_manager.py", line 54, in export_sqlite
    metadata_directory.mkdir(exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'OnlyFans/{modelName}/Metadata'
```

**Comment by DIGITALCRIMINALS** [comment]
which model is this?
