### ISSUE TITLE
KeyError: 'user_id'

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#774]
Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "D:\Users\BLANK\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\BLANK\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans Scrapper\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\OnlyFans Scrapper\ultima_scraper\datascraper\main_datascraper.py", line 73, in default
    setup, subscriptions = await datascraper.account_setup(
  File "D:\OnlyFans Scrapper\ultima_scraper\modules\module_streamliner.py", line 486, in account_setup
    authed = await auth.login()
  File "C:\Users\BLANK\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-qRD0JCle-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 101, in login
    self.session_manager.headers = create_headers(*a)
  File "C:\Users\BLANK\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-qRD0JCle-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 207, in create_headers
    headers.pop(remove_header)
KeyError: 'user_id'

**Comment by Site3op** [comment]
I switched to these dynamic rules (https://github.com/deviint/onlyfans-dynamic-rules). After getting the refresh page error when attempting to scrape today.
