### ISSUE TITLE
Error Code 401 'Please Refresh the Page'

### ISSUE THREAD

**Issue by basketballhead6** [DIGITALCRIMINALS/OnlyFans#775]
Does anyone know why this error is occuring. It started to happening to me today.

Error: {'code': 401, 'message': 'Please refresh the page'}
Error: {'code': 401, 'message': 'Please refresh the page'}
Please refresh the page
Error: {'code': 401, 'message': 'Please refresh the page'}
Traceback (most recent call last):
  File "D:\Personal\OF-master\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Personal\OF-master\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 83, in default
    profile_directory = api.base_directory_manager.profile.root_directory
AttributeError: 'DirectoryManager' object has no attribute 'profile'

**Comment by DIGITALCRIMINALS** [comment]
It's to do with OnlyFans breaking, usually waiting a few minutes it should work again.

**Comment by basketballhead6** [comment]
> It's to do with OnlyFans breaking, usually waiting a few minutes it should work again.

@DIGITALCRIMINALS I've tried again this morning after waiting several hours and it still is creating the same error

**Comment by DIGITALCRIMINALS** [comment]
I updated dynamic rules, the 401 error should be gone

**Comment by basketballhead6** [comment]
@DIGITALCRIMINALS  Thank you! How long will it take for the rawgithub to update to the new file as it looks like it still is pulling the old version when you go to the URL

**Comment by DIGITALCRIMINALS** [comment]
No idea, it's down to Github's caching but for me it's updated to the latest one

**Comment by basketballhead6** [comment]
It's just updated for me. Thanks!
