### ISSUE TITLE
Error Code 401 - Please refresh page

### ISSUE THREAD

**Issue by hollowsmart** [DIGITALCRIMINALS/OnlyFans#780]
Still getting having this issue now, same as #775. Tried reinstalling and also running updater.py. Is there something I'm missing?

> Error: {'code': 401, 'message': 'Please refresh the page'}
Error: {'code': 401, 'message': 'Please refresh the page'}
Please refresh the page
Error: {'code': 401, 'message': 'Please refresh the page'}
Traceback (most recent call last):
  File "D:\Downloads\OF-7.6.1\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Downloads\OF-7.6.1\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 83, in default
    profile_directory = api.base_directory_manager.profile.root_directory
AttributeError: 'DirectoryManager' object has no attribute 'profile'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EEB3F84670>
Traceback (most recent call last):
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by basketballhead6** [comment]
Try using this repo for dynamic rules: https://github.com/deviint/onlyfans-dynamic-rules

**Comment by hollowsmart** [comment]
> Try using this repo for dynamic rules: https://github.com/deviint/onlyfans-dynamic-rules
> 
> The default dynamic rules attached to this project is updated manually whereas this repo updates automatically

Thanks for that. Sorry to ask, but where can I find instructions on how to use this repo? Is it a file I replace or something I add to a json file?

**Comment by DIGITALCRIMINALS** [comment]
> > Try using this repo for dynamic rules: https://github.com/deviint/onlyfans-dynamic-rules
> > The default dynamic rules attached to this project is updated manually whereas this repo updates automatically
> 
> Thanks for that. Sorry to ask, but where can I find instructions on how to use this repo? Is it a file I replace or something I add to a json file?

Replace dynamic rules link in the config with this one

```https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json```

**Comment by hollowsmart** [comment]
> > > Try using this repo for dynamic rules: https://github.com/deviint/onlyfans-dynamic-rules
> > > The default dynamic rules attached to this project is updated manually whereas this repo updates automatically
> > 
> > 
> > Thanks for that. Sorry to ask, but where can I find instructions on how to use this repo? Is it a file I replace or something I add to a json file?
> 
> Replace dynamic rules link in the script's config with this one
> 
> `https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json`

Thanks again. Makes heaps of sense now. Unfortunately encountering a new error not unlike #774 now:

> Traceback (most recent call last):
  File "D:\Downloads\OF-7.6.1\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Downloads\OF-7.6.1\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 73, in default
    setup, subscriptions = await datascraper.account_setup(
  File "D:\Downloads\OF-7.6.1\ultima_scraper\modules\module_streamliner.py", line 486, in account_setup
    authed = await auth.login()
  File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 101, in login
    self.session_manager.headers = create_headers(*a)
  File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 207, in create_headers
    headers.pop(remove_header)
KeyError: 'user_id'
