### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by TheSulak3** [DIGITALCRIMINALS/OnlyFans#782]
C:\Users\{username}\Desktop\OnlyFans-master>
C:\Users\{username}\Desktop\OnlyFans-master>poetry run python start_us.py
Traceback (most recent call last):
  File "C:\Users\{username}\Desktop\OnlyFans-master\start_us.py", line 27, in <module>
    main_test.check_profiles()
  File "C:\Users\{username}\Desktop\OnlyFans-master\tests\main_test.py", line 43, in check_profiles
    profile_directories = settings.profile_directories
AttributeError: 'Settings' object has no attribute 'profile_directories'

I dont know whats wrong, i've set auth.json and things and this appears on screen whenever I try to open the program

**Comment by Rocket3192** [comment]
Same, happened after the 3 hours ago update

**Comment by DIGITALCRIMINALS** [comment]
Update the script again
