### ISSUE TITLE
Key Error when Launching Scraper

### ISSUE THREAD

**Issue by basketballhead6** [DIGITALCRIMINALS/OnlyFans#786]
When I launch the scraper after the update the following error occurs when trying to use any of the APIs:

Traceback (most recent call last):
  File "D:\Personal\OF-master\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Personal\OF-master\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Personal\OF-master\ultima_scraper\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Personal\OF-master\ultima_scraper\modules\module_streamliner.py", line 550, in account_setup
    authed = await auth.login()
             ^^^^^^^^^^^^^^^^^^
  File "D:\Personal\OF-master\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 100, in login
    self.session_manager.headers = create_headers(*a)
                                   ^^^^^^^^^^^^^^^^^^
  File "D:\Personal\OF-master\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 207, in create_headers
    headers.pop(remove_header)
KeyError: 'user_id'

**Comment by jacobkossman** [comment]
muddled through the upgrade today and getting this as well. even after switching to these dynamic rules: `https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json` still getting the above error.

anyone fix this yet?

**Comment by basketballhead6** [comment]
@jacobkossman I messed around a little bit and it look like the error is caused because of a mismatch between the dynamic rules and the script. Fixed the script to match the dynamic rules but it threw a different error after I matched the values so still waiting on @DIGITALCRIMINALS to provide a fix.

**Comment by DIGITALCRIMINALS** [comment]
I can't fix that.
OnlyFans uses `user-id` in their headers but that fork is using `user_id` for a reason I don't know.

**Comment by basketballhead6** [comment]
> I can't fix that.
> 
> OnlyFans uses `user-id` in their headers but that fork is using `user_id` for a reason I don't know.

Bummer... @DIGITALCRIMINALS can you put the GitHub raw link to your dynamic rules so I can switch it back please? Thank you

**Comment by DIGITALCRIMINALS** [comment]
> > I can't fix that.
> > OnlyFans uses `user-id` in their headers but that fork is using `user_id` for a reason I don't know.
> 
> Bummer... @DIGITALCRIMINALS can you put the GitHub raw link to your dynamic rules so I can switch it back please? Thank you

https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json
