### ISSUE TITLE
orjson.JSONDecodeError

### ISSUE THREAD

**Issue by hollowsmart** [DIGITALCRIMINALS/OnlyFans#788]
New errors again. I've migrated the config and profiles folder as directed in the "27th January 2023 Migration"
Run updater.py twice, tried reinstalling and updating python.

> 
> Traceback (most recent call last):
>   File "D:\Downloads\OF-7.6.1\start_us.py", line 82, in <module>
>     asyncio.run(main())
>   File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
>     return future.result()
>   File "D:\Downloads\OF-7.6.1\start_us.py", line 59, in main
>     api = await main_datascraper.start_datascraper(
>   File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
>     await default(datascraper)
>   File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 48, in default
>     await main_helper.process_profiles(api, global_settings)
>   File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 605, in process_profiles
>     temp_json_auth = import_json(user_auth_filepath)
>   File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 393, in import_json
>     json_file = orjson.loads(o_file.read())
> orjson.JSONDecodeError: unexpected content after document: line 14 column 1 (char 441)

**Comment by hollowsmart** [comment]
Okay, I've deleted and ran the script again to create a new auth.json which has resolved this issue. Now currently facing the same KeyError: 'user_id' issue as #786 

> Traceback (most recent call last):
  File "D:\Downloads\OF-7.6.1\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Personal\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Downloads\OF-7.6.1\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\Downloads\OF-7.6.1\ultima_scraper\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await datascraper.account_setup(
  File "D:\Downloads\OF-7.6.1\ultima_scraper\modules\module_streamliner.py", line 550, in account_setup
    authed = await auth.login()
  File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 100, in login
    self.session_manager.headers = create_headers(*a)
  File "C:\Users\Personal\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-4BgXF0HY-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 207, in create_headers
    headers.pop(remove_header)
KeyError: 'user_id'
