### ISSUE TITLE
Fix Browser Auth

### ISSUE THREAD

**Issue by blairg23** [DIGITALCRIMINALS/OnlyFans#79]
Whenever I try to run the latest version of the scraper, I get the following:

```
Select Site: 0 = onlyfans | 1 = fansly |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 59, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/datascraper/main_datascraper.py", line 69, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/modules/onlyfans.py", line 117, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/extras/OFLogin/start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "/mnt/i/Pr0ns/programs/scrapers/OnlyFans/extras/OFLogin/start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "/home/neophile/.virtualenvs/onlyfans-scraper/lib/python3.10/site-packages/seleniumwire/webdriver/browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/home/neophile/.virtualenvs/onlyfans-scraper/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 175, in __init__
    self.service.start()
  File "/home/neophile/.virtualenvs/onlyfans-scraper/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self.assert_process_still_running()
  File "/home/neophile/.virtualenvs/onlyfans-scraper/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /mnt/i/Pr0ns/programs/scrapers/OnlyFans/extras/OFLogin/geckodriver.exe unexpectedly exited. Status code was: 64
```

**Comment by americanseeder1865** [comment]
This is broken. I haven't had time to fully develop a solution

**Comment by blairg23** [comment]
> This is broken. I haven't had time to fully develop a solution

Is this working yet? Or is there a workaround? I'm on Windoze 10.

**Comment by HoneyBadger116** [comment]
same issue here

**Comment by blairg23** [comment]
What is causing this issue? I've pulled the latest master branch and still experience this issue. Is there some other OS / Python version I should be using? It doesn't seem like others are experiencing this?

**Comment by blairg23** [comment]
After much frustration and trying every possible solution for Windows 10, I came up with the following observations:
1. This will never work on GIT bash for Windows (unless someone figures out how to get the Visual Studio C++ Build Tools working in GIT bash for Windows).
2. Geckodriver is broken for Ubuntu for Windows Subsystem for Linux (WSL). Downloading the latest driver (0.30.0 from https://github.com/mozilla/geckodriver/releases) did fix the original issue. HOWEVER, after 10 failed attempts, the script tries to open a new Firefox browser which doesn't allow any logging in and fails Captcha endlessly.
3. Trying this on my Ubuntu standalone laptop worked, but you can't simply copy/paste the cookie, you need to pull out only the `auth_id` and the `sess` or it will fail with `too many values to unpack` Python error.

Hope this helps any fellow OF scrapers out there!

**Comment by blairg23** [comment]
Here's another clue...
1. I just had this exact same problem on a different library in windows using Python 3.10. I switched to Python 3.9 and the error went away. So it's something with Python 3.10 that's causing the C++ library issue with `io.h` even though I have it installed.

**Comment by DIGITALCRIMINALS** [comment]
I'm disabling browser authentication for now.

**Comment by god43** [comment]
looks like this issue is back.

**Comment by blairg23** [comment]
I'm no longer having this issue.
