### ISSUE TITLE
'create_post' object has no attribute 'fromUser'

### ISSUE THREAD

**Issue by ffrie80** [DIGITALCRIMINALS/OnlyFans#792]
I gave up on trying to make the script work on my other machine so I started fresh in a different computer (mac). I am finally being able to get pass the auth section, but when I choose one (or all) profiles to download I get the following error:

```
Traceback (most recent call last):
  File "/OFDL/start_us.py", line 82, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/OFDL/start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "/OFDL/ultima_scraper/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/OFDL/ultima_scraper/datascraper/main_datascraper.py", line 107, in default
    await datascraper.start_datascraper(job_user_list)
  File "/OFDL/ultima_scraper/modules/module_streamliner.py", line 96, in start_datascraper
    identifier=paid_content.fromUser.username,
AttributeError: 'create_post' object has no attribute 'fromUser'
```

Any ideas what I might be doing wrong or how I could fix it? Thanks!

**Comment by PsychoSid** [comment]
See - https://github.com/DIGITALCRIMINALS/OnlyFans/issues/785

**Comment by ffrie80** [comment]
Thanks @PsychoSid! I'll continue the discussion on that post.
