### ISSUE TITLE
Event Loop Closed (Newest Commit) 

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#798]
Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans Scrapper\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "D:\OnlyFans Scrapper\ultima_scraper\datascraper\main_datascraper.py", line 107, in default
    await datascraper.start_datascraper(job_user_list)
  File "D:\OnlyFans Scrapper\ultima_scraper\modules\module_streamliner.py", line 96, in start_datascraper
    identifier=paid_content.fromUser.username,
AttributeError: 'create_post' object has no attribute 'fromUser'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001852BEFBA30>
Traceback (most recent call last):
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "D:\Users\USER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Site3op** [comment]
Happens both on onlyfans and fansly options.

**Comment by Site3op** [comment]
Confirmed its happening on a fresh install as well.

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/785
