### ISSUE TITLE
Fansly Module Error

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#8]
Traceback (most recent call last):
  File "D:\OnlyFans Scrapper\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "D:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans Scrapper\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans Scrapper\datascraper\main_datascraper.py", line 131, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\OnlyFans Scrapper\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "D:\OnlyFans Scrapper\modules\fansly.py", line 1283, in manage_subscriptions
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
  File "D:\OnlyFans Scrapper\modules\fansly.py", line 1283, in <lambda>
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
TypeError: 'NoneType' object is not subscriptable

This occurs after selecting the Fansly profile and after the welcome username.

**Comment by americanseeder1865** [comment]
Is this on the latest commit?

**Comment by Site3op** [comment]
> Is this on the latest commit?

Correct.

**Comment by RonnieBlaze** [comment]
i get the same thing when trying the new fansly part

**Comment by DIGITALCRIMINALS** [comment]
It was due to expired subscriptions

**Comment by sdfasf225** [comment]
I'm still getting this issue with the latest commit.

**Comment by DIGITALCRIMINALS** [comment]
> I'm still getting this issue with the latest commit.

Who are you subscribed to?

**Comment by ttrv65ebyng** [comment]
This issue still occurs on the latest commit when following a user that has deleted/deactivated their fansly account. I get a reference to a user that no longer exists right before the crash. Unfortunately, fansly doesn't provide a way to unfollow the account after it was deactivated, so when running downloads on all models, it crashes when hitting a model that has deactivated their account, and there's seemingly no way for me to prevent this atm.
