### ISSUE TITLE
Error: {'code': 0, 'message': 'oliviahartlond1 not found'}

### ISSUE THREAD

**Issue by vdb1975** [DIGITALCRIMINALS/OnlyFans#802]
The object error is displayed after selecting default profile, then all the account I've subscribed are displayed.
When I choose one; the following is displayed after  some time
74
Traceback (most recent call last):
  File "D:\OnlyFans-master\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\OnlyFans-master\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 128, in start_datascraper
    await default(datascraper)
  File "D:\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 108, in default
    await datascraper.start_datascraper(job_user_list)
  File "D:\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 96, in start_datascraper
    identifier=paid_content.fromUser.username,
AttributeError: 'create_post' object has no attribute 'fromUser'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002A7D8B6FD00>
Traceback (most recent call last):
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\delta\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by DIGITALCRIMINALS** [comment]
Update the script, it's already been fixed.

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/785
