### ISSUE TITLE
Error: {'code': 0, 'message': 'messages?limit=10&offset=121&order=desc not found'}

### ISSUE THREAD

**Issue by Nostang3** [DIGITALCRIMINALS/OnlyFans#817]
Recently converted over to the poetry version and when running the script I get this towards the end. I've ran it a couple times with the same result. Tried to search to see if there was something similar so I could have missed it. Wanted you to be aware.

I'm running this on windows 10 with python 3.11.

```
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████| 3/3 [00:00<00:00, 999.04it/s]
Error: {'code': 0, 'message': 'messages?limit=1&offset=0&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=141&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=91&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=71&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=41&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=61&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=31&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=131&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=101&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=81&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=51&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=11&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=21&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=111&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=121&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=1&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=151&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=161&order=desc not found'}
Processing Scraped Messages
100%|████████████████████████████████████████████████| 74/74 [00:00<00:00, 9241.58it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████| 74/74 [00:00<00:00, 10561.40it/s]
Archive Completed in 8.13 Minutes
Input anything to continue
```

**Comment by randomhappysack** [comment]
_I tried python 3.11 and it completely broke the script for me. I reverted back to 3.10.4 to get it working..._

_Does the script support 3.11.x?_

**Comment by Telandriq** [comment]
Same bug went from 3.10.9 to 3.10.6 to see if it fixed the issue. It didn't

**Comment by hetap01** [comment]
Getting the same errors also
```
Error: {'code': 0, 'message': 'messages?limit=10&offset=50&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=150&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=160&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=190&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=10&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=200&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=80&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=40&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=120&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=90&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=0&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=100&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=30&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=20&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=110&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=70&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=220&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=210&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=130&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=60&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=230&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=170&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=180&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=140&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=0&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=170&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=20&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=10&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=220&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=210&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=200&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=30&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=110&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=190&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=80&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=150&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=70&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=90&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=40&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=60&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=130&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=100&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=180&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=230&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=120&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=160&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=50&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=140&order=desc not found'}
Error: {'code': 0, 'message': 'Story highlight not found.'}
```

Doesn't time out either, requires a Ctrl+C to stop, which provides this

```
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Onlyfans-master\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever    super().run_forever()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_downloads' was never awaited
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_scraper' was never awaited
```

**Comment by DIGITALCRIMINALS** [comment]
Latest commit should fix this
