### ISSUE TITLE
Fansly scraper not working on latest build

### ISSUE THREAD

**Issue by Bun-Bun** [DIGITALCRIMINALS/OnlyFans#820]
Doesn't even make it to any prompts past profile selection.

`Traceback (most recent call last):
  File "/root/src/onlyfans/start_us.py", line 82, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/src/onlyfans/start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "/root/src/onlyfans/ultima_scraper/datascraper/main_datascraper.py", line 134, in start_datascraper
    await default(datascraper)
  File "/root/src/onlyfans/ultima_scraper/datascraper/main_datascraper.py", line 108, in default
    await datascraper.start_datascraper(job_user_list)
  File "/root/src/onlyfans/ultima_scraper/modules/module_streamliner.py", line 86, in start_datascraper
    chat_users = await self.get_chat_users()
  File "/root/src/onlyfans/ultima_scraper/modules/module_streamliner.py", line 629, in get_chat_users
    chats = await authed.get_chats()
  File "/root/src/onlyfans/lib/python3.10/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 418, in get_chats
    results2 = await self.get_chats(
  File "/root/src/onlyfans/lib/python3.10/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 418, in get_chats
    results2 = await self.get_chats(
  File "/root/src/onlyfans/lib/python3.10/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 424, in get_chats
    final_results.extend(results2)
AttributeError: 'dict' object has no attribute 'extend'
`

**Comment by DIGITALCRIMINALS** [comment]
Fixed this in latest commit
