### ISSUE TITLE
Issue after installling Ultimate Scrapper

### ISSUE THREAD

**Issue by Mxecan** [DIGITALCRIMINALS/OnlyFans#836]
I have Python 3.10 installed.
I installed these files in a new directory.   I ran python updater.py with no problems
However when I run poetry run python start_us.py and get the following error
Traceback (most recent call last):
  File "C:\US\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\edmon\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\edmon\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\US\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "C:\US\ultima_scraper\datascraper\main_datascraper.py", line 134, in start_datascraper
    await default(datascraper)
  File "C:\US\ultima_scraper\datascraper\main_datascraper.py", line 49, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\Users\edmon\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-js9sR1O0-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 613, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "C:\Users\edmon\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-js9sR1O0-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 394, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: unexpected character: line 12 column 3 (char 442)

Any ideas?

**Comment by DIGITALCRIMINALS** [comment]
fix json file

**Comment by Mxecan** [comment]
I don't now python.  Which file and where?

**Comment by humaintenance** [comment]
@Mxecan I had this issue too. The issue will be line 12 of the config.json located at __settings__\config.json

Line 12 in my config file is for "reformat_media", which is a boolean variable, so requires either true or false. I'd start by checking that out.

My issue was line 62, I needed to enclose the the value in quotations, i.e. "All"
