### ISSUE TITLE
Errors for OF only (not fansly) with Latest Python 3.10

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINALS/OnlyFans#84]
after filling in my auth stuff for OF, i get these errors:

```
Select Site: 0 = onlyfans | 1 = fansly |
0
Traceback (most recent call last):
  File "B:\Github\OnlyFans\start_ofd.py", line 59, in <module>
    asyncio.run(main())
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "B:\Github\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "B:\Github\OnlyFans\datascraper\main_datascraper.py", line 51, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "B:\Github\OnlyFans\helpers\main_helper.py", line 912, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value

```

**Comment by HIDDENSAGE** [comment]
Having same issue

**Comment by DIGITALCRIMINALS** [comment]
You entered a invalid character in your auth.json
