### ISSUE TITLE
Sqlalchemy Issue

### ISSUE THREAD

**Issue by HoneyBadger116** [DIGITALCRIMINALS/OnlyFans#85]
Traceback (most recent call last):
  File "D:\OF Rip\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "D:\OF Rip\OnlyFans-master\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "D:\OF Rip\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "D:\OF Rip\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by dnkness** [comment]
I ended up uninstalling all versions of python, then restarted my PC, and then reinstalled the latest version and ran the pip install command again which seemed to fix the issue. Hope it works for you too

**Comment by HoneyBadger116** [comment]
OK looks like the big issue is you have to go to the windows store and install 3.10 from there. I did so just from the sites download.
