### ISSUE TITLE
ImportError: cannot import name 'CleoException'

### ISSUE THREAD

**Issue by reahari** [DIGITALCRIMINALS/OnlyFans#853]
Trying to run `poetry run python updater.py` or `python updater.py` returns the following error
```
Traceback (most recent call last):
  File "/home/$USER/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/home/$USER/.local/lib/python3.10/site-packages/poetry/console/application.py", line 15, in <module>
    from cleo.exceptions import CleoException
ImportError: cannot import name 'CleoException' from 'cleo.exceptions' (/home/$USER/.local/lib/python3.10/site-packages/cleo/exceptions/__init__.py)
```

Using Ubuntu 22.04

**Comment by DIGITALCRIMINALS** [comment]
Best to refer here

https://github.com/python-poetry/poetry/issues/3345
