### ISSUE TITLE
orjson.JSONDecodeError: unexpected character: line 14 column 3 (char 470)

### ISSUE THREAD

**Issue by Mxecan** [DIGITALCRIMINALS/OnlyFans#855]
I have no skills in json.  So as much help as you can give.
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Traceback (most recent call last):
  File "C:\US\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\edmon\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\edmon\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\US\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "C:\US\ultima_scraper\datascraper\main_datascraper.py", line 134, in start_datascraper
    await default(datascraper)
  File "C:\US\ultima_scraper\datascraper\main_datascraper.py", line 49, in default
    await main_helper.process_profiles(api, global_settings)
  File "C:\Users\edmon\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-js9sR1O0-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 613, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "C:\Users\edmon\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-js9sR1O0-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 394, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: unexpected character: line 14 column 3 (char 470)
PS C:\US>

**Comment by Klutronic** [comment]
A couple of us are seeing the same thing: [issue](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/842)

**Comment by DIGITALCRIMINALS** [comment]
You need to fix your auth.json file
