### ISSUE TITLE
Script stucked forever loading

### ISSUE THREAD

**Issue by mikebradley** [DIGITALCRIMINALS/OnlyFans#860]
I currently have this, where the script is just stucked on download metadata, ant then it takes there forever. What I see on interrupting it, I have the following message -  Does anyone know what should I modify :) 

```
^CTraceback (most recent call last):
  File "/home/mike/Documents/GitHub/OnlyFans/start_us.py", line 82, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_downloads' was never awaited
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_scraper' was never awaited
```

**Comment by rando-username** [comment]
how did  you  solve it? @mikebradley
