### ISSUE TITLE
having this issue

### ISSUE THREAD

**Issue by divakar123** [DIGITALCRIMINALS/OnlyFans#864]
Whenever I try to run scraper I Get this issue

Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Auth 404'ed
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\OnlyFans-master\OnlyFans-master\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\OnlyFans-master\OnlyFans-master\start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\OnlyFans-master\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 134, in start_datascraper
    await default(datascraper)
  File "C:\Users\Administrator\Downloads\OnlyFans-master\OnlyFans-master\ultima_scraper\datascraper\main_datascraper.py", line 75, in default
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\OnlyFans-master\OnlyFans-master\ultima_scraper\modules\module_streamliner.py", line 531, in account_setup
    authed = await auth.login()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-txH1Cz0t-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 159, in login
    user = await self.get_user(auth_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-txH1Cz0t-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 239, in get_user
    response["session_manager"] = self.session_manager
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed
