### ISSUE TITLE
uknown error?

### ISSUE THREAD

**Issue by penguinpatrol** [DIGITALCRIMINALS/OnlyFans#866]
PS F:\vr vids\AAA other\AAA downloaders\OnlyFans-7.6.1> poetry run python start_us.py
Traceback (most recent call last):
  File "F:\vr vids\AAA other\AAA downloaders\OnlyFans-7.6.1\start_us.py", line 24, in <module>
    main_test.check_start_up()
  File "F:\vr vids\AAA other\AAA downloaders\OnlyFans-7.6.1\tests\main_test.py", line 29, in check_start_up
    check_config(fsm.settings_directory)
  File "F:\vr vids\AAA other\AAA downloaders\OnlyFans-7.6.1\tests\main_test.py", line 37, in check_config
    json_config, _updated = main_helper.get_config(config_path)
  File "C:\Users\cslar\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-l1psuRRX-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 410, in get_config
    json_config = import_json(config_path)
  File "C:\Users\cslar\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-l1psuRRX-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 394, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: unexpected control character in string: line 85 column 43 (char 2209)

**Comment by penguinpatrol** [comment]
tried to re install and am getting

PS F:\OnlyFans-7.6.1> poetry run python ./start_us.py
Traceback (most recent call last):
  File "F:\OnlyFans-7.6.1\start_us.py", line 8, in <module>
    from ultima_scraper_api.helpers.main_helper import OptionsFormat
ModuleNotFoundError: No module named 'ultima_scraper_api'

**Comment by Jarsky** [comment]
When you reinstalled, did you also run the updater?
`python updater.py`

If it still doesnt work, then try running this command from the folder F:\OnlyFans-7.6.1
`poetry update`

If that doesn't work then try uninstall and reinstall poetry then run the updater
