### ISSUE TITLE
First Time running Issue

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#874]
Getting the following;

`poetry run python start_us.py
Traceback (most recent call last):
  File "/Users/thegoat/Downloads/OnlyFans-master/start_us.py", line 24, in <module>
    main_test.check_start_up()
  File "/Users/thegoat/Downloads/OnlyFans-master/tests/main_test.py", line 29, in check_start_up
    check_config(fsm.settings_directory)
  File "/Users/thegoat/Downloads/OnlyFans-master/tests/main_test.py", line 37, in check_config
    json_config, _updated = main_helper.get_config(config_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thegoat/Library/Caches/pypoetry/virtualenvs/ultima-scraper-ykJV31-G-py3.11/lib/python3.11/site-packages/ultima_scraper_api/helpers/main_helper.py", line 410, in get_config
    json_config = import_json(config_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thegoat/Library/Caches/pypoetry/virtualenvs/ultima-scraper-ykJV31-G-py3.11/lib/python3.11/site-packages/ultima_scraper_api/helpers/main_helper.py", line 394, in import_json
    json_file = orjson.loads(o_file.read())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: invalid escaped character in string: line 80 column 87 (char 1997)`

Any help?

**Comment by misterscraper** [comment]
Solved

**Comment by wildechap** [comment]
> Solved

how?

**Comment by qwuzzy** [comment]
I also have this but for line 80 column 15 (char 1933).
