### ISSUE TITLE
Auth 404'ed

### ISSUE THREAD

**Issue by fityanto17** [DIGITALCRIMINALS/OnlyFans#877]
Follow all the steps correctly. 
when running get Auth404'ed status 
reading old issues, cuz somebody have face it before
the solve method not helping and work at all.

the cmd log:

Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Auth 404'ed
Auth (V1) Attempt 4/10
Auth 404'ed
Auth (V1) Attempt 5/10
Auth 404'ed
Auth (V1) Attempt 6/10
Auth 404'ed
Auth (V1) Attempt 7/10
Auth 404'ed
Auth (V1) Attempt 8/10
Auth 404'ed
Auth (V1) Attempt 9/10
Auth 404'ed
Auth (V1) Attempt 10/10
Auth 404'ed
Traceback (most recent call last):
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\Iksan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Iksan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\modules\onlyfans.py", line 88, in account_setup
    authed = await auth.login()
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "D:\Iksan Project\Data\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

**Comment by DawidIzydor** [comment]
Are you using Google Chrome to grab cookies? For me only this browser works reliably

**Comment by DIGITALCRIMINALS** [comment]
>start_ofd.py
