### ISSUE TITLE
UnboundLocalError: cannot access local variable 'authed' where it is not associated with a value

### ISSUE THREAD

**Issue by spiderzero3** [DIGITALCRIMINALS/OnlyFans#884]
Fresh install of the latest commit, get an error shortly after running the script.

```
Error: {'code': 0, 'message': 'sggermany not found'}
Error: {'code': 0, 'message': 'gingerrrsnapps not found'}
Error: {'code': 0, 'message': 'censoredsylph not found'}
Error: {'code': 0, 'message': 'cabackup not found'}
Error: {'code': 0, 'message': 'maryjane_ev not found'}
Traceback (most recent call last):
  File "D:\OnlyFans-master-ultima-03-12-23\start_us.py", line 82, in <module>
    asyncio.run(main())
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\OnlyFans-master-ultima-03-12-23\start_us.py", line 58, in main
    api = await USR.start(
          ^^^^^^^^^^^^^^^^
  File "D:\OnlyFans-master-ultima-03-12-23\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "D:\OnlyFans-master-ultima-03-12-23\ultima_scraper\ultima_scraper.py", line 116, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-ZtAcebY7-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 134, in configure_datascraper_jobs
    if user.username in authed.blacklist:
                        ^^^^^^
UnboundLocalError: cannot access local variable 'authed' where it is not associated with a value
```

**Comment by DIGITALCRIMINALS** [comment]
Fixed all errors here
