### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/OnlyFans#889]
with the latest commit 6b92b7b89ad88043d93a01032e0e99f442bebe19

E:\OnlyFans-master>poetry run python start_us.py
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_us.py", line 71, in <module>
    asyncio.run(main())
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\OnlyFans-master\start_us.py", line 53, in main
    api = await USR.start(
          ^^^^^^^^^^^^^^^^
  File "E:\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 67, in start_datascraper
    await self.process_profiles(api, global_settings)
  File "E:\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 150, in process_profiles
    auth = api.add_auth(json_auth)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0AvWnZYd-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\onlyfans.py", line 30, in add_auth
    temp_auth_details = auth_details(auth_json).upgrade_legacy(auth_json)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0AvWnZYd-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 11, in __init__
    self.cookie = cookie_parser(options.get("cookie", ""))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0AvWnZYd-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\extras.py", line 67, in __init__
    key, value = crumble.strip().split("=", 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by DIGITALCRIMINALS** [comment]
Because you entered cookie details incorrectly.
