### ISSUE TITLE
Can't run start_us.py.

### ISSUE THREAD

**Issue by puzi12138** [DIGITALCRIMINALS/OnlyFans#914]
PS C:\Users\xxx\Downloads\OnlyFans-7.6.1> poetry run python start_us.py
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\start_us.py", line 22, in <module>
    main_test.check_start_up()
  File "C:\Users\xxx\Downloads\OnlyFans-7.6.1\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'

**Comment by puzi12138** [comment]
I ran the updater for twice and it's done,maybe it cant download all the updates for only once
