### ISSUE TITLE
Profiles that will not scrape

### ISSUE THREAD

**Issue by RonnieBlaze** [DIGITALCRIMINALS/OnlyFans#93]
still having problems with 2 free profiles that will not scrape. bellathorne and petitepixie69
I know you said they both seem to work for you.

After starting with a fresh config.json file i was able to get it to scrape the petitepixie69 profile but not the bellathorne  profile.
After adding my ignored_keywords of "trial", "subscribe to", "@", "free" the petitepixie69  profile no longer scrapes, I even tried each ignored keyword be its self and they all error the same way See below.

Scrape Processing
Name: petitepixie69
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
  0%|                                                                                          | 0/769 [00:00<?, ?it/s]Matches:  ['free']
Matches:  ['subscribe to']
Matches:  ['free']
Matches:  ['free']
Matches:  ['free']
Matches:  ['free']
Matches:  ['free']
Matches:  ['free']
Matches:  ['free']
  0%|                                                                                  | 1/769 [00:00<02:04,  6.17it/s]Traceback (most recent call last):
  File "F:\Users\xxx\Downloads\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\Users\xxx\Downloads\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\Users\xxx\Downloads\OnlyFans\datascraper\main_datascraper.py", line 96, in start_datascraper
    await main_helper.process_names(
  File "F:\Users\xxx\Downloads\OnlyFans\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 1136, in media_scraper
    matches = [s for s in ignored_keywords if s in final_text]
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 1136, in <listcomp>
    matches = [s for s in ignored_keywords if s in final_text]
TypeError: argument of type 'NoneType' is not iterable

When trying to scrape Bella's profile with a fresh config i get the below error that is different then the other.

bellathorne
Scrape Processing
Name: bellathorne
Type: Profile
Type: Stories
Scrape Attempt: 1/100
Processing Scraped Stories
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 399.84it/s]
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.06it/s]
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "F:\Users\xxx\Downloads\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\Users\xxx\Downloads\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\Users\xx\Downloads\OnlyFans\datascraper\main_datascraper.py", line 96, in start_datascraper
    await main_helper.process_names(
  File "F:\Users\xxx\Downloads\OnlyFans\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "F:\Users\xxx\Downloads\OnlyFans\modules\onlyfans.py", line 793, in prepare_scraper
    master_set += await subscription.get_archived_posts()
  File "F:\Users\xxx\Downloads\OnlyFans\apis\onlyfans\classes\create_user.py", line 430, in get_archived_posts
    final_results = [create_post(x, self) for x in results if x]
  File "F:\Users\xxx\Downloads\OnlyFans\apis\onlyfans\classes\create_user.py", line 430, in <listcomp>
    final_results = [create_post(x, self) for x in results if x]
  File "F:\Users\xxx\Downloads\OnlyFans\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

I hope my finding that the ignored_keywords is causing the issue for the one profile to be helpful, I was hoping that it would have fixed both of the profile problems that I am having.  Since they are both free profiles if anyone else would like to see if they can or can not scrape them using the same ignored keywords that i used might be helpful.

**Comment by DIGITALCRIMINALS** [comment]
Run the updater script

**Comment by RonnieBlaze** [comment]
> 
> 
> Run the updater script

that seems to have fixed it!
