### ISSUE TITLE
RasPi Python3.10 Issues

### ISSUE THREAD

**Issue by ilyesm** [DIGITALCRIMINALS/OnlyFans#95]
Hi there,

I was having issues with SQLite3 on my RasPi running Python 3.10. I uninstalled and reinstalled SQLite3, but now I get the following error every time I try to run the start_ofd.py file.

`pi@rpi-pro:~/OF/onlyfans $ python3 start_ofd.py 
Traceback (most recent call last):
  File "start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "/home/pi/OF/onlyfans/tests/main_test.py", line 58
    match string_match:
                     ^
SyntaxError: invalid syntax`

Any suggestions?

Thanks.
I

**Comment by ilyesm** [comment]
I have managed to solve this by just running python start_ofd.py, but now, I get the following line repeated thousands of times per second after initiating the script.

`No module named '_sqlite3'`

Trace:

`pi@rpi-pro:~/OF/onlyfans $ python start_ofd.py 
Select Site: 0 = onlyfans | 1 = fansly | 
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome ***** | *****
Scraping Paid Content
Scraping - elenaxx | 1 / 5
Scraping - momanddaughter | 2 / 5
Scraping - petitfreak69b | 3 / 5
Scraping - lexypanterra | 4 / 5
Scraping - wonderjuz | 5 / 5
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = elenaxx | 2 = momanddaughter | 3 = petitfreak69b | 4 = lexypanterra | 5 = wonderjuz
1
Scrape Processing
Name: elenaxx
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
1
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1222/1222 [00:00<00:00, 1291.56it/s]
Processing metadata.
Finished processing metadata.
No module named '_sqlite3'
**(omitted for brevity)**
No module named '_sqlite3'
^CTraceback (most recent call last):
  File "/home/pi/OF/onlyfans/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/OF/onlyfans/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/home/pi/OF/onlyfans/datascraper/main_datascraper.py", line 98, in start_datascraper
    await main_helper.process_names(
  File "/home/pi/OF/onlyfans/helpers/main_helper.py", line 959, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/home/pi/OF/onlyfans/modules/onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/home/pi/OF/onlyfans/modules/onlyfans.py", line 841, in prepare_scraper
    await process_metadata(
  File "/home/pi/OF/onlyfans/modules/onlyfans.py", line 665, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/home/pi/OF/onlyfans/helpers/main_helper.py", line 551, in export_sqlite
    db_helper.run_migrations(alembic_location, database_path)
  File "/home/pi/OF/onlyfans/helpers/db_helper.py", line 57, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/pi/.local/lib/python3.10/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/pi/.local/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/pi/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/pi/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pi/OF/onlyfans/database/databases/user_data/alembic/env.py", line 79, in <module>
    run_migrations_online()
  File "/home/pi/OF/onlyfans/database/databases/user_data/alembic/env.py", line 61, in run_migrations_online
    connectable = engine_from_config(
  File "/home/pi/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 743, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/home/pi/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/pi/.local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 473, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap>", line 556, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 397, in cached
  File "<frozen importlib._bootstrap_external>", line 513, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 417, in cache_from_source
KeyboardInterrupt`

**Comment by DIGITALCRIMINALS** [comment]
Gonna have to search on Google for this on sir

**Comment by reahari** [comment]
You could always try installing it

`sudo apt-get install sqlite3`

`python3.9 -m pip install pysqlite`
