### ISSUE TITLE
Error when scraping an OF account that has URLs in the posts name

### ISSUE THREAD

**Issue by Jbry22** [DIGITALCRIMINALS/OnlyFans#96]
I assume that due to the posts having a URL in them, this error below is given - although I could be totally wrong as its simply a guess. 

The scraper is fully updated and so are the requirements needed.

If there is a way around or a fix for this so I can scrape the user, it would be much appreciated if anyone can help.

This is also a free OF account so can be subscribed to and see if the error can be replicated.

Thanks!

```Scrape Processing
Name: planesgirl
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
  0%|                                                                                           | 0/45 [00:00<?,it/s] 
 C:\Users\B\AppData\Roaming\Python\Python310\site-packages\bs4\__init__.py:431: MarkupResemblesLocatorWarning: "https://fans.ly/r/planesgirl" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\B\Desktop\OnlyFans-7.5\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\B\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\B\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\B\Desktop\OnlyFans-7.5\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\B\Desktop\OnlyFans-7.5\datascraper\main_datascraper.py", line 98, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\B\Desktop\OnlyFans-7.5\helpers\main_helper.py", line 959, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\B\Desktop\OnlyFans-7.5\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\B\Desktop\OnlyFans-7.5\modules\onlyfans.py", line 824, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\B\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\B\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\B\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\B\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\B\Desktop\OnlyFans-7.5\modules\onlyfans.py", line 1169, in media_scraper
    file_path = await main_helper.reformat(prepared_format, filename_format)
  File "C:\Users\B\Desktop\OnlyFans-7.5\helpers\main_helper.py", line 655, in reformat
    text = clean_text(text)
  File "C:\Users\B\Desktop\OnlyFans-7.5\helpers\main_helper.py", line 108, in clean_text
    string = string.replace(m, " ").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by DIGITALCRIMINALS** [comment]
What is the file format in the config

**Comment by Jbry22** [comment]
`{date}-{media_id}-{text}.{ext}`

**Comment by DIGITALCRIMINALS** [comment]
Update script
