### ISSUE TITLE
ModuleNotFoundError on Mac

### ISSUE THREAD

**Issue by pummer** [DIGITALCRIMINALS/OnlyFans#969]
`➜  ultimascraper-master poetry run python3 start_us.py`
`Traceback (most recent call last):`
`   File "/Users/xxxxxx/UltimaScraper-master/start_us.py", line 13, in <module>`
`    main_test.check_start_up()`
`  File "/Users/xxxxxx/UltimaScraper-master/tests/main_test.py", line 21, in check_start_up`
`    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager`
`ModuleNotFoundError: No module named 'ultima_scraper_collection'`

This is what I get when I try to start the program for the first time. I'm on an Intel Mac using 13.1 Ventura. Python 3.11

**Comment by CucciPro** [comment]
run `xcode-select --install` in terminal, followed by `poetry run python updater.py` as I assume the issue is that psycopg2 fails to install.
