### ISSUE TITLE
Issues running onlyfans scrapper: 401 Unauthorized

### ISSUE THREAD

**Issue by bryanhsu00** [DIGITALCRIMINALS/OnlyFans#975]
I am using mac running with the latest version, after following the instruction copying the cookie, x_bc, user_agent values I still get the following errors. I noticed after I modified the auth.json and run the scrapper. The scrapper will modify my config and I wonder this behavior is normal or not. 

I have also been logout from the onlyfans after running this scrapper. Down below is my error messages.

Also, I wonder what the value should the "username" may be ? The value is "default" by default. Should it be my username or user id ?

Thanks for your help.

```
Traceback (most recent call last):
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_api/managers/session_manager.py", line 203, in request
    result.raise_for_status()
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://onlyfans.com/api2/v2/users/me')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bryan/Downloads/UltimaScraper/start_us.py", line 62, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bryan/Downloads/UltimaScraper/start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "/Users/bryan/Downloads/UltimaScraper/ultima_scraper/ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "/Users/bryan/Downloads/UltimaScraper/ultima_scraper/ultima_scraper.py", line 88, in start_datascraper
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 382, in account_setup
    authed = await auth.login()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_api/apis/onlyfans/classes/auth_model.py", line 109, in login
    await self.process_auth()
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_api/apis/onlyfans/classes/auth_model.py", line 165, in process_auth
    json_resp = await self.session_manager.json_request(link)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_api/managers/session_manager.py", line 229, in json_request
    response = await self.request(url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/Library/Caches/pypoetry/virtualenvs/ultima-scraper-vgTApnKf-py3.11/lib/python3.11/site-packages/ultima_scraper_api/managers/session_manager.py", line 219, in request
    raise Exception(
Exception: Infinite Loop Detected for unhandled status error: 401

```

**Comment by irontusk5** [comment]
I had the exact same issue but I was editing the auth.json file located under \.profiles\OnlyFans\default

It worked for me after editing the auth.json file located under \__user_data__\profiles\OnlyFans\default

**Comment by majortawhid** [comment]
> 

what exactly you edited in the auth.json file

**Comment by irontusk5** [comment]
@majortawhid 
I added the: username, cookie, user_agent and x_bc values to that file. 
Instructions are here: https://github.com/DIGITALCRIMINALS/UltimaScraper
