### ISSUE TITLE
ModuleNotFoundError: No module named 'ultima_scraper_collection.managers.datascraper_manager'

### ISSUE THREAD

**Issue by xxx-uploaded** [DIGITALCRIMINALS/OnlyFans#984]
Today I updated the script with a command **python updater.py** and an error popped up, please tell me what to do?

E:\python-3.10.5\OnlyFans-master1>poetry run python start_us.py
Traceback (most recent call last):
  File "E:\python-3.10.5\OnlyFans-master1\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "E:\python-3.10.5\OnlyFans-master1\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-fbdRxbVM-py3.10\lib\site-packages\ultima_scraper_collection\__init__.py", line 1, in <module>
    from ultima_scraper_collection.managers.datascraper_manager.datascrapers.fansly import (
ModuleNotFoundError: No module named 'ultima_scraper_collection.managers.datascraper_manager'

**Comment by xxx-uploaded** [comment]
• Installing ultima-scraper-collection (1.0.3): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: 'C:\\Users\\Аdmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\ultima-scraper-fbdRxbVM-py3.10\\Lib\\site-packages\\ultima_scraper_collection\\managers\\database_manager\\connections\\sqlite\\legacy_databases\\messages\\migration\\alembic\\versions\\2c36fcc0b921_content.py'

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\poetry\installation\wheel_installer.py:56 in write_to_fs
       52│             # Due to the parallel installation it can happen
       53│             # that two threads try to create the directory.
       54│             os.makedirs(parent_folder, exist_ok=True)
       55│
    →  56│         with open(target_path, "wb") as f:
       57│             hash_, size = copyfileobj_with_hashing(stream, f, self.hash_algorithm)
       58│
       59│         if is_executable:
       60│             make_file_executable(target_path)

**Comment by okanshine** [comment]
same problem

**Comment by Crazylocust** [comment]
Have you found the solution?

**Comment by fightcancer2** [comment]
Same issue.  Fresh installation.
