### ISSUE TITLE
Many errors, can't get this to work

### ISSUE THREAD

**Issue by WellSomething** [DIGITALCRIMINALS/OnlyFans#986]
Up until now I've been using OnlyFans-v7.6.1-master, a 12/4/2021... today I began using it again and noticed that videos in Messages weren't being scraped or downloading, so began looking into UltimaScraper latest commit. I'm quite sure I followed all the steps, and don't know what else to do.

Windows 10 machine just in case, here are the errors:

M:\XXXXXXX\OnlyFans\UltimaScraper-master-050423>poetry run python start_us.py
Choose Profiles: 0 = All | 1 = default
1
Traceback (most recent call last):
  File "M:\XXXXXXX\OnlyFans\UltimaScraper-master-050423\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "M:\XXXXXXX\OnlyFans\UltimaScraper-master-050423\start_us.py", line 44, in main
    _api = await USR.start(
  File "M:\XXXXXXX\OnlyFans\UltimaScraper-master-050423\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "M:\XXXXXXX\OnlyFans\UltimaScraper-master-050423\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, subscriptions = await datascraper.account_setup(
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 402, in account_setup
    await datascraper.manage_subscriptions(
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 352, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 157, in get_all_subscriptions
    results = await authed.get_subscriptions(
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 360, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 331, in multi
    results2 = await asyncio.gather(*tasks)
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 245, in get_user
    response = await self.session_manager.json_request(link)
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 230, in json_request
    json_resp = await response.json()
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\aiohttp\client_reqrep.py", line 1099, in json
    await self.read()
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\aiohttp\client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
  File "C:\Users\MyUserNameHere\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0A37jgh--py3.10\lib\site-packages\aiohttp\streams.py", line 349, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by El-tra** [comment]
That's exactly, what I get. Obviously there is something on our side, as others are more successful. Got no help/hint either. :(
[#954](https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/954)
